### ISSUE TITLE
maltrail stop working

### ISSUE THREAD

**Issue by birka1** [stamparm/maltrail#103]
hi
why the sensor is stop working after a few days and i need to restart it ?

can i run it like a service ? (i guess it's linux question)

thanks

**Comment by stamparm** [comment]
1) You should check the content of `/var/log/maltrail/error.log`. Also, there has been a patch (month ago) related to newer versions of pcapy that caused problems with sudden sensor stops

2) To run it as a service (adjust the variable `MALTRAIL_DIR` to your checkout location):

```
cat > /etc/init.d/maltrail << "EOF"
#!/bin/bash
#
### BEGIN INIT INFO
# Provides: maltrail
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start/stop Maltrail sensor/server
### END INIT INFO

MALTRAIL_DIR=/opt/maltrail

case "$1" in
    start)
        $MALTRAIL_DIR/server.py &>/dev/null &
        $MALTRAIL_DIR/sensor.py &>/dev/null &
        ;;
    stop)
        pkill -f "$MALTRAIL_DIR/server.py"
        pkill -f "$MALTRAIL_DIR/sensor.py"
        ;;
    restart)
        $0 stop
        sleep 5
        $0 start
        ;;
    *) 
        echo $"Usage: $0 {start|stop|restart}" 
        exit 1
        ;;
esac
exit $?
EOF

chmod +x /etc/init.d/maltrail
service maltrail start
```

**Comment by birka1** [comment]
hi
1. error.log is empty 
2. thanks for the service configuration

3. Are the trails automatically updated?

**Comment by stamparm** [comment]
`Are the trails automatically updated?` - yup. every 24 hours by default
