### ISSUE TITLE
Bug: Fail2ban http endpoint contains memory leak

### ISSUE THREAD

**Issue by jkellerer** [stamparm/maltrail#10874]
### Finding
The newly added "/fail2ban" endpoint is a great idea, however based on my understanding it contains a partial memory leak. I'm calling it partial, since it is appears in a LRU map that stores up to 10000 IP lists based on default config, so it wont grow past this point.

#### Cache Key
Method `_fail2ban` caches results created by reading logs for ~8 seconds using the following cache key:
https://github.com/stamparm/maltrail/blob/44d8deddc7a199501597687f2d1b5c79b018b0c8/core/httpd.py#L450-L451
The cache key only depends on server time, so a requester has no chance to influence its value.

#### Cache Read
If a request is made twice within the ~8 seconds range, the previously cached IP list is returned.
https://github.com/stamparm/maltrail/blob/44d8deddc7a199501597687f2d1b5c79b018b0c8/core/httpd.py#L458-L461

#### Cache Write
If this is the first request for the cache key, a new list is generated and stored in the LRU cache.
https://github.com/stamparm/maltrail/blob/44d8deddc7a199501597687f2d1b5c79b018b0c8/core/httpd.py#L468-L471

### Conclusion
While caching is in general not a bad idea, in this case there's no need for more than 1 cached result since previous cache values are not accessible. As by default the LRU map has a capacity of 10000, this means that up to 9999 IP lists fill up RAM without being useful.

E.g. when fixing this with minimal efforts, the cache should at least be cleared before writing to it, since we only have one result at most that requires caching. Probably better would be to not use a LRU map at all and just cache the content in a single tuple together with the cache key for comparison.

**Comment by stamparm** [comment]
@jkellerer thank you for this well written issue. Find it "patched" now

p.s. main idea was/is to prevent the server application DoS attack through continuous request(s) for fail2ban list (i.e. the list creation itself require usage of server time)
