### ISSUE TITLE
stuck in loading screen

### ISSUE THREAD

**Issue by ihacku** [stamparm/maltrail#11]
Browser keeps request http://serverip:8338/events?date=2015-12-16
until chrome tab crash

![image](https://cloud.githubusercontent.com/assets/2731416/11834103/220fcd1c-a404-11e5-807e-237619a79358.png)

probably too many events? after i stop server.py, The dashboard shows some data
![image](https://cloud.githubusercontent.com/assets/2731416/11834245/7c84b040-a405-11e5-95f3-059802dfff38.png)

**Comment by stamparm** [comment]
How many events are there? You could go to the /var/log/maltrail and just tell me the sizes of file(s) there. On our production (2x1Gbps with TONS of users) we have cca. 2 million events (cca. 300 mb) each day. Loading takes around 1 minute at the end of the day.

If you see that browser really crunches something, let it do the job and tell me the final numbers (number of events and required time)

**Comment by stamparm** [comment]
I am wondering which events have caused this. I am planning to deal with this kind of cases by restraining some too obvious floods of events (e.g. more than 100k of same event should be enough to say that something is wrong with the threat itself)

**Comment by ihacku** [comment]
Log size is 257M, maltrail treats chinese character UA as a threat(heuristic), but it's used by our app.
This might be the reason why there're so many events in a short time. Can i whitelist this?

**Comment by stamparm** [comment]
I'll remove/modify the problematic rule and let you know. Also, going to deal with similar flood events in more gratious way. For whitelisting, there is a file whitelist.txt, but please currently avoid its changes

**Comment by stamparm** [comment]
@ihacku i believe that with the latest commit your UA won't trigger the problematic rule

**Comment by ihacku** [comment]
Thanks for the quick response, it works.
And there're other UA which trigger the rule,I have checked the ip, it's not fake spider.
Baiduspider-image+(+http://www.baidu.com/search/spider.htm)
BaiduSpider (+http://www.baidu.com)
Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)
SogouMobileTool/4.4.2 (Linux; U; Android 4.4.2; Readboy_G35 Build/KVT49L)
Sogou Pic Spider/3.0(+http://www.sogou.com/docs/help/webmasters.htm#07)
