### ISSUE TITLE
Feature Request: Read logs from elasticsearch

### ISSUE THREAD

**Issue by dbinoj** [stamparm/maltrail#112]
Our sensor server does not have huge HDDs, so we ship the log over the wire to our log store which runs elasticsearch. Any plans to support ES in addition to text files? Or can you provide us with any pointers which will help us develop a new input sytem for the server.py script? Else we would have to store the text files again somewhere else and let the server script read from it. No central logging :cry:

**Comment by stamparm** [comment]
Well, Maltrail expects a data to be in RAW log format. Retrieving of data
from Elasticsearch is something that doesn't sound like "compatible" or
"doable". In such low storage cases there is an option where one server
(UDP_ADDRESS, UDP_PORT) is used as an aggregator while sensors are pushing
events toward it (LOG_SERVER).

**Comment by dbinoj** [comment]
Makes sense. For now then I'll store logs in ES and as RAW log files using syslog-ng and let server.py read the log files. I'll be writing the logs in 2 places, but will solve the problem for now. I just hope syslog-ng has some config option which tells it not to add syslog headers in front of each log line. In the future, maybe we can write a script which downloads logs from ES to local store in RAW format for the selected date so that server.py works out of the box :)
