### ISSUE TITLE
DNS sinkhole zonefile feed from malc0de.com protected by Cloudflare

### ISSUE THREAD

**Issue by dbinoj** [stamparm/maltrail#114]
The feed https://malc0de.com/bl/ZONES is protected by cloudflare and maltrail is not able to download the list because it needs to solve a CAPTCHA before downloading. I dont see how this can be fixed unless someone downloads the list and hosts it somewhere like github regularly (like https://github.com/firehol/blocklist-ipsets, although they does not have malc0de's zone files) or malc0de.com should make an exception for IP lists in their cloudflare page rules.

**Comment by stamparm** [comment]
On regular IPs there is no captcha. Just tried. Cloudflare presents captcha for sure if you are behind a Tor. In case that multiple lists "fail" I could make a periodic stash somewhere.

**Comment by dbinoj** [comment]
I'm not behind tor and I reproduced this over 3 leased lines, all different
ISPs and on a residential ADSL line. Maybe my country's score on cloud
flare is low? Btw, the leased lines and ADSL connection I tried are in
different cities too. This led me to speculate that cloud flare presented
captcha to my entire state/country.

On 07-Nov-2016 1:43 pm, "Miroslav Stampar" <notifications@github.com> wrote:

On regular IPs there is no captcha. Just tried. Cloudflare presents captcha
for sure if you are behind a Tor. In case that multiple lists "fail" I
could make a periodic stash somewhere.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stamparm/maltrail/issues/114#issuecomment-258771221>,
or mute the thread

**Comment by dbinoj** [comment]
![image](https://cloud.githubusercontent.com/assets/831913/20055036/66225652-a505-11e6-81b4-82a25ad0664c.png)

**Comment by stamparm** [comment]
Then it seems that your IP is blocked by the Cloudflare. Probably bad IP reputation :)

**Comment by dbinoj** [comment]
That's the thing I'm trying to clarify here... Assuming that my IP has bad reputation, I tried with 3 different ISPs and even from a home connection in another city. Result is still the same :)

**Comment by dbinoj** [comment]
I guess my whole country's reputation is low

**Comment by jjjan** [comment]
your ip isn't in bad reputation. if you have worked in Cloudflare there is mechanism that can make this page for ip that may would be in bad reputation like India, North korea and etc...

**Comment by dbinoj** [comment]
Exactly! So the options I see for users in these countries are

1. Ask cloudflare if anything can be done
2. Ask malc0de if a less strict rule can be applied for the URLs which will be accessed by scripts.
3. Someone in areas where the links are accessible easily can run a cron job every 12 or 24 hrs and push the changes to github.
4. Affected people can rent a VPN/VPS outside their country and tunnel the traffic of maltrail through that service. This will work for sure but is too costly and not feasible for small/not for profit networks.

**Comment by dbinoj** [comment]
We had a VPS outside our country which we use to monitor uptime of websites. I've written a script in it to clone all maltrail feeds and push it to https://github.com/dbinoj/maltrail-feeds-mirror. I'm not having cloudflare issues in that server. I've also uploaded the script so that others can also host mirrors. I'm thinking of a new feature in maltrail which will try a mirror if the primary source fails. And the mirror can be configurable in maltrail.conf with a configuration option like `MIRROR_REPO dbinoj/maltrail-feeds-mirror`
Right now I'm just changing my maltrail sensor's relevant feed's .py file with the github raw url, which is pain when updating maltrail itself. What do you think of the mirror/script/idea? Feedback please.

**Comment by stamparm** [comment]
There is a nice option `UPDATE_SERVER` that could solve your problem. It goes like this. You can just leave a `server.py` or rerun `server.py` (or `sensor.py`) once a day on that VPS, pick resulting `trails.csv` and put it to some HTTP visible location (e.g. `/var/www/trails.csv`) - by using e.g. `cron`. Then, at the sensor side put into the configuration file `UPDATE_SERVER http://<your_vps_address>/trails.csv`. That way you'll have the problem sorted in the cleanest possible way.

**Comment by stamparm** [comment]
p.s. instead of running `sensor.py` or `server.py` for retrieving/updating trails at that VPS location you can run (from maltrail directory): `python core/update.py`

**Comment by dbinoj** [comment]
Ah... Thanks. I didn't know `/trails` just served the csv from user directory. Thought I had to run the sensor on the VPS too and hence came up with this crazy mirror solution. I'll stop my now useless mirror script and run update.py instead :) thanks for the help.

**Comment by dbinoj** [comment]
I've updated the mirror script which I had to push the trails.csv to github. So that even others who have the same issue can use the mirror with:
```
UPDATE_SERVER https://media.githubusercontent.com/media/dbinoj/maltrail-update-mirror/master/trails.csv
```
I'm currently updating 4 times a day.

**Comment by stamparm** [comment]
Cool :)
