### ISSUE TITLE
New sinkhole?

### ISSUE THREAD

**Issue by youradds** [stamparm/maltrail#11491]
Hi,

This one just got through for me:

87.106.18.141

How do I go about adding this to the sinkhole list? 

Thanks

Andy

**Comment by MikhailKasimov** [comment]
Hello!

If it's known who sinkholer is, then make pull-request in format ```sinkhole_<name of sinkholer>.txt```. If name of sinkholer is unknown, then put IP into ```sinkhole_unknown.txt``` trail:  https://github.com/stamparm/maltrail/blob/master/trails/static/malware/sinkhole_unknown.txt

BTW: Thanks for hint about this IP: all ```.at``` domains from it gonna go to ```ursnif.txt``` trail (not all of them are covered by detection right now).
