### ISSUE TITLE
UA to add

### ISSUE THREAD

**Issue by DigiAngel** [stamparm/maltrail#115]
These are safe/known:

Symantec Endpoint Protection/12.1.0.0 (SMR 5.1.0; dummy)

Thank you!

**Comment by xECK29x** [comment]
Should add wildcards for the versions but +1 should be whitelisted, somehow.

Sent from Alto
On Tuesday, November 8, 2016 at 9:55 AM DigiAngel <notifications@github.com> wrote:

These are safe/known:

Symantec Endpoint Protection/12.1.0.0 (SMR 5.1.0; dummy)

Thank you!
