### ISSUE TITLE
Question:  How do you use custom rules?

### ISSUE THREAD

**Issue by DigiAngel** [stamparm/maltrail#116]
Topic :)  Just add a domain or ip?  Or anything more than that?  Say I want to have a trail that will show "chat app" or something...how do I get that to fly?  Thanks.

**Comment by stamparm** [comment]
Custom rules can be any of: IP, DNS or URL (or only HTTP directory path). Original idea is that those values can be easily distinguished if put into one bulk file line by line.

**Comment by DigiAngel** [comment]
Perfect...thank you!
