### ISSUE TITLE
How are potential dns exhaustion  worked out?

### ISSUE THREAD

**Issue by youradds** [stamparm/maltrail#11820]
Hi,

I'm trying to work out how the "potential dns exhaustion " records are created? I'm seeing quite a lot of false positives:
```

"2020-10-26 08:08:01.262974" spider.x.com 127.0.0.1 44211 127.0.0.53 53 UDP DNS (startissueuk).co.uk "potential dns exhaustion (suspicious)" (heuristic)

"2020-10-26 08:09:45.654688" spider/x.com 127.0.0.1 36147 127.0.0.53 53 UDP DNS (redwoodbank).co.uk "potential dns exhaustion (suspicious)" (heuristic)
```

I'm just wondering how this metric is worked out? 

Thanks

Andy

**Comment by stamparm** [comment]
Hi @youradds. There was a "bug" with clearing of the subdomain set, which most probably caused the problem like you experience. Anyhow, please update and retry.

p.s. threshold is: 1000 subdomains in less than 60 seconds, but as said, there was a problem with the "clearance"

**Comment by youradds** [comment]
Ah cool. So just restart to update? Or do a whole update of maltrail?

**Comment by stamparm** [comment]
Well, you should update the maltrail manually and then (re)start

**Comment by youradds** [comment]
Thanks. Looks like I was on v .39 as well, so have updated now.  Just running some tests to see if its sorted it so I can get back to you

Much appreciated

**Comment by youradds** [comment]
BTW you say:

`p.s. threshold is: 1000 different subdomains in less than 60 seconds, but as said, there was a problem with the "clearance"`

Is that for ALL traffic, or just the one request? The reason I ask - is that I've written a crawler to browse websites. It's currently going through a 70 mllion+ list of domains, and Maltrail is helping me get rid of the rubbish (dead sites, sinkholes, etc). I just wnat to make sure I'm not accidentally triggering this by running lots of concurrent processing at the same time? (its checking about 200-500 links a second)

TIA

Andy``

**Comment by stamparm** [comment]
For all traffic, but as said regarding the "subdomains" - as this kind of attack is for some specific targeted domain. Example of triggering would be if the following is "sent" in less than 60 seconds (notice the usage of same domain `example.com`):

```
nae2eusi.example.com
eeraes6k.example.com
ia3pooch.example.com
oajaef4t.example.com
...
<snip for 992 similar "random" alike subdomains for example.com>
...
joozaa9o.example.com
ohch1zee.example.com
kei2aepi.example.com
eey6ahso.example.com
```
