### ISSUE TITLE
Packets drop

### ISSUE THREAD

**Issue by sehot** [stamparm/maltrail#11880]
Hi
How can i check if there is packets drop?

**Comment by MikhailKasimov** [comment]
Hello!

```iptables -L -n -v``` in Linux and take a look on columns ```pkts bytes target``` in output.

**Comment by sehot** [comment]
Hi
it's empty 

` sudo iptables -L -n -v

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
`

**Comment by MikhailKasimov** [comment]
Hello!

Initially, Maltrail doesn't block packets itself -- it is detection, not prevention, system. And it works independently to iptables, so it doesn't send to iptables info on what to block\drop.

Please, also read MT's documentaion about ```FAIL2BAN_REGEX``` variable, how you can set MT to work in cooperation with iptables.

**Comment by sehot** [comment]
Hi
You didn't understand me , i will try to clarify my question  ,
my question is about performance , how can i make sure that maltrail can handle all received  traffic ? 
how can i make sure it  is not missing resource  (cpu \memory ) ?  

for example , if i have 1Gbps of traffic and only 1 core CPU and 4 gig ram , can maltrail handle all the traffic ?

**Comment by MikhailKasimov** [comment]
Hello!

Indeed, here is my misunderstanding, because I was focused on ```How can i check if there is packets drop?``` question and ```my question is about performance``` is a little bit another question. OK, thanks for clarification.

```if i have 1Gbps of traffic and only 1 core CPU and 4 gig ram , can maltrail handle all the traffic ?``` <-- should handle. Of course, if you switch onto ```CAPTURE_FILTER ip or ip6```, this will increase the load, but, anyway, should work normally.

So, ```how can i make sure it is not missing resource (cpu \memory ) ?``` <-- by own tests only with some measurement tools for CPU/RAM. Personally, I've never seen any external test results for MT...

**Comment by stamparm** [comment]
@sehot it goes like this. If used with default settings (particularly `CAPTURE_FILTER`) you won't have any problems processing that traffic, even on higher speeds. We are running it on some higher speed network(s) for years without any problems. As a matter of fact, that `CAPTURE_FILTER` setting is one of the most important to fine-tune the sensor on high-speed network pipes. Making it blank would most probably cause problems in >1Gbps traffic (e.g. lots of encrypted HTTPs PSH packets would be needlessly inspected - which is occupying majority of user/browser produced traffic)

Currently there is no way to check whether some packet got away, BUT, you can always make a dumb sanity check. For example, during the prime time, you can run Maltrail's sensor WHILE in the same time producing dummy malicious traffic (e.g. `ping 136.161.101.53` as mentioned in [README](https://github.com/stamparm/maltrail)) at some point in network which is being monitored by the Maltrail. Sensor should detect all those trivial attempts as `conficker`.

`if i have 1Gbps of traffic and only 1 core CPU and 4 gig ram , can maltrail handle all the traffic` <- answer is YES. That should be pretty ok-ish machine for 1Gbps traffic.

**Comment by MikhailKasimov** [comment]
Looks like all questions have got its answers.
