### ISSUE TITLE
Cool GUI - just trying to understand something

### ISSUE THREAD

**Issue by youradds** [stamparm/maltrail#12039]
Cool GUI! Very handy having it all visualised. I noticed these:

https://ibb.co/M10Wmqq

What are they, and should I be worried? I noticed the same one (first entry) on another server that I've got this on as well

Thanks

**Comment by stamparm** [comment]
based on quick google around for that domain:

A) Fortinet says that it is "malware" related [1]
B) SpamHaus has it listed for whatever reason [2]
C) Domain itself is ancient and "sinkholed", while in the same time it is periodically resolved from (I assume) one of your clients. This doesn't look "normal"
D) Domain has no linkbacks/referring domains and it has no reputation. That's usually a bad sign for periodic communication
E) There is a history of that same domain/IP being used by malware [3]
F) AFAICS, domain has been pointing to OVH (IP address 5.196.201.6) which is a place with dubious reputation

References:

[1] https://www.virustotal.com/gui/domain/control.commandeservices.bid/detection
[2] https://mxtoolbox.com/Problem/Blacklist/Spamhaus-DBL/?page=prob_blacklist&ip=control.commandeservices.bid&link=button&action=blacklist:control.commandeservices.bid&showLogin=1&hidetoc=1&reason=127.0.1.2
[3] https://infosec.cert-pa.it/analyze/20fde87b85e07fadbdd8cdb6d9ca6f2c.pdf

**Comment by youradds** [comment]
Hi,

Thanks for looking into this for me. Much appreciated. I noticed that these IPs that are marked as dangerous, are:

151.236.220.5 [GB]
176.58.107.5 [GB]
212.71.253.5 [GB]

They are all Linode IPs. So I stuck a ticket in to them - and they said:

```
I wouldn't worry about these IPs because they are our DNS resolvers in London – it's expected behaviour. I agree it is curious that they were marked risky. However, the traffic type is expected for a resolver, UDP port 53.

I hope this helps to explain. Feel free to let us know if you have any other questions. We're always here.
```

So it seems it shouldn't be an issue. Odd how they are marked as warnings though. Is there any way to whitelist them?

Thanks!

Andy
