### ISSUE TITLE
Regularly "killed"

### ISSUE THREAD

**Issue by gregfr** [stamparm/maltrail#121]
Greetings
I've installed sensor & server on the same system. Every few days, the sensor stops like this:

`[o] running...`
(a few days pass)
```
[i] updating trails (this might take a while)...
 [o] 'https://reputation.alienvault.com/reputation.generic'
 [o] 'http://cybercrime-tracker.net/ccam.php'
 [o] 'https://www.badips.com/get/list/any/2?age=7d'
 [o] 'http://osint.bambenekconsulting.com/feeds/c2-dommasterlist-high.txt'
 [o] 'http://osint.bambenekconsulting.com/feeds/c2-ipmasterlist-high.txt'
 [o] 'http://osint.bambenekconsulting.com/feeds/dga-feed.txt'
Killedogress: 5/63 (7%)
```
What am I doing wrong?
Thanks in advance

**Comment by stamparm** [comment]
That DGA feed is sometimes too large for a low memory system. I bet you
have a low memory (e.g. 256 MB) on that sensor machine, right?

**Comment by gregfr** [comment]
Thanks for you answer. It's a 512M VM, I'll try to monitor the RAM at the point where the sensor gets killed.

**Comment by stamparm** [comment]
With the latest revision FAR less memory is used on this feed. It is downloaded in gzip format (cca. 6MB) and read/decompressed/parsed line by line. Previously the whole uncompressed file has been parsed inside the memory (cca. 111MB).

**Comment by gregfr** [comment]
Thanks that is nice :)
