### ISSUE TITLE
Is Maltrail missing some stuff?

### ISSUE THREAD

**Issue by youradds** [stamparm/maltrail#12117]
```
2020-11-08 06:06:16 dovecot_login authenticator failed for ([185.234.216.63]) [185.234.216.63]: 535 Incorrect authentication data (set_id=wayne)
2020-11-08 06:09:45 dovecot_login authenticator failed for () [193.169.252.205]: 535 Incorrect authentication data (set_id=medellin)
2020-11-08 06:12:17 dovecot_login authenticator failed for ([185.234.219.13]) [185.234.219.13]: 535 Incorrect authentication data (set_id=cristina)
```

All of those are coming up as spammers (and I can see from what they are trying to login as =))

https://www.abuseipdb.com/check/185.234.219.13
https://www.abuseipdb.com/check/185.234.216.63
https://www.abuseipdb.com/check/193.169.252.205

Yet it isn't being added to maltrails IP list:
```

root@ca1:/var/log/exim4# curl http://ca1.x.com:8338/fail2ban | grep "185.234.219.13"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1410  100  1410    0     0   5875      0 --:--:-- --:--:-- --:--:--  5875
root@ca1:/var/log/exim4# curl http://ca1.x.com:8338/fail2ban | grep "185.234.216.63"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1410  100  1410    0     0   275k      0 --:--:-- --:--:-- --:--:--  275k
root@ca1:/var/log/exim4# curl http://ca1.x.com:8338/fail2ban | grep "193.169.252.205"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1410  100  1410    0     0   275k      0 --:--:-- --:--:-- --:--:--  275k
```

Am I missing something? Attached is my maltrail.conf (with my IP taken out :))

[maltrail.txt](https://github.com/stamparm/maltrail/files/5505913/maltrail.txt)

**Comment by youradds** [comment]
Also I noticed this in the config:

```
# Remote address for pulling (latest) trail definitions (e.g. http://192.168.2.107:8338/trails). USE_SERVER_UPDATE_TRAILS directive should be active in [Server] parameters.
#UPDATE_SERVER http://192.168.2.107:8338/trails
```

I tested it using my URL:

curl http://ca1.x.com:8338/trails

It spits out a load of stuff (not including the IP in question though). Is this simply outputting the results, or does it do an update? (i.e should I put it on a cron?)

**Comment by youradds** [comment]
@MikhailKasimov  awesome thank you. Its so nice to find a project thats so actively updated and responsive!  You get so many where they go stale, and suggestions / bug fixes etc go unattended even when someone does the work and forks them

Much appreciated

**Comment by youradds** [comment]
@MikhailKasimov  just checking - is that fix correct?

`FAIL2BAN_REGEX attacker|reputation|potential[^"]*(web scan|directory traversal|injection|remote code)|spammer`

I've restarted sensor.py and server.py, and I still see this in the rejectlog for exim:

`2020-11-08 12:43:03 dovecot_login authenticator failed for (172.105.106.51) [193.169.252.205]: 535 Incorrect authentication data (set_id=nessus)`

but I don't see anything in 2020-11-08.log for Maltrail about it?

Should it maybe be:

FAIL2BAN_REGEX attacker|reputation|potential[^"]*(web scan|directory traversal|injection|remote code|spammer)

(i.e inside the parenthesis)

**Comment by MikhailKasimov** [comment]
As I can see there's no ```potential spammer```... Does ```FAIL2BAN_REGEX attacker|reputation|potential[^"]*(web scan|directory traversal|injection|remote code|spammer)``` works on your side correctly?

**Comment by youradds** [comment]
Hi,

I didn't try my suggestion (was just checking). Surely this one should have been put as a "known attacker", as they were probing our email accounts with a brute force:

`2020-11-08 12:43:03 dovecot_login authenticator failed for (172.105.106.51) [193.169.252.205]: 535 Incorrect authentication data (set_id=nessus)`

I'm just confused as to why it wasn't coming up (as they are on abuseipdb, so I assume the API side of maltrail would see it there?)

**Comment by youradds** [comment]
Maybe I'm missing something here btw?

[i] loading trails...
[i] 1,136,698 trails loaded
[?] in case of any problems with packet capture on virtual interface 'any', plea                           se put all monitoring interfaces to promiscuous mode manually (e.g. 'sudo ifconf                           ig eth0 promisc')
[i] opening interface 'any'
[i] setting capture filter 'udp or icmp or (tcp and (tcp[tcpflags] == tcp-syn or                            port 80 or port 1080 or port 3128 or port 8000 or port 8080 or port 8118))'
[i] preparing capture buffer...

**Comment by youradds** [comment]
Here are some more example ones I've seen coming in just now on rejectmail for exim4:

```
2020-11-08 13:07:47 dovecot_login authenticator failed for (172.105.106.51) [193.169.252.205]: 535 Incorrect authentication data (set_id=none)
2020-11-08 13:09:30 dovecot_login authenticator failed for ([185.234.219.14]) [185.234.219.14]: 535 Incorrect authentication data (set_id=kiosk)
2020-11-08 13:10:05 dovecot_login authenticator failed for (localhost) [45.142.120.90]: 535 Incorrect authentication data (set_id=paperbag2@pagething.com)
2020-11-08 13:10:12 dovecot_login authenticator failed for (localhost) [45.142.120.121]: 535 Incorrect authentication data (set_id=pmg@pagething.com)
```

2 of them correctly are flagged:

"2020-11-08 13:10:02.755552" ca1.pagething.com 45.142.120.90 31168 172.105.106.51 25 TCP IP 45.142.120.90 "known attacker" "blocklist.de (+dshield.org,greensnow.co,rutgers.edu)"
"2020-11-08 13:10:05.567480" ca1.pagething.com 45.142.120.121 14306 172.105.106.51 25 TCP IP 45.142.120.121 "known attacker" "blocklist.de (+dshield.org,greensnow.co,rutgers.edu)"

but the other 2 are missed, despite being on abuseipdb:

https://www.abuseipdb.com/check/193.169.252.205
https://www.abuseipdb.com/check/185.234.219.14

Cheers

Andy

**Comment by stamparm** [comment]
@youradds please take a look into `IP_MINIMUM_FEEDS` (https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L64-L65). That could be the option which is "causing" you trouble. Try to lower it down to `1` and restart the sensor.

It goes like this. In regular installation, when that setting is set to `1`, you can expect loads of "noise" from the outside. That's the reason why that setting is by default set to `3`

**Comment by stamparm** [comment]
@youradds As of `UPDATE_SERVER`, you should not touch it in your case. That option should point (if required) to the outside source of the trails, WHERE in your case you really don't want to point to yourself.

As of accessing that address locally, it just spits out the trails currently being used by the Maltrail. There is no action following it (e.g. update or similar).

As of some IPs not appearing in that output, which you would expect, take a look into `IP_MINIMUM_FEEDS` as pointed in previous message

**Comment by youradds** [comment]
Ah ok. What do you mean by "noise" from the outside? Surely if someone is probing your server from a recognised spammer , you want to just block them right off? :)

Regarding UPDATE_SERVER - thanks for the update. I did wonder about it, but just wanted to make sure I wasn't missing anything

**Comment by stamparm** [comment]
`you can expect loads of "noise" from the outside` <- @youradds I meant that there will be lots of "spammy" events inside your Maltrail logs from any IP address that looked "suspicious" to anybody recently. Writing this based on experience. Increasing the `IP_MINIMUM_FEEDS` strengthens the conclusion that something is indeed malicious/suspicious the same way that regular voting is done
