### ISSUE TITLE
Another "parked" IP

### ISSUE THREAD

**Issue by youradds** [stamparm/maltrail#12585]
46.23.69.44 - for https://www.uk2.net/ 

Example:

http://seasidecottage.wales/

AFAI can see, all the domains on that IP are parked. I've cleaned them out of my system, but it's probably worth updating the list (I still can't work out how to do "pull" requests I'm afraid )

**Comment by stamparm** [comment]
thx :+1:

**Comment by youradds** [comment]
Ah hmmm looks like they also use that IP for live sites!

http://lexis-telecom.co.uk/

So maybe can't be used as a guaranteed parking server :(

**Comment by stamparm** [comment]
@youradds np. reverted
