### ISSUE TITLE
port 80 or other ports / tcp marked as DNS in type

### ISSUE THREAD

**Issue by marirs** [stamparm/maltrail#126]
"usec" : 840991, "reference" : "(static)", "sensor" : "sense", "dest_hostname" : "", "protocol" : "TCP", "alert" : "domain (suspicious)", "src_ip" : "10.136.197.32", "sec" : 1489462109, "threat" : "(badbadmac).club", "src_port" : 52955, "dest_port" : 80, "type" : "DNS", "dest_ip" : "34.198.152.6" }

Not sure; if its just me or anyone else getting this. I'm seeing a lot of non DNS trails getting marked as DNS...
am I doing something different here?

**Comment by stamparm** [comment]
Type of trail is DNS (domain name), while it has been detected inside the HTTP traffic (Host: header).

I suspect that you've turned on the `CHECK_HOST_DOMAINS` inside the `maltrail.conf`. Description says it all: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L87

**Comment by marirs** [comment]
You are right - that was set to true...
thank you :)
