### ISSUE TITLE
defunct process

### ISSUE THREAD

**Issue by marirs** [stamparm/maltrail#127]
Any reason why the process becomes defunct?

ps -efl | grep -i python
4 S root     29729     1 10  49   - - 979856 poll_s Mar15 ?       10:52:04 python ./sensor.py
5 Z root     29759 29729  9  80   0 -     0 exit   Mar15 ?        09:43:18 [python] <defunct>
5 Z root     29760 29729  9  80   0 -     0 exit   Mar15 ?        09:43:22 [python] <defunct>
5 S root     29762 29729 10  80   0 - 1453203 poll_s Mar15 ?      10:39:41 python ./sensor.py

16gb ram with 4 cores. how do i figure out what went wrong?

thanks

**Comment by stamparm** [comment]
If you are running it as a `python ./sensor.py` from within the terminal, then all of a sudden you disconnect from the terminal, sensor will most probably die. Hence, please try to run it from multiplexer (e.g. `screen` or `tmux`). Also, you could run it as a batch script from within the root's cron (e.g. `0 23 * * * /usr/bin/pgrep -f sensor.py || /usr/local/bin/maltrail_sensor.sh`).

There is also a `/var/log/maltrail/error.log` where you can take a look at Maltrail (critical) error messages
