### ISSUE TITLE
sinkhole_prolexic.txt ?

### ISSUE THREAD

**Issue by zoni171** [stamparm/maltrail#128]
looks to be a prolexic sinkhole? if confirmed may need to create a "sinkhole_prolexic.txt" under maltrail/trails/static/malware/

https://www.virustotal.com/en/ip-address/72.52.4.120/information/

72.52.4.120

**Comment by stamparm** [comment]
Parking page (owner sedo.com). 

![example](https://cloud.githubusercontent.com/assets/921555/24172871/292ca02e-0e8a-11e7-9e59-997df4b6caaf.png)
