### ISSUE TITLE
Getting started with a test pcap

### ISSUE THREAD

**Issue by rickhg12hs** [stamparm/maltrail#12809]
N.B.: I'm a `maltrail` noob. :student: 

I want to try `maltrail` on a sample pcap file, for example this [Malware-Traffic-Analysis.Net exrcise pcap](https://www.malware-traffic-analysis.net/2019/12/25/2019-12-25-traffic-analysis-exercise.pcap.zip). [ The ZIP file password may be found at https://www.malware-traffic-analysis.net/about.html ]

When I run `sensor.py` with the `--console` option, I get some `(suspicious)` notifications:

```
"2020-12-05 19:32:53.865313" homelinux.org 139.199.184.166 59314 10.12.25.101 80 TCP URL (128.199.64.235)/shell.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.866606" homelinux.org 139.199.184.166 61288 10.12.25.101 80 TCP URL (128.199.64.235)/shell.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.866377" homelinux.org 139.199.184.166 61288 10.12.25.101 80 TCP URL (128.199.64.235)/cmd.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.881964" homelinux.org 139.199.184.166 54899 10.12.25.101 80 TCP URL (128.199.64.235)/cmd.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.869737" homelinux.org 139.199.184.166 56366 10.12.25.101 80 TCP URL (128.199.64.235/images/stories)/cmd.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.866562" homelinux.org 139.199.184.166 61288 10.12.25.101 80 TCP URL (128.199.64.235)/cmd.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.878811" homelinux.org 139.199.184.166 61333 10.12.25.101 80 TCP URL (128.199.64.235)/shell.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.877280" homelinux.org 139.199.184.166 57683 10.12.25.101 80 TCP URL (128.199.64.235)/mm.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.877481" homelinux.org 139.199.184.166 57683 10.12.25.101 80 TCP URL (128.199.64.235)/shell.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.881920" homelinux.org 139.199.184.166 54899 10.12.25.101 80 TCP URL (128.199.64.235)/cmd.php "web shells (suspicious)" (static)
"2020-12-05 19:32:53.891775" homelinux.org 139.199.184.166 56638 10.12.25.101 80 TCP URL (128.199.64.235)/mysql.php "web shells (suspicious)" (static)
```
... but nothing shows up on the webpage at `localhost:8338`.  I successfully logged in and the webpage displays but it only shows `No matching threats found`.

I've not modified `maltrail.conf` after install from this repo and no error messages appear anywhere.

I'm thinking this is just a configuration issue, but I'm not sure where to start.

What's the best way to "roadtest" `maltrail` with some pcap files?

**Comment by stamparm** [comment]
I'll try to explain what's going on with the following screenshots:

![1](https://user-images.githubusercontent.com/921555/101492138-dd76df00-3964-11eb-9852-19d82ead7548.png)

---

![2](https://user-images.githubusercontent.com/921555/101492129-d9e35800-3964-11eb-8e41-b2d48a324c3e.png)

---

![3](https://user-images.githubusercontent.com/921555/101492144-dfd93900-3964-11eb-9325-cdbd9a8f36f8.png)

---

![4](https://user-images.githubusercontent.com/921555/101492251-01d2bb80-3965-11eb-83c1-e649721c6ed2.png)

**Comment by stamparm** [comment]
`What's the best way to "roadtest" maltrail with some pcap files?` <- `--consoles` which you've already used

**Comment by rickhg12hs** [comment]
Thanks!
