### ISSUE TITLE
Multiple errors in ./html/js/main.js

### ISSUE THREAD

**Issue by Antoniano** [stamparm/maltrail#129]
Hi.

After dumping more 60000 of events maltrail server started showing the next error in a popup while opening server web-page:
"TypeError: Cannot read property 'split' of undefined"

Then if you go to events and click on High on a pie-chart it show the next popup:
"Uncaught TypeError: Cannot read property 'split' of undefined Script: http://X.X.X.X:8338/js/main.js Line: 1275"

When you try to go to sources tab it shows the next popup:
"Uncaught TypeError: Cannot read property 'DNS' of undefined Script: http://X.X.X.X:8338/js/main.js Line: 2204"

Anyway it doesn't show any results.
Also I should notice that I can see results for other days. It seems that there is a record in a log file that couldn't be processed by server.

I'm sorry, but I can't send you a log file. I can try to identify which record causes this error if you provide me detailted steps on how to do it. 

Thank you in advance for help.

**Comment by Antoniano** [comment]
I found an inproper string in a log file:
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@


But I even can't imagine how it came into my log.

**Comment by Antoniano** [comment]
I have deleted this line from a file and now everything works correctly. I think this issue can be closed but I leave it up to you.

**Comment by stamparm** [comment]
Dear Lord :). I'll try to reproduce it

**Comment by stamparm** [comment]
Added couple of "sanity" checks. Thank you for your report and debugging effort
