### ISSUE TITLE
CEF syslog: match against severity

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#13251]
Hi,

I'm currently playing around with syslog and SIEM.
I already wrote a decoder and rule against CEF logs which looks like this (in JSON):

```
{
  "cluster": {
    "node": "node02",
    "name": "wazuh"
  },
  "agent": {
    "name": "siem-worker1",
    "id": "000"
  },
  "data": {
    "date": "2020-12-23",
    "srcip": "172.24.68.133",
    "code": "0",
    "dstport": "-",
    "type": "sensor",
    "version": "0.26.1",
    "trail": "136.161.101.53",
    "ref": "(static)",
    "application": "Maltrail",
    "srcport": "-",
    "code_2": "0",
    "dstip": "136.161.101.53",
    "category": "sinkhole conficker (malware)"
  },
  "rule": {
    "firedtimes": 1,
    "mail": false,
    "level": 3,
    "description": "Malicious Maltrail event triggered",
    "groups": [
      "Maltrail"
    ],
    "id": "64521"
  },
  "full_log": "Dec 23 22:38:31 OPNsense.localdomain CEF:0|Maltrail|sensor|0.26.1|2020-12-23|sinkhole conficker (malware)|0|src=172.24.68.133 spt=- dst=136.161.101.53 dpt=- trail=136.161.101.53 ref=(static)",
  "id": "1608759511.9145237",
  "timestamp": "2020-12-23T22:38:31.769+0100",
  "predecoder": {
    "hostname": "OPNsense.localdomain",
    "program_name": "CEF",
    "timestamp": "Dec 23 22:38:31"
  },
  "manager": {
    "name": "siem-worker1"
  },
  "decoder": {
    "name": "CEF"
  },
  "input": {
    "type": "log"
  },
  "@timestamp": "2020-12-23T21:38:31.769Z",
  "location": "10.24.80.101",
  "_id": "OPyKkXYBYhUsOsEqFo1-"
}
```

In general this is perfectly fine, but I'd like to know if there's a chance to add the severity in logs? I see there are two times "code 0" in syslog (full_log). What are these values for? With the above there would be just a record in SIEM and that's it. But sometimes you want to trigger an email alert so maybe it would be good to have critical severity logged by a field so I can build a rule which would fire an event.

Any idea? :)

**Comment by mimugmail** [comment]
Here are a couple of hits to maybe make it clearer, compared to excellent maltail server UI we have no search criteria in Elastic/Syslog/...

```
** Alert 1608791767.98105: - Maltrail,
2020 Dec 24 07:36:07 OPNsense.localdomain->10.24.80.101
Rule: 64521 (level 3) -> 'Malicious Maltrail event triggered'
Src IP: 172.24.68.133
Src Port: 56962
Dst IP: 8.8.8.8
Dst Port: 53
Dec 24 07:36:07 OPNsense.localdomain CEF:0|Maltrail|sensor|0.26.1|2020-12-23|domain (suspicious)|0|src=172.24.68.133 spt=56962 dst=8.8.8.8 dpt=53 trail=(test).sx ref=(static)
code: 0
application: Maltrail
type: sensor
version: 0.26.1
date: 2020-12-23
category: domain (suspicious)
code_2: 0
trail: (test).sx
ref: (static)
```

```
** Alert 1608791534.97526: - Maltrail,
2020 Dec 24 07:32:14 OPNsense.localdomain->10.24.80.101
Rule: 64521 (level 3) -> 'Malicious Maltrail event triggered'
Src IP: 172.24.68.133
Src Port: -
Dst IP: 136.161.101.53
Dst Port: -
Dec 24 07:32:14 OPNsense.localdomain CEF:0|Maltrail|sensor|0.26.1|2020-12-23|sinkhole conficker (malware)|0|src=172.24.68.133 spt=- dst=136.161.101.53 dpt=- trail=136.161.101.53 ref=(static)
code: 0
application: Maltrail
type: sensor
version: 0.26.1
date: 2020-12-23
category: sinkhole conficker (malware)
code_2: 0
trail: 136.161.101.53
ref: (static)
```

```
** Alert 1608790964.96290: - Maltrail,
2020 Dec 24 07:22:44 OPNsense.localdomain->10.24.80.101
Rule: 64521 (level 3) -> 'Malicious Maltrail event triggered'
Src IP: 172.24.68.133
Src Port: 21231
Dst IP: 151.115.41.123
Dst Port: 53
Dec 24 07:22:44 OPNsense.localdomain CEF:0|Maltrail|sensor|0.26.1|2020-12-23|long domain (suspicious)|0|src=172.24.68.133 spt=21231 dst=151.115.41.123 dpt=53 trail=(nwdpz2mfrvm4bepbzfpmn71te8zhhk.uribl).rspamd.com ref=(heuristic)
code: 0
application: Maltrail
type: sensor
version: 0.26.1
date: 2020-12-23
category: long domain (suspicious)
code_2: 0
trail: (nwdpz2mfrvm4bepbzfpmn71te8zhhk.uribl).rspamd.com
ref: (heuristic)
```

So I have one rule which hits level 3, a mail alert e.g. would be fired at level 12.

**Comment by stamparm** [comment]
Hi.

I am now in BIG dilemma. It goes like this. Maltrail is explicitly created with **fat** `client` (UI/presentation) component. That means that lots of stuff is offloaded to the clients in the time of need, in contrast to constantly using server's resources.

One of those "offloads" is also the severity calculation. While it doesn't necessary mean hefty usage of CPU resources, skipping it in sensor logs means less usage of storage (resources). Also, `severity` is a highly subjective calculation. For example, in my case I "jump" on `malware`, while somebody else would "jump" on `web attack`. Thus, "skipping" the Maltrail UI with `LOGSTASH_SERVER` or `SYSLOG_SERVER` user should in ideal case calculate severity on his own priority checklist.

Most probably you can now sense the dilemma here. I am not sure what to do for making everybody happy, while not breaking the current workflow/idea - where severity is currently calculated inside the Maltrail UI (i.e. https://github.com/stamparm/maltrail/blob/master/html/js/main.js#L72 and https://github.com/stamparm/maltrail/blob/master/html/js/main.js#L817-L835)

**Comment by stamparm** [comment]
p.s. maybe a separate configuration entry (e.g.) `REMOTE_SEVERITY` which would declare the severity calculation (e.g. via regexes or smth) for those events being sent via `SYSLOG_SERVER` or `LOGSTASH_SERVER`

**Comment by mimugmail** [comment]
No worries .. I though the code number are kind of serverities. We don't need to move the calculation to the application itself.
Is there a quick list of categories like `sinkhole conficker (malware)` or `long domain (suspicious)`? 
I could add a rule for every category and let the end user decide to which one he wants an alert.

**Comment by stamparm** [comment]
I already started making a configuration setting like:

`REMOTE_SEVERITY_REGEX (?P<high>(remote )?custom\)|malwaredomainlist|malware(?! (distribution|site))|adversary|ransomware)|(?P<medium>potential malware site|malware distribution)|(?P<low>mass scanner|reputation|attacker|spammer|compromised|crawler|scanning)`

That could resolve your problem and problems of alike

**Comment by stamparm** [comment]
@mimugmail done

A) example for `SYSLOG_SERVER` (Note: `LogSeverity` values here are 0 (for low), 1 (for medium) and 2 (for high))

`Dec 24 15:05:55 beast CEF:0|Maltrail|sensor|0.27.68|2020-12-24|andromeda (malware)|2|src=192.168.5.137 spt=60453 dst=8.8.8.8 dpt=53 trail=morphed.ru ref=(static)`

B) example for `LOGSTASH_SERVER`

`{"timestamp": 1608818692, "sensor": "beast", "severity": "high", "src_ip": "192.168.5.137", "src_port": 48949, "dst_ip": "8.8.8.8", "dst_port": 53, "proto": "UDP", "type": "DNS", "trail": "morphed.ru", "info": "andromeda (malware)", "reference": "(static)"}`

p.s. I would strongly suggest usage of `LOGSTASH_SERVER` because it is far easier to parse (i.e. JSON) and attribute names should be the same as those from UI

**Comment by mimugmail** [comment]
Beautiful work Miro! 

I'll add it to the official Wazuh ruleset. BTW Wazuh doesn't include logstash anymore as it's too resource hungry. The already have a strong parsing via filebeat and own engine. 

```
** Alert 1608899641.11816: - Maltrail,connection_attempt,connection_attempt,
2020 Dec 25 13:34:01 OPNsense.localdomain->10.24.80.101
Rule: 64522 (level 7) -> '**Medium** critical Maltrail event triggered'
Src IP: 172.24.68.133
Src Port: 52753
Dst IP: 8.8.8.8
Dst Port: 53
Dec 25 14:35:26 OPNsense.localdomain CEF:0|Maltrail|sensor|0.27.71|2020-12-25|long domain (suspicious)|1|src=172.24.68.133 spt=52753 dst=8.8.8.8 dpt=53 trail=(sdbsxsrbdbtxsdbsxdxdsffsxds).test.de ref=(heuristic)
code: 0
application: Maltrail
type: sensor
version: 0.27.71
date: 2020-12-25
category: long domain (suspicious)
severity: **1**
trail: (sdbsxsrbdbtxsdbsxdxdsffsxds).test.de
ref: (heuristic)
```


```
** Alert 1608899654.12483: - Maltrail,connection_attempt,connection_attempt,
2020 Dec 25 13:34:14 OPNsense.localdomain->10.24.80.101
Rule: 64523 (level 10) -> '**High critical** Maltrail event triggered'
Src IP: 172.24.68.133
Src Port: -
Dst IP: 136.161.101.53
Dst Port: -
Dec 25 14:35:38 OPNsense.localdomain CEF:0|Maltrail|sensor|0.27.71|2020-12-25|sinkhole conficker (malware)|2|src=172.24.68.133 spt=- dst=136.161.101.53 dpt=- trail=136.161.101.53 ref=(static)
code: 0
application: Maltrail
type: sensor
version: 0.27.71
date: 2020-12-25
category: sinkhole conficker (malware)
severity: **2**
trail: 136.161.101.53
ref: (static)
```
