### ISSUE TITLE
HTTP(s) support?

### ISSUE THREAD

**Issue by laci420** [stamparm/maltrail#136]
Hi!

Most people here run secure HTTP servers with encryption. As far as I can see maltrail does not support HTTP(s) sniffing. Maybe it would be possible to use an ssl certificate with maltrail to support that?

Would be quite cool!

Thanks,
Laci

**Comment by szepeviktor** [comment]
Maybe an SSH tunnel is more secure than an open https port.

**Comment by stamparm** [comment]
@laci420 Maltrail is a low-level packet inspector. This basically means that something like HTTP(s) interception would be an overkill (it requires work on upper layer of transport protocol). Sorry, but this is not going to be implemented
