### ISSUE TITLE
[Update Request] Wordbot.xyz as a safe site

### ISSUE THREAD

**Issue by Zamion101** [stamparm/maltrail#13674]
Hello I'm the owner and developer of wordbot.xyz under the [FluxTeam](https://github.com/fluxteam). I found our domain "wordbot.xyz" tagged as malware site under [trails/static/malware/android_cerberus.tx](https://github.com/stamparm/maltrail/blob/master/trails/static/malware/android_cerberus.txt#L5150). We have recently bought this domain and if there is a any problem with our website we will be very happy to get further information about this situation. Also is it possible we want to remove our domain from your list. You can contact me from here or with email `support@wordbot.xyz`.

**Comment by stamparm** [comment]
Done. Sorry for inconvenience

**Comment by MikhailKasimov** [comment]
+ https://github.com/stamparm/maltrail/pull/13678/commits/c162f158fa34862afb49b1c57a8eefa719fdce9f

**Comment by Zamion101** [comment]
Thank you for your quick response and also for whitelisting.

**Comment by Zamion101** [comment]
This domain is no longer maintained by FluxTeam. Please be aware of possible scams/viruses within this domain.

**Comment by MikhailKasimov** [comment]
Thank you for info! Fix for white-list: https://github.com/stamparm/maltrail/commit/badd7792ed6c1388df43661943361b1aeaef8524
