### ISSUE TITLE
Running but not logging anything

### ISSUE THREAD

**Issue by scriptzteam** [stamparm/maltrail#14]
root@xyz:/var/log/maltrail# ping -c 1 136.161.101.53
PING 136.161.101.53 (136.161.101.53) 56(84) bytes of data.
64 bytes from 136.161.101.53: icmp_seq=1 ttl=54 time=81.6 ms

--- 136.161.101.53 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 81.669/81.669/81.669/0.000 ms

root@xyz:/var/log/maltrail# cat /var/log/maltrail/$(date +"%Y-%m-%d").log
cat: /var/log/maltrail/2015-12-16.log: No such file or directory

**Comment by stamparm** [comment]
please check if the interface being monitored is being put to PROMISC. in some cases (if interface is passive for example), when sniffing on `any`, user should put that same interface to PROMISC manually (there is also a warning message from sensor about this)

for started, can you please send results of:
1) `ip route get 136.161.101.53`
2) `ifconfig -a`
3) `cat ~/.maltrail/trails.csv | grep 136.161.101.53`

**Comment by scriptzteam** [comment]
It seems that those two commands needs to be running in order to work :)

python server.py
and 
python sensor.py

i am running them in screen so now works :)

you should add it into docs, in docs is that only server.py is need to be run.

anyway greaaaaat job!
