### ISSUE TITLE
problem with installing on freebsd

### ISSUE THREAD

**Issue by rout3rx** [stamparm/maltrail#141]
Hi
i have a problem with running sensor 
`[i] using configuration file '/root/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[?] at least 384MB of free memory required
[i] loading trails...
[i] 1,196,914 trails loaded
[x] virtual interface 'any' missing. Replacing it with all interface names
[i] opening interface 'vmx0'
[i] opening interface 'vmx1'
[i] opening interface 'lo0'
[i] opening interface 'enc0'
[i] opening interface 'pflog0'
[i] opening interface 'pfsync0'
[i] setting capture filter 'udp or icmp or (tcp and (tcp[tcpflags] == tcp-syn or port 80 or port 1080 or port 3128 or port 8000 or port 8080 or port 8118))'
[!] unhandled exception occurred ('PFSYNC link-layer type filtering not implemented')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "sensor.py", line 984, in <module>
    main()
  File "sensor.py", line 975, in main
    init()
  File "sensor.py", line 788, in init
    _cap.setfilter(config.CAPTURE_FILTER)
PcapError: PFSYNC link-layer type filtering not implemented
'
---
[i] finished
`

**Comment by rout3rx** [comment]
why closed?

**Comment by stamparm** [comment]
Pushed patch. Just update
