### ISSUE TITLE
No login prompt?

### ISSUE THREAD

**Issue by mgaulton** [stamparm/maltrail#14322]
Hey there, 
Returning user, did a clean install but after a clean start of sensor and server, the web interface only loads to a point, no login prompt is shown.
Suggestions would be appreciated.

Opensuse Tumbleweed, python 3.8, requirements met, fresh git clone

**Comment by mgaulton** [comment]
Chrome incognito browser didn't change anything
When I tried it in Firefox, i got a dialog with ReferenceError: $ is not defined Script: http://192.168.2.5:8338/js/main.js Line: 85

**Comment by MikhailKasimov** [comment]
Hello!

Are there any error messages in console, when server and\or sensor are getting started?

**Comment by mgaulton** [comment]
Negative, the error.log is 0 bytes even.

##server
Maltrail (server) #v0.29.9 {https://maltrail.github.io}

[*] starting @ 16:26:11 /2021-02-04/

[i] using configuration file '/opt/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[i] running UDP server at '0.0.0.0:8337'
[i] starting HTTP server at http://192.168.2.5:8338/
[^] running...

##sensor
Maltrail (sensor) #v0.29.9 {https://maltrail.github.io}

[*] starting @ 16:25:57 /2021-02-04/

[i] using configuration file '/opt/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[i] using '/root/.maltrail/trails.csv' for trail storage (last
modification: 'Thu, 04 Feb 2021 20:57:51 GMT')
[i] loading trails...
[i] 1,324,188 trails loaded
[?] in case of any problems with packet capture on virtual interface 'any',
please put all monitoring interfaces to promiscuous mode manually (e.g.
'sudo ifconfig eth0 promisc')
[i] opening interface 'any'
[i] setting capture filter 'udp or icmp or (tcp and (tcp[tcpflags] ==
tcp-syn or port 80 or port 1080 or port 3128 or port 8000 or port 8080 or
port 8118))'
[i] preparing capture buffer...
[i] created 1 more processes (out of total 2)
[^] running...

**Comment by stamparm** [comment]
it seems like the thirdparty.min.js hasn't been loaded properly and/or before the main.js.

now, i've pushed some dirty patch to the repo. please pull, restart the server and retry it again

**Comment by stamparm** [comment]
p.s. do you have some script blocker addons or similar?
p.p.s. if everything fails, please go to https://maltraildemo.github.io/ and write down whether you experience same problems there

**Comment by stamparm** [comment]
@mgaulton any update?

**Comment by mgaulton** [comment]
sorry, work distracted me.
pulling and trying now.

**Comment by mgaulton** [comment]
uBlockOrigin on chrome, no blocker in incognito, no blocker in Firefox or Edge

**Comment by mgaulton** [comment]
No change 
Chrome Incognito, Chrome with ubLock, FF with no block, Edge with no block, blank main body no login
I did discover that uBlock was on FF initially, I removed it and the "Line 85" message disappeared, becoming like the others, no main body no login prompt.

**Comment by mgaulton** [comment]
Demo page loads to events with no login prompt, but I do get a main body there.

**Comment by mgaulton** [comment]
thirdparty.min.css:1 Failed to load resource: net::ERR_CONNECTION_RESET
thirdparty.min.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
I caught this in the java console, where is it loaded from?

**Comment by mgaulton** [comment]
8338 is wide open on my server

**Comment by mgaulton** [comment]
And this 
Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700&amp;subset=cyrillic' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

http://192.168.2.5:8338/
Refused to load the font 'data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAGSwABMAAAAAtfwAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABqAAAABwAAAAcZSXU3EdERUYAAAHEAAAAlQAAAOYXGhVYR1BPUwAAAlwAAAdrAAAQ5noXPxxHU1VCAAAJyAAAATQAAAKy3SOq409TLzIAAAr8AAAAUwAAAGCgNqyhY21hcAAAC1AAAAGPAAAB6gODigBjdnQgAAAM4AAAAEIAAABCEToKw2ZwZ20AAA0kAAABsQAAAmVTtC+nZ2FzcAAADtgAAAAIAAAACAAAABBnbHlmAAAO4AAATFsAAIy8VrEAaGhlYWQAAFs8AAAAMwAAADYN24w7aGhlYQAAW3AAAAAgAAAAJA8tBb1obXR4AABbkAAAAnoAAAOqnWlWT2xvY2EAAF4MAAAByQAAAdgbwD2ObWF4cAAAX9gAAAAgAAAAIAIIAaduYW1...wpkippki4ZkilZnOcCl7nCHS5yibts4aRkc5NbkiO57JQ8yZcCKZQiq7e+pcmn24INfk3TKpRGWLemVLlH5R6H0qUsa9MIDSp1paF0KJ1Kl7JYWaIsVf7b5w6rq726bq/1e4OBmuqqZl84MsywLtNSGQw0tjcus7xN0xO+I6ShdCidfwEvVqEbAAB42kXOvW7CMBDAcZ8dQghQvvIBSEhh6WKpEjNrw8JSdYqlziy0K2u7dCzPculUwcvwFKxwlyb25t/f55P/4PaN8CO2GLwUJcDRlBtfF0scmi1Gr3T4Mgv09VshUGU5Kv2MQZafhFJXIXXlNjsAa5/dho/GrSz/9c81PELL1OhUm7xVMxmyO3LRuMsO4b1xj90Fe9+nZb19jQdCf/4PwEH92YifDDxBT0q1OVCZcInkkytjLhPYuTLiMgbpypC2j46WcbX28+YGEi6xt3Ql5ZLAwZUpLUkvljPi9NFyzvMzubbzBiN9B2+6bK8AAAABV9JwXgAA' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by stamparm** [comment]
Something is seriously wrong in your setup:

1) There is not a single mention of https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700&amp;subset=cyrillic inside Maltrail's source code
2) This `thirdparty.min.css:1 Failed to load resource: net::ERR_CONNECTION_RESET` means that server component is not running. Nothing is wrong with Maltrail here. Please follow the instructions at the [README.md](https://github.com/stamparm/maltrail/blob/master/README.md) to properly setup and run Maltrail
3) `Demo page loads to events with no login prompt, but I do get a main body there.` - demo page doesn't have login prompt
4) `Refused to load the font` should not prevent you from entering the Maltrail's panel

**Comment by mgaulton** [comment]
OK, I think looking at it, the google reference is a plugin in the browser caused that.
I'll try again, on the config.

**Comment by mgaulton** [comment]
weirdly, using the docker for the web ui works.

**Comment by MikhailKasimov** [comment]
@mgaulton Hello! Any news on case?

**Comment by mgaulton** [comment]
I think you're right, this is an issue on my end.
We can close this and I'll fight with it.
Thanks for your time.;
