### ISSUE TITLE
[Question] Way to detect this by MT?

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#1467]
Hello!

Subj

https://twitter.com/JayTHL/status/1118595885208866819
https://twitter.com/JayTHL/status/1118650213084872705

Need an advice on how to detect all of this by MT in most correct way? Thanks!

**Comment by stamparm** [comment]
Currently no "generic" way how to do it

**Comment by MikhailKasimov** [comment]
Can we have support for ```helplog[0-9]{3,4}\.(ml|ga|gq|tk|cf)``` here? \Very needed here\

**Comment by MikhailKasimov** [comment]
Another example https://twitter.com/JayTHL/status/1121872865106833409 : ```service-confirm-v[0-9]+\.(ml|tk|cf|ga|gq)```

**Comment by MikhailKasimov** [comment]
Fix is in https://github.com/stamparm/maltrail/pull/2655/commits/19e253a30d4dd535e7ea6c3a597de520834b5801

Will close current report after merging.

**Comment by MikhailKasimov** [comment]
Waiting for more intelligent way how to detect all of this stuff: https://github.com/stamparm/maltrail/pull/2655#issuecomment-509004419

**Comment by stamparm** [comment]
With the latest revision, stuff like `service-confirm-v[0-9]+\.(ml|tk|cf|ga|gq)` should be supported. Though, please use it wisely as it requires more testing in production environment (and bad regexes can break everything)

**Comment by MikhailKasimov** [comment]
> 
> 
> With the latest revision, stuff like `service-confirm-v[0-9]+\.(ml|tk|cf|ga|gq)` should be supported.

Thank you!

> Though, please use it wisely as it requires more testing in production environment (and bad regexes can break everything)

I would be very careful here.
