### ISSUE TITLE
Best practice to upgrade Maltrail?

### ISSUE THREAD

**Issue by youradds** [stamparm/maltrail#14794]
What is the best practice for upgrading Maltrail?  Just upload the new files, and keep a copy maltrail.conf?

**Comment by MikhailKasimov** [comment]
Hello!

Currently there'are two ways: 1) To re-download entire MT and 2) To use special feed: https://twitter.com/maltrail/status/1360302630493327360 (announce).

```and keep a copy maltrail.conf?``` <-- it is anyway useful to have. :)

**Comment by youradds** [comment]
Thanks :) I ended up doing:

```
rm maltrail.conf.bak
mv maltrail.conf maltrail.conf.bak
wget https://github.com/stamparm/maltrail/archive/master.zip
unzip -o master.zip
```

The issue then is that the files are in mailtrail-master, and apart from then doing:

```
cd maltrail-master 
mv -f * ../
rm -f maltrail.conf
cp maltrail.conf.bak maltrail.conf

```

(which seems to have problems, as the other folders exist). Any ideas? I'm trying to write up something that I can have set on a weekly cron, that'll make sure we are on the most up to date :) 

Thanks

Andy

**Comment by MikhailKasimov** [comment]
```(which seems to have problems, as the other folders exist)``` <-- to use ```-R``` key: ```mv -Rf * ../```

```wget https://github.com/stamparm/maltrail/archive/master.zip``` <-- Why not ```git clone --depth 1 https://github.com/stamparm/maltrail.git``` ?

**Comment by youradds** [comment]
Good idea :) In fact, looking more into it this may be better:

git clone https://github.com/stamparm/maltrail.git || (cd /opt/maltrail-test/maltrail; git pull)

Then as long as maltrail.conf if backed up, we could simply to:

cp -f /opt/maltrail/maltrail.conf.bak /opt/maltrail/maltrail.conf

:)

**Comment by youradds** [comment]
If anyone comes across this in the future - its actually pretty simple. Assuming you have maltrail in /opt/maltrail, you do:

/opt/upgrade-maltrail.sh
```

#!/bin/bash

cd /opt
git clone https://github.com/stamparm/maltrail.git || (cd /opt/maltrail; git pull)
cp -f /opt/maltrail/maltrail.conf.bak /opt/maltrail/maltrail.conf

pkill -f /maltrail.conf # kill off everything so it restarts with the new one

# should restart on its own now :)
```

Assuming you have your cronjob setup to keep Maltrail running:

```
* * * * * if [ -n "$(ps -ef | grep -v grep | grep 'server.py')" ]; then : ; else python /opt/maltrail/server.py -c /opt/maltrail/maltrail.conf; fi >/dev/null 2>&1
* * * * * if [ -n "$(ps -ef | grep -v grep | grep 'sensor.py')" ]; then : ; else python /opt/maltrail/sensor.py -c /opt/maltrail/maltrail.conf; fi >/dev/null 2>&1
```


Then just run the upgrade script:

`bash /opt/upgrade-maltrail.sh`

:)

**Comment by stamparm** [comment]
@youradds just one thing to consider. if you put your own `maltrail.conf` to any other location (e.g. `/etc/maltrail.conf`), then you won't have to bother with copy/move steps. in such case, doing a one `git clone `and periodic `git pull` can do wonders

**Comment by youradds** [comment]
Very good point :) I just had all mine in the same folder for cleanliness and keeping it in one place. Maybe I'll do that for new installs :)
