### ISSUE TITLE
About mirror port/span port

### ISSUE THREAD

**Issue by phuocnch** [stamparm/maltrail#148]
Hi Maltrail,

I was successful mirror one port for forwarding all traffic to Maltrail-server but cannot show-up because Maltrail-server only receives UDP port 8837, I was tried to receive UDP 0-65335 but error, could you please help me this case for show all traffic forwarded by a mirror port?

Thanks,
Phuoc

**Comment by stamparm** [comment]
Can you please write down options `UDP_PORT`, `UDP_ADDRESS`, `LOG_SERVER` you use on both server and sensors? I am not sure what seems to be the problem from the original message

**Comment by phuocnch** [comment]
Hi stamparm,

Thanks for your quick response, I install server and sensor run on the same PC and put cable in a port mirror ( this port is configured as SPAN destination ) from a source is another port, now as my understand your product just only receive from sensor.py, right?

Which ways that can I forward all traffic to maltrail's server without using sensor.py? like .log file format?
Sorry for my english not good, please let me know if you do not understand my opinion.

Regards,
Phuoc

**Comment by phuocnch** [comment]
Hi stamparm,

Can I forward flow traffic to MalTrail Server via port 8837?

Regards,
Phuoc

**Comment by stamparm** [comment]
I believe that you are missing the point of SPAN port and/or port mirroring. That traffic is not redirected anywhere. It stays on the sensor machine. It should be available on one (monitoring) network interface for sensor to sniff it.

Now, if you want just to send log messages from SENSOR to remote SERVER you can do that by using options `UDP_PORT`, `UDP_ADDRESS`, `LOG_SERVER`. In such case SERVER is listening on `UDP_ADDRESS:UDP_PORT`, while remote SENSOR sends alert logs to that same SERVER by using option `LOG_SERVER` (for example, in most cases, `UDP_ADDRESS:UDP_PORT` == `LOG_SERVER` <- if `UDP_ADDRESS` is the external address of SERVER exposed to the Internet)

**Comment by phuocnch** [comment]
Hi stamparm,

Thanks for your help, so Maltrail must be default gateway is mandatory? can I use with this topology?
![image](https://user-images.githubusercontent.com/30856439/29209829-c1b67b76-7eba-11e7-89ea-d866de2aa135.png)

Regards,
Phuoc

**Comment by phuocnch** [comment]
Hi stamparm,

Could you please help with this error?
![image](https://user-images.githubusercontent.com/30856439/29212150-2b4a1442-7ec7-11e7-88e5-1fc4cdefab66.png)

Thanks,
Phuoc

**Comment by stamparm** [comment]
You can use that topology, but I believe that you are still missing the point of "port mirroring". Maltrail doesn't have to be a default gateway. It is just getting data on ONE passive NIC and that data is a network traffic copy coming from the gateway/router/switch...

**Comment by phuocnch** [comment]
Hi stamparm,

I have successful installed both Server/Sensor on the same machine, but I just only receive information only from that machine, other machine on local LAN seem not show on Mailtrail. 
My config of maltrail.conf is:
[Server]
HTTP_Address 0.0.0.0
HTTP_PORT 8338
UDP_Address 0.0.0.0
UDP_Port 8337
[Sensor]
LOG_SERVER ipMaltrail:8337

Can I forward NetFlow traffic to Mailtrail via UDP 8337? or which method that I can forward traffic to Maltrail from Pfsense?

Thanks,
Phuoc

**Comment by phuocnch** [comment]
Hi stamparm,

I have tried forward all NetFlow (v5,v9) traffic from FW to Maltrail through port 8337 but show error from Maltrail is :
"File "/home/abc/maltrail/core/log.py", line 193, in handle = get_event_log_handle(int(sec), resuse=False)"
" ValueError: need more than 1 value to unpack"

Could you please help me on this?

Thanks,
Phuoc

**Comment by stamparm** [comment]
Well, Maltrail can't process Netflow. Netflow is a protocol for carrying condensed information on network traffic, while Maltrail requires full traffic capture.

**Comment by phuocnch** [comment]
Hi stamparm,

Thanks for your response, now I can forward all traffic to Maltrail server by full traffic capture and can monitor our users, I very appreciate your help and thank you very much, J.

Regards,
Phuoc Nguyen
