### ISSUE TITLE
About integrated with UFW or Iptables

### ISSUE THREAD

**Issue by phuocnch** [stamparm/maltrail#149]
Dear stamparm,

Could you please give us some solution for add some Maltrail log with condition is IF severity = high THEN add dst_ip to UFW or Iptables for blocking?

Thanks,
Phuoc Nguyen

**Comment by stamparm** [comment]
Severity is calculated at the client's side (browser), hence, there is no way how to do it at the sensor side. Though, you could do a cronjob at the sensor side where you would grep for certain event types and make a firewall rule accordingly

**Comment by phuocnch** [comment]
Hi stamparm,

Thanks for your information, my solution is creating a CronTab run a script with GREP command on Maltrail's log with severity is HIGH then insert to iptables or UFW file.
But I have a problem is on Maltrail's log hasn't SEVERITY COLUMN, could you please let me know where I can find SEVERITY for the filter?

Regards,
Phuoc Nguyen

**Comment by phuocnch** [comment]
Hi stamparm,

Still waiting for you, could you please help add to the log file with SEVERITY column?

Regards,
Phuoc Nguyen

**Comment by stamparm** [comment]
p.s. severity won't be included into the logs. It is a feature of server side itself. At some other server application (from some other developer) somebody else could calculate severity in different way.

**Comment by phuocnch** [comment]
Dear stamparm,

Thank you very much, I will try for the other way, now we can close this issue, I very appreciate your support.

Best Regards,
Phuoc Nguyen
