### ISSUE TITLE
Issue with ports

### ISSUE THREAD

**Issue by DigiAngel** [stamparm/maltrail#15]
Hey again.  So I've been running the latest git pull for about 4 hours now.  After fixing the Cisco VLAN issue (thanks much!) I am seeing src and dst IP's that look correct, but the ports do not.  An example:

Src:  64.74.133.82
Src Port: 50887
Dst:  x.x.x.x
Dst Port: 56863, 56902

Yet packet capturing during this time shows no hits on port 50887.  Bro-ids does show 64.74.133.82, but Src port ranges from 33573-38544, with Dst port ranges of 33440-33444, this is a traceroute.  Betting something isn't getting translated correctly.  Thank you.

**Comment by DigiAngel** [comment]
Another example...logs show this:
~~~
64.202.161.41   22221   x.x.x.x  53
~~~
But maltrail has:
~~~
64.202.161.41	50887	x.x.x.x	56858
~~~
I've found that the source port is always 50887, and the destination port is always 56858.

**Comment by DigiAngel** [comment]
Will send pcap :)

**Comment by stamparm** [comment]
Will work on it later today.

**Comment by DigiAngel** [comment]
Thanks so much...I know you have a real life :)

**Comment by stamparm** [comment]
@DigiAngel thx for pcap. there was indeed a huge bug related. my fault. bye

**Comment by DigiAngel** [comment]
This is working great now...ports are showing up as they should...thanks so much!
