### ISSUE TITLE
'X-Forwarded-For' Header Support

### ISSUE THREAD

**Issue by xECK29x** [stamparm/maltrail#151]
For traffic sourced from load balancers or proxies leveraging the 'X-Forwarded-For' header to identify "true source" systems would it be possible for Maltrail to replace (or provide a pop-up bubble like you do for multiple items) for 'Source IP' so it is possible to identify the true source of the traffic?

https://en.wikipedia.org/wiki/X-Forwarded-For 

Thanks and keep up the great work!

**Comment by mpochron** [comment]
Any update?

**Comment by stamparm** [comment]
@mpochron done with the latest revision
