### ISSUE TITLE
raspberry

### ISSUE THREAD

**Issue by carlospolop** [stamparm/maltrail#152]
I'm trying to use a raspberry pi as a sensor and server and I have another PC using the sensor and sending the logs to the raspi:8337.
Using wireshark I have noticed that when the sensor of the PC finds something, it sends the log to the raspi:8337. Besides, the raspi is listening in the udp port 8337 and the packages sent by the PC reach the raspi. I have checked it using tcpdump.
Eventhough, the maltrail server doesnt save the log, so it doesnt appear in the maltrail web server.
Does anyone know what can be wrong?

**Comment by stamparm** [comment]
Which options have you used for this?

**Comment by stamparm** [comment]
At server side (192.168.5.27):
![at_server_side](https://user-images.githubusercontent.com/921555/30313310-281fa7fc-979d-11e7-90c9-32a05b482266.png)

At sensor side (192.168.5.33):
![sensor](https://user-images.githubusercontent.com/921555/30313307-281e3368-979d-11e7-9f43-6543b6e40c39.png)

Curl (test from sensor toward known malicious IP):
![test](https://user-images.githubusercontent.com/921555/30313311-281fedb6-979d-11e7-82db-3e85d33b577a.png)

Wireshark (capture of UDP log):
![wireshark](https://user-images.githubusercontent.com/921555/30313373-5c026582-979d-11e7-9670-5fc1a2d5cbe9.png)

Results at server side:
![test2](https://user-images.githubusercontent.com/921555/30313309-281ead34-979d-11e7-9dd6-2f2c1e66dd96.png)

**Comment by stamparm** [comment]
p.s. there is one thing. Logs are not immediately sent because of condensing (packing multiple same events to prevent unnecessary log traffic).

Though, I can see that there is a situation (particularly when testing) when log could be trapped before another log occur. Just to take a quick look and maybe patch

**Comment by stamparm** [comment]
With latest revision strictly every 10 seconds (`core/settings.py` -> `CONDENSED_EVENTS_FLUSH_PERIOD`), in case of event condensing, logs will be sent (if any)

**Comment by carlospolop** [comment]
Raspberry pi server(192.168.0.183):
![screen shot 2017-09-12 at 10 50 35](https://user-images.githubusercontent.com/17181413/30317391-4957e198-97aa-11e7-9c38-aad6a943bf0e.png)

PC sensor:
![screen shot 2017-09-12 at 10 56 18](https://user-images.githubusercontent.com/17181413/30317418-5e32f918-97aa-11e7-94a9-706f1c31fba9.png)

Ping from PC to malicious IP:
![screen shot 2017-09-12 at 11 06 22](https://user-images.githubusercontent.com/17181413/30317462-7e879d40-97aa-11e7-8c30-0d0fbc65861a.png)

PC wireshark after the ping:
![screen shot 2017-09-12 at 11 03 51](https://user-images.githubusercontent.com/17181413/30317492-8ddcd094-97aa-11e7-9933-d87acd18041c.png)

Raspi tcpdump after the ping:
![screen shot 2017-09-12 at 11 04 02](https://user-images.githubusercontent.com/17181413/30317513-98c31e00-97aa-11e7-8988-08a77c2a0b5b.png)

Raspi maltrail web server after the ping:
![screen shot 2017-09-12 at 11 04 31](https://user-images.githubusercontent.com/17181413/30317537-a8209468-97aa-11e7-9b5e-0eddb04a81b1.png)

It looks like the packet reach the server but the raspberrypi doesnt log it.
What can be happening?

**Comment by stamparm** [comment]
Try to run sensor with `--debug` or take a look into `/var/log/maltrail/error.log`

**Comment by carlospolop** [comment]
There is nothing in /var/log/maltrail/error.log
The sensor --debug tells me when it find some problem and it sends the log to the server, but I think that the server doesnt log it.

**Comment by stamparm** [comment]
As said, can't reproduce. Not sure how to help you

**Comment by carlospolop** [comment]
Sure, thanks a lot for your help!
I will try to debug it more and see if I can find the problem

**Comment by Wyncham** [comment]
Same issue for me on raspberry pi3 using quick start instruction.

**Comment by 0E800** [comment]
Possibly different time settings? Check the date/time on your server vs the sensor.

**Comment by Faustino50-Cat** [comment]
Now I tried your "same" settings and it is working, have you checked your firewall rules or something else?
