### ISSUE TITLE
Cannot show debug on Maltrail

### ISSUE THREAD

**Issue by phuocnch** [stamparm/maltrail#154]
Hi stamparm,

Could you please help me with show debug for maltrail? although SHOW_DEBUG true in Maltrail.conf but it not show in console output.

Regards,
Phuoc Nguyen

**Comment by stamparm** [comment]
`SHOW_DEBUG` enables debug messages, but in case of Maltrail those messages are only related to exceptions or similar errors

**Comment by phuocnch** [comment]
Hi stamparm,

The other maltrail's system version 0.10.274 with SHOW_DEBUG true that I can see these logs like below picture that for me can know the system is running. maybe I miss config somewhere?
![image](https://user-images.githubusercontent.com/30856439/31209027-af8d9c04-a9b2-11e7-80fc-4ca69e2d1a4e.png)

**Comment by stamparm** [comment]
`ignore_event` is a leftover. Removed recently. If you want to see the events (similar to those at the given console output), you should use `--console`:

```
$ python sensor.py -h
Maltrail (sensor) #v0.10.281

Usage: sensor.py [options]

Options:
  --version       show program's version number and exit
  -h, --help      show this help message and exit
  -c CONFIG_FILE  configuration file (default: 'maltrail.conf')
  -i PCAP_FILE    open pcap file for offline analysis
  -p PLUGINS      plugin(s) to be used per event
  --console       print events to console (too)
  --no-updates    disable (online) trail updates
```

**Comment by phuocnch** [comment]
Thanks stamparm, It's worked.

Best Regards,
PN
