### ISSUE TITLE
Memory is not enough.

### ISSUE THREAD

**Issue by tonybreak** [stamparm/maltrail#155]
![001](https://user-images.githubusercontent.com/9734167/31042022-76d67064-a5d1-11e7-9550-8241500d8a5c.jpg)

When I log in the maltrail web, the web page just loading, and then the alert is that "Memory is not enough. "

how can i fix it?

**Comment by tonybreak** [comment]
append:
when i set up maltrail in 8 servers, the log file from 800MB  to 1.2GB. when i log in the web, it have 3~5 min to log in.

What can I do to view the website quickly in one min?

**Comment by stamparm** [comment]
For some reason you are getting too many alerts (events recorded). Have you changed something in default configuration?

**Comment by tonybreak** [comment]
I use the default configuration, I don't chaned anything. The log file is too large, you see it.

![001](https://user-images.githubusercontent.com/9734167/31328006-37f4231a-ad05-11e7-8707-b8d04b3306aa.jpg)
![002](https://user-images.githubusercontent.com/9734167/31328007-38201e98-ad05-11e7-92ae-a7790ba912ac.jpg)

The webbrowser's memory is increasing, and biger and biger. Then the webbrowser will popup " Memory is not enough. " and the web site of maltrail will crash.

Maybe, my logs is too much. So, 
1. I think I can delete the low severity event. 
2. Or, I can set up 4 different servers to solve the problem.(Don't send all logs to one server)

How do you think about 2 of above.
Need more help. Thank you.

**Comment by stamparm** [comment]
Try to use `DISABLED_FEEDS` (https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L43). You are getting way too many alerts. Here on a fairly large network I don't get more than 100MB per day.

Try to put inside the `DISABLED_FEEDS` items like `voipbl,dataplane,turris, ciarmy, policeman`

**Comment by tonybreak** [comment]
Ok, thank you a lot. I will have a try.
