### ISSUE TITLE
open Multiple files pcap file for offline analysis at the same time

### ISSUE THREAD

**Issue by nmweizi** [stamparm/maltrail#156]
- I have multiple files.Each file 2G size.

1. aaa01.pcap
2. aaa02.pcap
3. aaa03.pcap

- I hope:
sensor.py -i aaa*.pcap

**Comment by rickhg12hs** [comment]
Same as #1587?

**Comment by stamparm** [comment]
@rickhg12hs yup. thx. closing as duplicate

**Comment by stamparm** [comment]
Duplicate of #1587 (solved)
