### ISSUE TITLE
How to delete the low servrity events?

### ISSUE THREAD

**Issue by tonybreak** [stamparm/maltrail#158]
How to delete the low servrity events in the log?

**Comment by stamparm** [comment]
Currently there is no way because severity is being calculated at the clients side (JS). However, I would recommend you to use `DISABLED_FEEDS` option inside the maltrail.conf (https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L43)

**Comment by tonybreak** [comment]
Thanks, I found that the logs about "potential data leakage" are too much. And some websites are APIs. So I changed the file of  core/setting.py.

Thanks a lot for replying.
