### ISSUE TITLE
Can I analyze multiple pcaps simultaneously at the same time?

### ISSUE THREAD

**Issue by xuluhang** [stamparm/maltrail#1587]
Can I analyze multiple pcaps simultaneously at the same time?
like that
sudo python sensor.py -i /home/1/*.pcap

**Comment by stamparm** [comment]
@xuluhang with the latest revision you can do it with the command you've stated. Just update and retry

**Comment by MikhailKasimov** [comment]
Related: https://kryptera.se/threat-hunting-maltrail/
