### ISSUE TITLE
VPN Configuration

### ISSUE THREAD

**Issue by CyborSnake** [stamparm/maltrail#16]
Good evening.

I write to ask if anyone knows how to make a confguration so you can connect to the server through a VPN.
In local network work correctly. But when trying to connect to the server through a VPN, which is not put in the IP address settings.
For your reply, thanks.

**Comment by stamparm** [comment]
When using a default 0.0.0.0 as a HTTP_ADDRESS you should be able to connect the server itself from any assigned address on any interface (if its reachable in the first place).

Please do the 'ifconfig | grep inet' to get all assigned addresses. At least one of those addresses should be accessible in your situation from the VPN
