### ISSUE TITLE
Remove 195.22.26.248 as malicious IP

### ISSUE THREAD

**Issue by RichieB2B** [stamparm/maltrail#160]
You probably want to remove 195.22.26.248 from [sinkhole_anubis.txt](https://github.com/stamparm/maltrail/blob/master/trails/static/malware/sinkhole_anubis.txt) as it will generate a lot of false positives. For example last summer a popular advertisement server was sinkholed to that IP.

Anubis has indicated they use this IP to sinkhole domains they are not sure are malicious yet, see https://www.alienvault.com/forums/discussion/10634/multiple-alarms-for-sinkhole-anubis-this-week

**Comment by stamparm** [comment]
Thank you. Will disable it this moment.
