### ISSUE TITLE
CoinBlockerList lists for consideration

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#1603]
Hello!

https://twitter.com/hobbygrafix/status/1121661376236097539

https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html <-- accessable list to have as feed.

Please, consider!

**Comment by MikhailKasimov** [comment]
@stamparm Ideas|Accepting|Refusing?

**Comment by stamparm** [comment]
1) We already have bunch of "mining" feeds and/or static scripts
2) Checked this one and I am not confident about it or its purpose:

![1](https://user-images.githubusercontent.com/921555/100439297-a7ec0f00-30a3-11eb-9fe4-925354d8ea6a.png)
