### ISSUE TITLE
Help needed for setting up server in one machine and client in another machine

### ISSUE THREAD

**Issue by santhoshcameo** [stamparm/maltrail#16130]
I came across maltrail project and it is such a wonderful piece of engineering work. I would love to test it with two  Openstack machines/ AWS EC2 machines

I am able to succeed in both server and sensor in the same machine using the docker file provided by you. 

But I am really not sure how to run the server in 1 Ec2 and the client in another EC2 machine. I was trying this for a week based on documentation but I am unable to proceed because the configuration file is difficult for me to understand.

Please help me with this.

this would be a big help.

**Comment by MikhailKasimov** [comment]
Hello!

Try chapter 1 of this manual: https://github.com/stamparm/maltrail/wiki/Miscellaneous/9f02fd2ddb345a60e43c3f532c7650ac862d0e0c

**Comment by santhoshcameo** [comment]
@MikhailKasimov  I am sorry, I could not write back, but this worked like a charm and the documentation is neat and clear for beginners as well. thank you.
