### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Albertmoiseev** [stamparm/maltrail#162]
Hi everyone,

What do you think regarding implementing python 3.x support?

**Comment by stamparm** [comment]
Not a huge fan of that idea as lots of per-string operations are totally different. Why would you like it to be implemented in Python 3 in the first place?

**Comment by q2dg** [comment]
Because of this: https://pythonclock.org

**Comment by stamparm** [comment]
@q2dg will see. Currently I have a bigger priority project to work on with this "clock" on my mind, though, I have a strange feeling that the Python2 will be strong even after the set time

**Comment by mimugmail** [comment]
I'm also not a fan of the clock but maybe FreeBSD 12.1 will drop support when Python2 reaches EoL so I might get problem with OPNsense plugin in 2020. But .. no rush yet :)

**Comment by MikhailKasimov** [comment]
https://www.ncsc.gov.uk/blog-post/time-to-shed-python-2

**Comment by mimugmail** [comment]
Ubuntu 20.4 will most likely be without P2: https://fullcirclemagazine.org/2019/08/28/debian-and-ubuntu-plan-to-remove-python-2/

**Comment by stamparm** [comment]
Don't worry. Will do it when I catch time

**Comment by stamparm** [comment]
Stabilizing Python3 port. Now came across `AssertionError: sorry, but this version only supports 100 named groups` <- @MikhailKasimov, you know the reason behind it, although, I didn't know that Python (3?) made a hard cap limit here. Anyway, I have some more things to do here, but all in all, current prototype works (Note: environment variable `MALTRAIL_DREI` has to be set to `1` if somebody wants to take a sneak peek with Python3 and latest HEAD revision)

**Comment by MikhailKasimov** [comment]
> 
> 
> Stabilizing Python3 port. Now came across `AssertionError: sorry, but this version only supports 100 named groups` <- @MikhailKasimov, you know the reason behind it, although, I didn't know that Python (3?) made a hard cap limit here.

https://stackoverflow.com/questions/478458/python-regular-expressions-with-more-than-100-groups

**Comment by stamparm** [comment]
@MikhailKasimov I've stumbled upon that link, but it provides no solution to the problem. All those "replies" rely on third-party libraries (e.g. `cregex`). I'll deal with this

**Comment by stamparm** [comment]
Stabilized, patched lots of stuff, quick tested on a huge-pipe. It works pretty well :)

**Comment by stamparm** [comment]
@Godwottery to be honest, your first pull request (https://github.com/stamparm/maltrail/pull/3569) was a trigger for me to finish this up. Hence, I would like to thank you and put you on the https://github.com/stamparm/maltrail/#thank-you. Do you want me to use or real name or just the handle?

**Comment by Godwottery** [comment]
> @Godwottery Do you want me to use your real name (what is it?) or just the handle?
I appreciate the thank-you. I would prefer if you use the handle.

**Comment by stamparm** [comment]
@Godwottery [done](https://github.com/stamparm/maltrail/#thank-you) :)
