### ISSUE TITLE
Is Maltrail portable to windows OS?

### ISSUE THREAD

**Issue by caraevangeline** [stamparm/maltrail#16408]
Hi,

I went across previous similar issues, since those were opened and closed long time ago, I want to know whether any fixes have been found recently to make maltrail sensor work for Windows. While I try to run the sensor in windows, it asked me to install Wincap and Pcapy, I did so but the libraries are broken I believe for WIndows OS hence facing issue resolving it. Is there any possibility of using Maltrail sensor for Windows OS?

**Comment by stamparm** [comment]
Tried again for N-th time to get everything up and running on Windows. Now, after downloading and installing 3rd Microsoft Package, I have to download 2GB of Visual C++ build tools to install pcapy (via pip). Sorry, closing this down
