### ISSUE TITLE
offline pcap analysis

### ISSUE THREAD

**Issue by Parita24** [stamparm/maltrail#165]
Hi,
i want to analyse a pcap file through maltrail which i have downloaded from wireshark.I have stored that file on tmp folder and i try to run sensor.py using command :
$ sudo python sensor.py --console -p /tmp/sick-client.pcap
it is throwing an error : 
plug-in script 'sick-client.pcap' should have an extension '.py'
![capture](https://user-images.githubusercontent.com/36918094/36781935-5bf15c30-1c9d-11e8-9ab3-d292a3f5767a.PNG)

**Comment by stamparm** [comment]
Actually, it is option `-i` that you are looking for:

```
$ python sensor.py -h
Maltrail (sensor) #v0.10.310

Usage: sensor.py [options]

Options:
  --version       show program's version number and exit
  -h, --help      show this help message and exit
  -c CONFIG_FILE  configuration file (default: 'maltrail.conf')
  -i PCAP_FILE    open pcap file for offline analysis
  -p PLUGINS      plugin(s) to be used per event
  --console       print events to console (too)
  --no-updates    disable (online) trail updates
```
