### ISSUE TITLE
Can't use SSL in maltrail server

### ISSUE THREAD

**Issue by dawydh** [stamparm/maltrail#166]
Hi,

When I activate SSL in Maltrail config's file an error is shown on the console. Here is the error traceback

root@xxxxxxxx:/opt/maltrail# ./server.py 
Maltrail (server) #v0.10.325

[i] using configuration file '/opt/maltrail/maltrail.conf'
[!] unhandled exception occurred ('[('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'PEM lib')]')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "./server.py", line 108, in <module>
    main()
  File "./server.py", line 100, in main
    start_httpd(address=config.HTTP_ADDRESS, port=config.HTTP_PORT, pem=config.SSL_PEM if config.USE_SSL else None, join=True)
  File "/opt/maltrail/core/httpd.py", line 599, in start_httpd
    server = SSLThreadingServer((address or '', int(port) if str(port or "").isdigit() else 0), pem, SSLReqHandler)
  File "/opt/maltrail/core/httpd.py", line 93, in __init__
    ctx.use_certificate_file(pem)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 391, in use_certificate_file
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'PEM lib')]
'
---
[i] finished

Thank you so much.
David

**Comment by stamparm** [comment]
Please take a look at https://serverfault.com/a/317038. It is possible that the newline character (in PEM file) is causing problems.

**Comment by dawydh** [comment]
Thank you so much,  
I've reviewed the link, and I've solved the problem.  Your code works perfectly.
I had written an error when I have been generated the certificate.

David
