### ISSUE TITLE
New holding IP

### ISSUE THREAD

**Issue by youradds** [stamparm/maltrail#16636]
Hi,

I just came across an IP that doesn't seem to be in your system: 52.15.160.167 . A selection of example domains I found (quite a few thousand , but this is a random selection which I've looked at, and all seem to be holding / auction pages)

pareforce.com                  
trainerexpert.com              
cannagp.com                    
lagosx.com                     
xmyqp.com                      
247ua.com                      
hectorius.com                  
rxbone.com                     
nantucketsoup.com              
dbreveal.com                   
iqskenya.com                   
cosmeticid.com                 
bionitric.com                  
inkblotco.com                  
iberostarspecialist.com        
asapela.com                    
repairyourworld.com            
wearelitco.com          

Cheers

Andy

**Comment by MikhailKasimov** [comment]
Hello!

What category you propose to apply here?

**Comment by youradds** [comment]
Not sure. It seems to just be a holding page. I got it from domains, and their CNAMES point to quite a few:

```
"107","prod-sav-park-lb01-1919960993.us-east-2.elb.amazonaws.com","52.15.160.167 3.128.211.88 3.16.197.4"
"28912","paytj.cdnxx.com","52.15.160.167 3.16.197.4 3.128.211.88"
"29376","advancenames.com","52.15.160.167 3.16.197.4 3.128.211.88"
"29782","www.malibulottery.com","52.15.160.167 3.16.197.4 3.128.211.88"
```

**Comment by stamparm** [comment]
Added this moment to the `suspicious/parking_site.txt`
