### ISSUE TITLE
Auto refreshing

### ISSUE THREAD

**Issue by Ekultek** [stamparm/maltrail#168]
# Issue

MacOS using Safari in order to update the list, you have to refresh the browser page

# Operating system specs

Mac mini Server (Late 2012), El Capitan v10.11.6

# Possible solution

You can create a bash script designed for macOS:

`osascript -e 'tell application "Safari" to tell the active tab of its first window to reload'`

If you can tie it into the update configuration:

```
# Update trails after every given period (seconds)
UPDATE_PERIOD 86400
```

and run the script when that time period occurs it should fix the issue

**Comment by MikhailKasimov** [comment]
I think, we can have something more generic here and e.g. apache2 ```mod_status``` module gives a hint for such variant -- to have something like ```example.com:8338/?refresh=N``` , where N -- page refreshing period (secs).

See [0] https://httpd.apache.org/docs/current/mod/mod_status.html ```Automatic Updates``` section:

```You can get the status page to update itself automatically if you have a browser that supports "refresh". Access the page http://your.server.name/server-status?refresh=N to refresh the page every N seconds.```

@stamparm ?

**Comment by Ekultek** [comment]
@MikhailKasimov Stan doesn’t like me so I doubt he’ll answer, I like the idea of using apache though. I’m gonna go ahead and close this though

**Comment by MikhailKasimov** [comment]
@Ekultek The lastest MT revision contains now this functionality in https://github.com/stamparm/maltrail/issues/624
