### ISSUE TITLE
attack map 

### ISSUE THREAD

**Issue by unmanagedtn** [stamparm/maltrail#16926]
Over at Spiceworks i ran into this thread and code that a user has developed to make a threat map. Is there any chance of having this implemented in maltrail directly ? 

see the following...

[Spiceworks topic.... ](https://community.spiceworks.com/topic/2257564-found-free-easy-to-interface-with-cyber-attack-map-for-in-house-use?page=1)

[fileshare](https://nc.co.cheshire.nh.us/index.php/s/KNRfzb9L75QKTyF?)

Thanks for the great software and all you do...

G

**Comment by stamparm** [comment]
Related to #117 (closing this down as duplicate). Maybe some day there will be something like this.
