### ISSUE TITLE
bug cannot allocated memory

### ISSUE THREAD

**Issue by darcosion** [stamparm/maltrail#17]
Trying to start the soft in an ubuntu 14.04 : 

:~/maltrail$ sudo python sensor.py
Maltrail (sensor) #v0.8.187

[i] using configuration file '/home/toopak/maltrail/maltrail.conf'
[i] loading trails file...
[i] 921,479 trails loaded
[i] using '/var/log/maltrail' for log storage
[!] in case of any problems with packet capture on virtual interface 'any', please put all monitoring interfaces to promiscuous mode manually (e.g. 'sudo ifconfig eth0 promisc')
[i] opening interface 'any'
[i] setting filter '(tcp[13] == 2) or (tcp[13] & 8 != 0) or not tcp'
[i] creating 3 more processes (4 CPU cores detected)
[!] unhandled exception occurred ('[Errno 12] Cannot allocate memory')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "sensor.py", line 531, in <module>
    main()
  File "sensor.py", line 524, in main
    init()
  File "sensor.py", line 443, in init
    _init_multiprocessing()
  File "sensor.py", line 470, in _init_multiprocessing
    _buffer = mmap.mmap(-1, BUFFER_LENGTH)  # http://www.alexonlinux.com/direct-io-in-python
error: [Errno 12] Cannot allocate memory
'
---
If a can adding another data for fix this bug...

**Comment by stamparm** [comment]
I'll make a more graceful exit and a warning, but it would be great to know what went wrong in your case.

Have you changed CAPTURE_BUFFER? If yes, to what value? If no, can you please write down what's your server's memory capacity. I've experienced this kind of behavior on low memory VPSes

**Comment by stamparm** [comment]
@darcosion there has been a related bug fixed today. can you please update and retry?

**Comment by stamparm** [comment]
`CAPTURE_BUFFER` has not been taken into the consideration (it was always 512 MB :). sorry for that

**Comment by darcosion** [comment]
Apparently, that's work. :)

Thanks for this anwsome tool.
