### ISSUE TITLE
Maltrail hangs on file import

### ISSUE THREAD

**Issue by ddb9797** [stamparm/maltrail#17205]
If I analyze a file with :

`sudo python3 ~/Desktop/maltrail/maltrail/sensor.py --console -r ...`

maltrail hangs after x packets. I'm not sure if it is caused by the content of the packet or a buffer that is full, but if i insert a print IP address in the code it always halts at the same packet.

**Comment by MikhailKasimov** [comment]
Hello!

Need info on: 

1) Maltrail version you use.
2) Environment (Linux or *BSD) you run Maltrail.
3) Please, attach file you use for making us to be able to reproduce your problem.

Thank you!

**Comment by ddb9797** [comment]
Seems like a problem with multiprocessing, because if I comment out 

```
    try:
        import multiprocessing

        if config.PROCESS_COUNT > 1 and not config.profile:
            _multiprocessing = multiprocessing
    except (ImportError, OSError, NotImplementedError):
        pass
```

it works

**Comment by ddb9797** [comment]
1. Maltrail version: 0.34
2. Env: Linux (debian)
3. Can't attach the file, because it's confidential information. Sorry

**Comment by ddb9797** [comment]
I'm searching a sample pcap file (couple of MBs) to demonstrate

**Comment by ddb9797** [comment]
Weird. For all the sample captures I find (no matter the size) Maltrail has no problem. I guess it must be inherent to the specific trace I'm analyzing. I guess you/I should close this issue because I cannot reproduce the issue properly.

**Comment by ddb9797** [comment]
for people with similar issues: just comment out the code mentioned above

**Comment by MikhailKasimov** [comment]
@stamparm : FYI --> https://github.com/stamparm/maltrail/issues/17205#issuecomment-863164503
