### ISSUE TITLE
Aws all ec2 instance monitoring architecture diagram

### ISSUE THREAD

**Issue by dipenpatel235** [stamparm/maltrail#17209]
Hello
I have 10 ec2 instances and I want to monitor all using maltrail.

So how I can setup this on my aws network ?
Please guide something about setup architecture diagram.

Thanks

**Comment by MikhailKasimov** [comment]
Hello!

1) Install MT on one instance you want to be the main.
2) In ```/maltrail.conf``` file in ```[Server]``` section find ``` # Listen port of (log collecting) UDP server``` option and activate it:

 ```
 # Listen port of (log collecting) UDP server
 UDP_PORT 8337
 ```
 
 3) In ```/maltrail.conf``` file in ```[Sensor]``` section find ```# Remote Maltrail server instance to send log entries (Note: listening at <UDP_ADDRESS>:<UDP_PORT>)``` option and activate it:
 
 ```
# Remote Maltrail server instance to send log entries (Note: listening at <UDP_ADDRESS>:<UDP_PORT>)
LOG_SERVER 192.168.2.107:8337

 ```
Do not forget to put your main instance IP here.

4) Install Maltrail on other 9 instances, but activate ```# Remote Maltrail server instance to send log entries (Note: listening at <UDP_ADDRESS>:<UDP_PORT>)``` option only there.

5) Save changes in ```/maltrail.conf``` on all 10 instances.

6) On main instance do run ```/maltrail/server.py``` and ```/maltrail/sensor.py``` scripts. On other nine instances do run ```/maltrail/sensor.py``` script only.

**Comment by stamparm** [comment]
@dipenpatel235 tl;dr: one machine has to be run as `server` (more info [here](https://github.com/stamparm/maltrail/#server)), while all other machines can be used as `sensors` (more info [here](https://github.com/stamparm/maltrail/#sensor)). Sensors' option `LOG_SERVER` should point to the server's `UDP_ADDRESS`:`UDP_PORT` for server to be able to collect all the events at one place. Additionally, you should set the option `SENSOR_NAME` at all sensors to some distinct names, so you could distinguish the event sources

**Comment by dipenpatel235** [comment]
thanks you so much @MikhailKasimov @stamparm i will go through and make it done.
