### ISSUE TITLE
False Positive for btloader.com 

### ISSUE THREAD

**Issue by architect00** [stamparm/maltrail#17444]
Hi,

we got a lot of alerts for btloader.com. This website seems to be used for tracking oder ads. As an example this is also used on https://9to5mac.com/ and dictionary.cambridge.org.

We found the domain and its associated domains in the tracker wiki: https://slayterdev.github.io/tracker-radar-wiki/domains/btloader.com.html

https://github.com/stamparm/maltrail/blob/bbfddf987139de09fec5e92ccc9bfc20ff38e948/trails/static/malware/generic.txt#L14572

**Comment by stamparm** [comment]
Sorry. My bad. I usually do sanity checks. This time this one slipped it

**Comment by MikhailKasimov** [comment]
Hello! Sorry from my side too.
