### ISSUE TITLE
In some cases, the server will stop working

### ISSUE THREAD

**Issue by xuluhang** [stamparm/maltrail#1772]
I found that if the number of alerts in a day was very large, the server would not be able to show me the output. Is there any way to fix this problem?

**Comment by xuluhang** [comment]
There are about 200,000 events.

**Comment by xuluhang** [comment]
Is this related to the offline environment?

**Comment by stamparm** [comment]
You are having problems at the server side or at the client (browser) side?

I would suggest you to "reduce" number of events by using options such as `DISABLED_FEEDS` and/or `DISABLED_TRAILS_INFO_REGEX`. One good example (used in my production environment) goes like this:

`DISABLED_TRAILS_INFO_REGEX known attacker|tor exit node|proxy|spammer|reputation|mass scanner|compromised`
