### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by pierrehegr** [stamparm/maltrail#18]
Hi, 

On FreeBSD, 10.2 (64bits), I have this issue:

>[i] using configuration file '/usr/maltrail/maltrail.conf'
free: not found
[!] unable to determine total physical memory. Please use absolute value for 'CAPTURE_BUFFER'

Sincerely

**Comment by stamparm** [comment]
@pierrehegr can you please check on FreeBSD `top -n 1` and tell me if you get only one screen of data?

**Comment by pierrehegr** [comment]
Hi, 
Yes, here is the result of the command:
>last pid:  1055;  load averages:  0.38,  0.25,  0.23  up 70+18:04:02    04:23:25
40 processes:  1 running, 39 sleeping
Mem: 566M Active, 6436M Inact, 737M Wired, 49M Cache, 826M Buf, 55M Free
Swap: 512M Total, 89M Used, 423M Free, 17% Inuse
PID USERNAME       THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
98670 root            10  21    0   405M   194M uwait   3   0:24   0.29%

**Comment by stamparm** [comment]
can you please update and retry?

**Comment by pierrehegr** [comment]
It's done, thanks.

Now, I just have this:
>[!] unable to determine total physical memory. Please use absolute value for 'CA                              PTURE_BUFFER'

**Comment by stamparm** [comment]
i've just downloaded freebsd vmware image. going to find a solution in mins

**Comment by pierrehegr** [comment]
Ok, it's very nice to you

**Comment by akizor** [comment]
Same issue here

Maltrail (sensor) #v0.8.175
[i] using configuration file '/path/maltrail/maltrail.conf'
/bin/sh: free: command not found
[!] unable to determine total physical memory. Please use absolute value for 'CAPTURE_BUFFER'

OS X El Capitan
10.11.1 (15B42)

**Comment by stamparm** [comment]
@pierrehegr can you please retry?

**Comment by stamparm** [comment]
@akizor can you please retry with the latest revision?

**Comment by pierrehegr** [comment]
Works for me

**Comment by pierrehegr** [comment]
Thanks a lot!

**Comment by stamparm** [comment]
@akizor if you still experience the problem, please open a new Issue

**Comment by akizor** [comment]
@stamparm Thanks. Works like a charm!
Btw, congrats on making this.

**Comment by stamparm** [comment]
@akizor thx :)
