### ISSUE TITLE
Clearing events

### ISSUE THREAD

**Issue by crazyintern** [stamparm/maltrail#18216]
Clear button did not work for me. Please let me know ways to clear log on the UI

**Comment by MikhailKasimov** [comment]
Hello!

If you mean this "Clear" button

![Screenshot_897](https://user-images.githubusercontent.com/7167300/128637557-5416323a-6dca-42a9-b5b0-28c2d107c10e.png)

it works for ```Filter``` field only.

Example: 1) If you put, e.g. DNS in ```Filter``` field, GUI will display you info about events, related to DNS-requests only. 2) After clicking ```Clear```, field ```Filter``` will be cleaned and GUI will display events of all types.
