### ISSUE TITLE
[Source] badIPS

### ISSUE THREAD

**Issue by scriptzteam** [stamparm/maltrail#18233]
Hi,
we have a lot of servers across globe, and on some we runnin own honeypots, but also maltrail and cowrie, etc... We do collect badIPS in real time -> https://github.com/scriptzteam/badIPS

If interested you can use as feed -> https://raw.githubusercontent.com/scriptzteam/badIPS/main/ips.txt

**Updated every 5 min.**

^-^

**Comment by stamparm** [comment]
hi. this looks like totally new blacklist. i don't mind including new feeds, but, it should have any kind of continuity before the inclusion. we can repeat this whole procedure in a month or so if you continue to update the list.

p.s. i believe that update of every 5 mins will unnecessary fill git logs

**Comment by scriptzteam** [comment]
Still running :D

**Comment by stamparm** [comment]
@scriptzteam currently you have following junk inside:

```
0
09.29
10.178.148
.103.253.103
.109
11
1.125.164
116.135.59
117.165.222
.139.109
.141.60.134
.143.152
.148
.149.26.218
156.81.59
161.12
16.141.168
.166.191.23
169.206
17.12.53
175
.177.173.8
184
.185.126.99
185.159
2
20
.201.148
2.204
.224
.237
.25.102
4.39
49.130
.50
52
52.175
5.220
5.246
53.248
53.253
.54.65
59
6.131.247
63.97.246
68
68.118
.72
.74
.75.69
8
.81
8.230.148
8.48.251
8.62.88
88.183
98.51.104
```

**Comment by scriptzteam** [comment]
Oops thats just wrongly parsed from log files, easy to fix, thx!

**Comment by scriptzteam** [comment]
Now properly checking if its real ipv4

https://github.com/scriptzteam/badIPS/commit/99b3526e6142081efbafe020fd818b5619d3c201

**Comment by stamparm** [comment]
@scriptzteam added (https://github.com/stamparm/maltrail/blob/master/trails/feeds/scriptzteam.py). i hope that there won't be any problems with it

**Comment by scriptzteam** [comment]
Thx!
In the end its just ips that attacked lots of our servers (ssh, mysql, telnet, any many more)...
