### ISSUE TITLE
All events are sent to syslog system with medium severity

### ISSUE THREAD

**Issue by pedimave** [stamparm/maltrail#18282]
I have started sending events to an external syslog and logstash systems.

My issue is that although I can see a different severity errors in the web interface (high or low), when it sends to syslog system all of them are sent with medium severity.

Thanks.

**Comment by stamparm** [comment]
please take a look into the [REMOTE_SEVERITY_REGEX](https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L104)
