### ISSUE TITLE
Logging of all audited connections (good and bad)

### ISSUE THREAD

**Issue by vicjos** [stamparm/maltrail#18494]
Hello everyone,

I've been trying for some time to achieve (through the two example plugins that are in maltrail/plugin) the way to have all the urls and ips that are checked. In order to be able to make a plugin that filters with another type of intelligence what maltrail through pcapy detects. And running pcapy twice seems to me suboptimal within the same machine.

Could you help me to generate a plugin, or add an option in the sensor.py call that allows to write in a TXT or standard TTY output (or other way) all the urls and ips that pass through the "router"?

This would allow to link maltrail to other existing solutions or own developments. Expanding power and functionality.

Thank you very much,

**Comment by stamparm** [comment]
1) Problem is that `--plugin` provided "plugins" are only run per "event", or to rephrase, when something "bad" happens. Also, I've done a through check, and there is not simple way to implement this into Maltrail
2) At my previous workplace, we've run multiple pcap based sniffers, even on big pipes, without any problems. Though, you have to be pretty selective on what to extract and what to filter out. For example, we used https://github.com/stamparm/dnslog to store all DNS records (independently from Maltrail), and this solution works pretty fast

**Comment by vicjos** [comment]
Thank you very much for your answer, **and for your work.**

I am researching on algorithms to detect if an unlisted IP is bad (for double check), and block it and add it to a TXT list of trails for further warnings and blocking. I know this is a huge world, but I want to focus on small threats, test, and if effective, expand it.

It is clear to me how to intercept DNS resolution with your proposal. I will try it!

I know it is very difficult to implement because I put a couple of checks in the code and it is not easy. But I try to give it some different approach for the solution, in case I could turn on the light bulb across a easy way:

For IP interception (even DNS), couldn't an option be enabled that if it's neither a bad trail nor whitelist, it's "suspicious"? (or other category).

Alternatively, a regex at the end of everything (before exiting or with very low priority over rest) that says that any pattern matching 0.0.0.0.0/0 write it as suspicious.

When it is classified as "suspicious", the plugin filter can be applied to it.

If you can't, I won't insist any more, I don't want to waste your time with my comments (thanks!).

I will try your github about DNS resolution, and research about IP while read your answer.

I will keep a close eye on this great project in case you come up with any improvements in this regard.

Thanks a million,
