### ISSUE TITLE
Failed to launch sensor/server on Archlinux

### ISSUE THREAD

**Issue by icolab** [stamparm/maltrail#1850]
Hi, 

I started to install Maltrail on my Archlinux server over when I try to launch the sensor or the server I had a python error:
```
File "sensor.py", line 785
    except (ImportError, SyntaxError), msg:
                                     ^
SyntaxError: invalid syntax
```
```
  File "server.py", line 109
    except SystemExit, ex:
                     ^
SyntaxError: invalid syntax

```
Moreover, there is no log file to help me to understand what is happening. 
I'm using python 3.7.3

Sincerely

**Comment by MikhailKasimov** [comment]
> I'm using python 3.7.3

https://github.com/stamparm/maltrail#requirements : ```To properly run the Maltrail, Python 2.6.x or 2.7.x is required```

Python 3 is not supported: https://github.com/stamparm/maltrail/issues/162

**Comment by stamparm** [comment]
@icolab as @MikhailKasimov said, Python 2 is required. With the latest revision you'll see a message such as `[CRITICAL] incompatible Python version detected ('3.5.2'). For successfully running Maltrail you'll have to use version 2.6 or 2.7 (visit 'http://www.python.org/download/')`

**Comment by icolab** [comment]
Thanks for your answers and sorry for the disturbance I didn't see it 
Sincerely

**Comment by MikhailKasimov** [comment]
@icolab Try again here, please: Python 3 is supported now (See #162 again). Thank you!
