### ISSUE TITLE
Systemd service file

### ISSUE THREAD

**Issue by rgherta** [stamparm/maltrail#18672]
Hi, I did some tests with the following file /usr/lib/systemd/system/maltrail.service 

```
[Unit]
Description=Malicious traffic detection system https://github.com/stamparm/maltrail

[Service]
Type=exec
User=root
WorkingDirectory=/home/localuser/Documents/Security/maltrail
ExecStart=/usr/bin/python3 sensor.py

[Install]
WantedBy=multi-user.target
```

The following commands work well

```
sudo systemctl daemon-reload && sudo systemctl start maltrail && sudo systemctl enable maltrail
```
---------------------------------------------------------------------------
sudo systemctl status maltrail
● maltrail.service - Malicious traffic detection system https://github.com/stamparm/maltrail
     Loaded: loaded (/lib/systemd/system/maltrail.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-11-19 19:18:17 CET; 12min ago
   Main PID: 361674 (python3)
      Tasks: 20 (limit: 18736)
     Memory: 1.6G
        CPU: 1min 17.919s
     CGroup: /system.slice/maltrail.service
             ├─361674 /usr/bin/python3 sensor.py
             ├─361682 /usr/bin/python3 sensor.py
             ├─361684 /usr/bin/python3 sensor.py
             ├─361686 /usr/bin/python3 sensor.py
             ├─361688 /usr/bin/python3 sensor.py
             ├─361690 /usr/bin/python3 sensor.py
             ├─361692 /usr/bin/python3 sensor.py
             └─361694 /usr/bin/python3 sensor.py

Nov 19 19:18:20 roman-hp-g8 python3[361674]: [*] starting @ 19:18:17 /2021-11-19/
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [i] using configuration file '/home/roman/Documents/Security/maltrail/maltrail.conf'
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [i] using '/var/log/maltrail' for log storage
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [i] using '/root/.maltrail/trails.csv' for trail storage (last modification: 'Thu, 18 Nov 2021 23:54:>
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [i] loading trails...
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [i] 677,192 trails loaded
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [?] in case of any problems with packet capture on virtual interface 'any', please put all monitoring>
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [i] opening interface 'any'
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [i] setting capture filter 'udp or icmp or (tcp and (tcp[tcpflags] == tcp-syn or port 80 or port 1080>
Nov 19 19:18:20 roman-hp-g8 python3[361674]: [i] preparing capture buffer...

--------------------------------------------------------------------

However the **systemctl stop** command is hanging although the python process dissapears

I had to add in the [Service] section of the file

KillSignal=SIGKILL
SendSIGKILL=yes

but in this case the process shutdown is not graceful

Can someone confirm the same? Is the python process forking or not?

**Comment by MikhailKasimov** [comment]
Hello!

Try this variation of systemd-based realization: https://malwareandmore.blogspot.com/2016/09/maltrail-setup-and-systemd-integration.html

Does this variation work OK on your side? Thank you!

**Comment by rgherta** [comment]
nope, still hanging... Let me read carefully and come back later on maybe after I try on another vm.

**Comment by rgherta** [comment]
So I manually killed successfully the process with 

`sudo kill -15 <PID>`

It killed the parent and all the 8 children.

systemctl stop should send sigterm according to the docs
https://www.freedesktop.org/software/systemd/man/systemd.kill.html#

I was able to gracefully stop the process only with 
KillMode=mixed

From the docs

> KillMode=¶
> Specifies how processes of this unit shall be killed. One of control-group, mixed, process, none.
> 
> If set to control-group, all remaining processes in the control group of this unit will be killed on unit stop (for services: after the stop command is executed, as configured with ExecStop=). If set to mixed, the SIGTERM signal (see below) is sent to the main process while the subsequent SIGKILL signal (see below) is sent to all remaining processes of the unit's control group. If set to process, only the main process itself is killed (not recommended!). If set to none, no process is killed (strongly recommended against!). In this case, only the stop command will be executed on unit stop, but no process will be killed otherwise. Processes remaining alive after stop are left in their control group and the control group continues to exist after stop unless empty.
> 
> Note that it is not recommended to set KillMode= to process or even none, as this allows processes to escape the service manager's lifecycle and resource management, and to remain running even while their service is considered stopped and is assumed to not consume any resources.
> 
> Processes will first be terminated via SIGTERM (unless the signal to send is changed via KillSignal= or RestartKillSignal=). Optionally, this is immediately followed by a SIGHUP (if enabled with SendSIGHUP=). If processes still remain after the main process of a unit has exited or the delay configured via the TimeoutStopSec= has passed, the termination request is repeated with the SIGKILL signal or the signal specified via FinalKillSignal= (unless this is disabled via the SendSIGKILL= option). See kill(2) for more information.
> 
> Defaults to control-group.
