### ISSUE TITLE
[Feature request] tsusen->maltrail integration

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#187]
Hello!

Here is an idea of ```tsusen```->```maltrail``` integration.

**Goal**: to have access to ```tsusen``` statistics via ```maltrail``` console directly as an alternative of manual typing ```http://tsusen-ip-address:8339``` in browser. Convenience for lazy admins, yes. :laughing: 

**Deal**:

In ```maltrail.conf``` to have parameter:

```
# Tsusen Network Traffic Sensor address
#TSUSEN_ADDRESS 192.168.0.1:8339

```
By default ``` #TSUSEN_ADDRESS``` is OFF. ```tsusen``` tab on ```maltrail``` panel is NOT displayed.

No need to put ```tsusen``` authentication parameters because ```tsusen``` doesn't use them.

In case of ``` TSUSEN_ADDRESS 192.168.0.1:8339``` is ON,  ```tsusen``` tab on ```maltrail``` panel is displayed.

And there are two sub-cases:

1) ```tsusen``` is being inactive and/or unreachable.

 ```tsusen``` tab on ```maltrail``` panel is displayed with ```offline```indicator.

![maltrail-tsusen-integration_1](https://user-images.githubusercontent.com/7167300/40075857-176dc088-5886-11e8-8910-d9209c259ac2.png)

```tsusen``` statistics are NOT accessible.

2) ```tsusen``` is being active and/or reachable.

```tsusen``` tab on ```maltrail``` panel is displayed with ```online```indicator.

![maltrail-tsusen-integration](https://user-images.githubusercontent.com/7167300/40075921-3ec61126-5886-11e8-8c33-e0c139484c0d.png)

```tsusen``` statistics are accessible.

```tsusen``` tab design is lame, of course, here, but is OK just to show the conception entirely.

APPENDIX: What is ```tsusen```: https://github.com/stamparm/tsusen

Please, consider! Thanks!

**Comment by MikhailKasimov** [comment]
https://twitter.com/sofytu6_7/status/1252180718270255104

**Comment by stamparm** [comment]
tsusen sadly didn't caught/stick by the community. Thus, I don't see a point in its integration as we speak
