### ISSUE TITLE
Is It Possible to Run Maltrail on Windows?

### ISSUE THREAD

**Issue by spaceman5** [stamparm/maltrail#19035]
Hi all

Is It Possible to Run Maltrail on Windows?

The Github page does not mention Windows,
but one video on Youtube shows it running on Windows..

I hope anyone can clarify this..

Thank you

**Comment by MikhailKasimov** [comment]
Hello!

```Is It Possible to Run Maltrail on Windows?``` <-- Theoretically, yes. But, as far as I remember, it is not easy to run it correctly.

```but one video on Youtube shows it running on Windows..``` <-- Please, put a link on this video.

**Comment by spaceman5** [comment]
Hi Mikhail

Thank you very much for your reply.

>Please, put a link on this video
Sure:
https://www.youtube.com/watch?v=eF_ZUNtyYHs

**Comment by MikhailKasimov** [comment]
> > Please, put a link on this video
> 
> Sure: https://www.youtube.com/watch?v=eF_ZUNtyYHs

Thank you!

```Is It Possible to Run Maltrail on Windows? <-- Theoretically, yes. But, as far as I remember, it is not easy to run it correctly.``` <-- I have reminded the reason we dropped attempts to port MT on Windows platform: https://github.com/stamparm/maltrail/issues/16408

**Comment by spaceman5** [comment]
Oh, I understand.

It makes me wonder.
Wireshark runs well on Windows, and uses the Packet Capturing library.
Couldn't this use wha Wireshark uses, and thus avoid any problems?

**Comment by MikhailKasimov** [comment]
I think, reason is in ``` Now, after downloading and installing 3rd Microsoft Package, I have to download 2GB of Visual C++ build tools to install pcapy (via pip).``` <-- to generate, for example, some NSIS-installer for 5,6MB Maltrail with ~100500GB of external libs and packages... Personally, it is doubtable pleasure...

**Comment by spaceman5** [comment]
I understand.
But my idea might circumvent it..
If Wireshark uses winpcap, without all this mess,
then assume a Windows machine, with Wireshark installed and working,
(meaning winpcap is there and working well too),
then wouldn't that simplify the dependencies needed?
(and thus save the installer mess too)
