### ISSUE TITLE
False positive `dr49lng3n1n2s.cloudfront.net` in the Blacklist

### ISSUE THREAD

**Issue by PeterDaveHello** [stamparm/maltrail#19047]
`dr49lng3n1n2s.cloudfront.net` is in the Blacklist https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt mentioned here: https://github.com/stamparm/maltrail#blacklist

Blocking `dr49lng3n1n2s.cloudfront.net` actually makes `aws.amazon.com` & `aws.amazon.com.cdn.amazon.com` blocked, looks false positive?

```
aws.amazon.com.cdn.amazon.com	canonical name = dr49lng3n1n2s.cloudfront.net.
```

```
aws.amazon.com	canonical name = tp.8e49140c2-frontier.amazon.com.
tp.8e49140c2-frontier.amazon.com	canonical name = dr49lng3n1n2s.cloudfront.net
```

Take a look at `misc/whitelist.txt` and I found `cloudfront.net` there:
https://github.com/stamparm/maltrail/blob/master/misc/whitelist.txt#L52

Anything that I can do to help? Thanks!

**Comment by stamparm** [comment]
thx. removed

**Comment by PeterDaveHello** [comment]
@stamparm thanks! May I also ask if making the entire CloudFront domain whitelisted sounds reasonable to you? Just wondering how to prevent the same false positive again 😄

**Comment by PeterDaveHello** [comment]
It's interesting that the domain was added for about two months: https://github.com/stamparm/maltrail/commit/79cc94a08038f68a8261f238d44a3a207c7cc531

And I didn't find out the relationship between the CloudFront domain with the references added 😅

**Comment by stamparm** [comment]
well, whitelisting the whole domain would be problematic because some malicious/malware programs use "cloud" fronting to hide the real C&C (e.g. https://bigb0ss.medium.com/redteam-c2-redirector-cloud-fronting-setup-aws-e7ed561a3a6c)

![1](https://user-images.githubusercontent.com/921555/152832462-326b5261-ea83-4458-a9e3-1c49430dcc5f.png)

**Comment by MikhailKasimov** [comment]
@PeterDaveHello 

> It's interesting that the domain was added for about two months: [79cc94a](https://github.com/stamparm/maltrail/commit/79cc94a08038f68a8261f238d44a3a207c7cc531)
> 
> And I didn't find out the relationship between the CloudFront domain with the references added 😅

Relashionship: 
![image](https://user-images.githubusercontent.com/7167300/152838486-39889d22-0d56-48d2-90ea-9fd2d2825aef.png)

> May I also ask if making the entire CloudFront domain whitelisted sounds reasonable to you? Just wondering how to prevent the same false positive again 

No way: https://twitter.com/drb_ra/status/1490697536591613952

This all doesn't cancel my thankyou-words for pointing FP out.

**Comment by PeterDaveHello** [comment]
I got an idea that may be able to help mitigate this situation: to cross reference AlienVault OTX and SecurityTrails, but not so sure it'll really be helpful here, because that may also add some additional loading to modify the process.

The reason why to suggest it is that I did two checks before opening this issue, and these checks seemed verified my guess, giving me the confidence that this could be a false positive.

1. From the info on AlienVault OTX, this domain seems to be popular, the certificate info also looks good, and has been whitelisted already in the past (from passive DNS records):

https://otx.alienvault.com/indicator/domain/dr49lng3n1n2s.cloudfront.net

![image](https://user-images.githubusercontent.com/3691490/152846932-7b076a93-0388-4eba-890f-f26db69f01d8.png)

![image](https://user-images.githubusercontent.com/3691490/152847048-ddb548b4-1460-4c52-b8a1-2b34d587374b.png)

2. From SecurityTrails we can see that two domains are in the record to point to `dr49lng3n1n2s.cloudfront.net`, that's `tp.8e49140c2-frontier.amazon.com` & `aws.amazon.com.cdn.amazon.com`, and `aws.amazon.com` points to `tp.8e49140c2-frontier.amazon.com`, so this domain seems to be very important(I know it may depend on if you're using AWS) and looks like an FP:

https://securitytrails.com/domain/tp.8e49140c2-frontier.amazon.com/dns
https://securitytrails.com/domain/dr49lng3n1n2s.cloudfront.net/dns

![image](https://user-images.githubusercontent.com/3691490/152847305-7dbe3190-60f2-4292-84c3-6291e4b4a790.png)

Both of AlienVault OTX and SecurityTrails has their API, though I'm not familiar with it, just want to share the process to verify my thoughts of the FP before opening the issue 😄

**Comment by MikhailKasimov** [comment]
To make all this resolved and not to forget, that this domain is clean\whitelisted, I put it to whitelist too explicitly: https://github.com/stamparm/maltrail/commit/83dd4d8085665ec13ca640d3fb850dce3def04c8 

This should be OK to prevent occasional FPs in future with this domain.

**Comment by PeterDaveHello** [comment]
Cool, hope they won't change it easily!

**Comment by PeterDaveHello** [comment]
@MikhailKasimov will this be reasonable to whitelist the whole CNAME chain behind those important domains? I believe that many of the most popular and important websites use CDN(sometimes, even more than one CDN provider) and usually have a CNAME chain that may be not so short(may depend on the geolocation), which can also lead us to this similar FP case(totally no offense).

**Comment by MikhailKasimov** [comment]
> BWT, do you think it's possible that traversing the chain of CNAME behind the most famous/popular domains is a possible method to prevent false positives?

How much time should it take by such chain-checker?

**Comment by stamparm** [comment]
@PeterDaveHello there will be no over-engineering here. there is no silver bullet for false-positives. if you take number of commits/domains, i would say that the frequency of FPs in Maltrail is quite low.

nonetheless, from now on we'll have some automated checks to prevent similar occurrences
