### ISSUE TITLE
[Improvement] maltrail currently flagging its own request to ipnoise.now.im

### ISSUE THREAD

**Issue by BernhardHH** [stamparm/maltrail#19044]
I have been digging around what is causing a particuliar medium maltrail threat in our system:

![image](https://user-images.githubusercontent.com/20403145/150931016-0c6be068-b826-4460-974b-db893fb6e0d9.png)

and it turns out, it's maltrail itself, fetching some blacklist.txt file

Maybe it would make sense to flag this somehow?

**Comment by stamparm** [comment]
hi. this is whitelisted for long time. also, that same domain is not used for (again) long time. thus, i would suggest you to update the Maltrail to latest revision and restart the sensor

**Comment by MikhailKasimov** [comment]
@mimugmail FYI

**Comment by mimugmail** [comment]
was this inside a static trail? The current version is 0.37, was this already removed there? 
If not, maybe I need to add a button to drop the trail folder and resync again.

**Comment by mimugmail** [comment]
So this will get updated with 21.7.8 then. I think you can close this one
