### ISSUE TITLE
Can't Running sensor.py

### ISSUE THREAD

**Issue by risyadfahlevi** [stamparm/maltrail#19052]
when i trying to run sensor.py with this command " python3 sensor.py"

this error appear.

-------------------------------------------------------------------
[*] starting @ 16:37:37 /2022-03-16/

[i] using configuration file '/mnt/c/Users/Mr. Nobody/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[i] using '/root/.maltrail/trails.csv' for trail storage (last modification: 'Wed, 16 Mar 2022 09:34:19 GMT')
[i] loading trails...
[i] 650,619 trails loaded
[?] in case of any problems with packet capture on virtual interface 'any', please put all monitoring interfaces to promiscuous mode manually (e.g. 'sudo ifconfig eth0 promisc')
[i] opening interface 'any'
[!] unhandled exception occurred ('any: socket: Address family not supported by protocol')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "/mnt/c/Users/Mr. Nobody/maltrail/sensor.py", line 1277, in <module>
    main()
  File "/mnt/c/Users/Mr. Nobody/maltrail/sensor.py", line 1264, in main
    init()
  File "/mnt/c/Users/Mr. Nobody/maltrail/sensor.py", line 975, in init
    _caps.append(pcapy.open_live(interface, SNAP_LEN, True, CAPTURE_TIMEOUT))
pcapy.PcapError: any: socket: Address family not supported by protocol
'
---

[*] ending @ 16:37:40 /2022-03-16/

-------------------------------------------------------------

**Comment by stamparm** [comment]
basically, this piece of code here https://github.com/stamparm/maltrail/blob/master/sensor.py#L961-L966 is checking if you have a "virtual" interface `any` available in your system. in your case, your system/pcapy says that there is one, but now it seems that it is not supported for usage.

to solve your problem, please edit your `maltrail.conf` and replace `MONITOR_INTERFACE any` with a list of interfaces that you want to do the monitoring (e.g. `MONITOR_INTERFACE eth0, eth1`)

**Comment by risyadfahlevi** [comment]
after i change with another interface (eth0 & eth2) this message is appear,

--------------------------------

[*] starting @ 09:50:13 /2022-03-17/

[i] using configuration file '/mnt/c/Users/Mr. Nobody/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage

[i] using '/root/.maltrail/trails.csv' for trail storage (last modification: 'Wed, 16 Mar 2022 09:34:19 GMT')
[i] loading trails...
[i] 650,619 trails loaded
[i] opening interface 'eth2'
[!] unhandled exception occurred ('eth2: socket: Address family not supported by protocol')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "/mnt/c/Users/Mr. Nobody/maltrail/sensor.py", line 1277, in <module>
    main()
  File "/mnt/c/Users/Mr. Nobody/maltrail/sensor.py", line 1264, in main
    init()
  File "/mnt/c/Users/Mr. Nobody/maltrail/sensor.py", line 975, in init
    _caps.append(pcapy.open_live(interface, SNAP_LEN, True, CAPTURE_TIMEOUT))
pcapy.PcapError: eth2: socket: Address family not supported by protocol
'
--------------------------------------------------------

What should i do ?

**Comment by stamparm** [comment]
sorry man. i can't help you. it seems that something is messed with your network adapters. by googling for `"Address family not supported by protocol"` there is no definite answer on what is going on

**Comment by MikhailKasimov** [comment]
> Address family not supported by protocol

Hello!

Does this happen on PapPi on your side? If yes, I was to find this topic: https://stackoverflow.com/questions/16153804/tornado-socket-error-on-arm out. 

Probably, this is related to your case. Thank you!
