### ISSUE TITLE
MalTrail Services running in OpnSense, but no IDS detections

### ISSUE THREAD

**Issue by hksolutions** [stamparm/maltrail#19056]
Dear,

I have 4 OpnSense boxes. 
3 Original Appliances and 1 VM with OpnSense.

All of them running Maltrail since a week. 
But after +-2-3 days, there is no detection anymore.
The service is running, I can also stop/restart the service, but it still wont work.

when I reboot the appliance, it works again for 2-3 days

I've updated the appliances to the latest software.
What can I do? I can't reboot the device every 2 days...

![No detection](https://user-images.githubusercontent.com/58289437/159655765-b623fd9f-89c0-40c1-998a-124c1d38fd6d.png)
![Services](https://user-images.githubusercontent.com/58289437/159655787-c3f669a3-a20c-4b9b-929e-6b25d3fc2607.png)

**Comment by MikhailKasimov** [comment]
@mimugmail @juliocbc Could you, please, recheck this case on your side? Thank you!

**Comment by stamparm** [comment]
Seems to be a copy (result) of https://github.com/stamparm/maltrail/issues/16710#issuecomment-1070848173

**Comment by hksolutions** [comment]
So just turning off the 'Capture All' mode. will do the trick 👍

**Comment by hksolutions** [comment]
Indeed, the IDS is working again after disabling the 'capture all' option and service restart. 👍

**Comment by MikhailKasimov** [comment]
I do REALLY hope, that inertia of FreeBSD guys in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260732 will get its end after all and all this OOM nightmare with its "artefacts" will go in limbo...

**Comment by juliocbc** [comment]
> 

@MikhailKasimov 

I will try to reproduce it in a lab here and let you know.

@hksolutions 

Could you please tell us the OPNsense version?

**Comment by hksolutions** [comment]
Mine is: 
OPNsense 22.1.2_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by juliocbc** [comment]
As the OPNsense requires to be updated to the latest version, I will be testing on OPNsense 22.1.4_1-amd64

**Comment by juliocbc** [comment]
Confirmed, it stops working after 2/3 days. Even killing the processes doesn't solve the issue.

**Comment by MikhailKasimov** [comment]
> Confirmed, it stops working after 2/3 days. Even killing the processes doesn't solve the issue.

OK, thank you for tests! Again, as said, I do REALLY hope, that inertia of FreeBSD guys in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260732 will get its end after all and all this OOM nightmare with its "artefacts" will finally go in limbo...

**Comment by MikhailKasimov** [comment]
Hello! Because 22.1.5 is already released (although I do not see any mention of ```py-pcapy-ng``` in release notes list -- https://forum.opnsense.org/index.php?topic=27832.0), please, re-check this problem and give a feedback how it works now. Thank you!

**Comment by MikhailKasimov** [comment]
@hksolutions @juliocbc Has anybody re-check how is MT-plugin going after 22.1.5 with py-pcapy-ny 1.0.7 is up? Works OK or still no IDS detections after 2-3 days along? Thank you!

**Comment by SgtDornan8** [comment]
> @hksolutions @juliocbc Has anybody re-check how is MT-plugin going after 22.1.5 with py-pcapy-ny 1.0.7 is up? Works OK or still no IDS detections after 2-3 days along? Thank you!

In version 22.1.6 with py-pcapy-ny 1.0.7 everything has been stable for several days. Hope the memory leak is fixed

**Comment by SgtDornan8** [comment]
Almost 2 months of stable work. The memory leak problem is gone.
