### ISSUE TITLE
Separate cloud & service providers' IP from `cdn_ranges.txt`?

### ISSUE THREAD

**Issue by PeterDaveHello** [stamparm/maltrail#19068]
Looks like IP addresses of cloud and service providers are currently mixed with CDN IP ranges, for example:

- Azure
https://github.com/stamparm/maltrail/blob/c8dfff256da29cb6a0291d59cfd109e1029796a1/misc/cdn_ranges.txt#L141-L231

- Facebook
https://github.com/stamparm/maltrail/blob/c8dfff256da29cb6a0291d59cfd109e1029796a1/misc/cdn_ranges.txt#L342-L379

- OpenX
https://github.com/stamparm/maltrail/blob/c8dfff256da29cb6a0291d59cfd109e1029796a1/misc/cdn_ranges.txt#L381-L383

Not sure if you'd consider separating them into another file, so that `cdn_ranges.txt` can be more specific, or this file is actually recording cloud IP addresses, rather than just CDN? Thanks!

**Comment by stamparm** [comment]
parking is not something of huge importance to Maltrail.

if you want to contribute, maybe you could take a dig into some new malware related trails

**Comment by PeterDaveHello** [comment]
> parking is not something of huge importance to Maltrail.
> 
> if you want to contribute, maybe you could take a dig into some new malware related trails

Sure, but this issue is not about parking, right?

**Comment by stamparm** [comment]
ok, thought about that other issue you've raised. parking nor CDN ranges are not of huge importance to Maltrail. they are useful and help in preventing FPs, but malware trails are the real gold in Maltrail

**Comment by PeterDaveHello** [comment]
Agree, please forgive me that I am still learning to find some gold, and trying to find some useful copper in the meanwhile 😅

**Comment by MikhailKasimov** [comment]
The best type of gold here: malicious network activity, that MT doesn't currently detect: domains, IP:port combinations, full-path URLs, etc.
