### ISSUE TITLE
Any way of testing to see it has been configured correctly and is working?

### ISSUE THREAD

**Issue by thefunkygibbon** [stamparm/maltrail#19079]
Would be good if there was some page that has threats known to be picked up by maltrails sensors i could browse to to make sure its working as i've been running for a few days and have nothing in the logs (i get that this is a good thing, but it is also a bad thing if its not actually working correctly)

**Comment by MikhailKasimov** [comment]
Hello!

For checking FPs (false positive) Maltrail has a) internal checks, b) user's reports. If FP occures, we try to fix it ASAP.

If your configure Sensor and Server parameters in ```maltrail.conf``` the best way to if everything OK is -- to run manual tests:

1)
```
ping -c 1 136.161.101.53
cat /var/log/maltrail/$(date +"%Y-%m-%d").log
```

2)
```
nslookup morphed.ru
cat /var/log/maltrail/$(date +"%Y-%m-%d").log
```

If everything is OK, MT Server should successfully recieve events from MT Sensor.

![Screenshot_184](https://user-images.githubusercontent.com/7167300/164993933-c1aac11a-9077-4bee-ab02-dc5c7c987a8e.png)

If you meet something (domain, IP:port, etc), that is related to malicious network traffic, you can put an issue (https://github.com/stamparm/maltrail/issues) of patch (https://github.com/stamparm/maltrail/pulls).

If you look for some online-page, there's no one.

**Comment by thefunkygibbon** [comment]
great stuff, thank you
