### ISSUE TITLE
Route home network devices traffic through maltrail on Raspberry 

### ISSUE THREAD

**Issue by CarloCattano** [stamparm/maltrail#19084]
I've configured maltrail and tested that it works with the ping command from my raspberry terminal.

Now I would love to redirect some of my devices manually through the pi , kind of how pihole does this.
Could not find instructions in the how-to or wiki.
I assume is a very simple task and excuse me for my ignorance on the topic.

Its such a nice tool I would love to learn to set it up to protect devices in my network

**Comment by MikhailKasimov** [comment]
Hello!

Looks like you need to set your Raspberry as the inline gateway/nexthop for your home network.

PC ------> RaspPI ------> your-home-router/nat------> Internet

or

PC ------> RaspPI is your-home-router/nat------> Internet

Try out this tutorial: https://www.seeedstudio.com/blog/2021/06/11/how-to-build-a-raspberry-pi-router-step-by-step-tutorial/

**Comment by CarloCattano** [comment]
Thanks!
So I assume it's not possible to use like pi-hole just creating an AP from a wifi adapter😔
Consider the issue closed perhaps, was more a question than an issue.
Thanks for your work and for the hint
