### ISSUE TITLE
problem send logs SENSOR --> SERVER (SUPPORT)

### ISSUE THREAD

**Issue by conexioninversa** [stamparm/maltrail#19087]
Hi all,
I intend to install sensors against a single maltrail server.
It doesn't work for me and I have the following configuration on a node (sensor):

![sensor3](https://user-images.githubusercontent.com/29124284/170033322-b1ef3b88-7783-4300-800b-b2dca66ae9c9.PNG)

I have UDP ports enabled on the server

![server](https://user-images.githubusercontent.com/29124284/170033243-81767e87-a263-4b58-a6ce-131a3f4a8a3e.PNG)

What can make it not work?
Thank you very much

**Comment by conexioninversa** [comment]
Hi MikhailKasimov
I have reviewed the documentation that you have indicated and I have also reviewed the configuration but I still do not see the events on the server.
I pass the log of the server and later of the sensor to see if there is something strange.

The server has the IP 192.168.1.1 and the sensor 192.168.1.2

[server.txt](https://github.com/stamparm/maltrail/files/8770358/server.txt)
[sensor.txt](https://github.com/stamparm/maltrail/files/8770357/sensor.txt)

thank you very much for the support

**Comment by MikhailKasimov** [comment]
Hello!

Two variants: everything is OK in your conf or I'm blind and unable to see the mistake... :( But, in fact, everything should work OK. Have tried to restart  ```/server.py``` and ```/sensor.py``` scripts on 192.168.1.1 and 192.168.1.2 respectively?

**Comment by MikhailKasimov** [comment]
UPD:

![image](https://user-images.githubusercontent.com/7167300/170284830-a809111f-d4d5-4f9e-8db8-2213b1f1458e.png)

**Comment by MikhailKasimov** [comment]
Yes, here is a limitation, that only one parameter line can be in game.
