### ISSUE TITLE
Cant open maltrail web access from another pc

### ISSUE THREAD

**Issue by risyadfahlevi** [stamparm/maltrail#19082]
I want to ask why I can't access the web server from another pc by only accessing the local ip of the maltrail server. Is there something I missed ? Is there a setting so that the maltrail server can be accessed using a local ip?

in maltrail.conf I have changed the file on the first line

"Listen address of (reporting) HTTP server
HTTP_ADDRESS 0.0.0.0" > _Replace with my own local ip_

but still can't, please help, thank you.

**Comment by MikhailKasimov** [comment]
Hello!

1) ![image](https://user-images.githubusercontent.com/7167300/168035699-40a36099-95df-4a49-8fc5-055c76b4005f.png)

2) Have restarted ```/server.py``` and even ```/sensor.py```.

3) Result 
![image](https://user-images.githubusercontent.com/7167300/168035929-edd7015a-137a-4d5b-8b28-b6dc4450b93e.png)


Everything OK is. Please, check your network settings.

**Comment by risyadfahlevi** [comment]
> Hello!
> 
> 1. ![image](https://user-images.githubusercontent.com/7167300/168035699-40a36099-95df-4a49-8fc5-055c76b4005f.png)
> 2. Have restarted `/server.py` and even `/sensor.py`.
> 3. Result
>    ![image](https://user-images.githubusercontent.com/7167300/168035929-edd7015a-137a-4d5b-8b28-b6dc4450b93e.png)
> 
> Everything OK is. Please, check your network settings.

Hello thank you for answering my question

i did it exactly like this before but still can't. is there any other way ?
BTW here's my maltrail.conf
# [Server]

# Listen address of (reporting) HTTP server
HTTP_ADDRESS 0.0.0.0
#HTTP_ADDRESS ::
#HTTP_ADDRESS fe80::12c3:7bff:fe6d:cf9b%eno1

# Listen port of (reporting) HTTP server
HTTP_PORT 8338

# Use SSL/TLS
USE_SSL false

# SSL/TLS (private/cert) PEM file (e.g. openssl req -new -x509 -keyout server.pem -out server.pem -days 1023 -nodes)
#SSL_PEM misc/server.pem

# User entries (username:sha256(password):UID:filter_netmask(s))
# Note(s): sha256(password) can be generated on Linux with: echo -n 'password' | sha256sum | cut -d " " -f 1
#          UID >= 1000 have only rights to display results (Note: this moment only functionality implemented at the client side)
#          filter_netmask(s) is/are used to filter results
USERS
    admin:9ab3cd9d67bf49d01f6a2e33d0bd9bc804ddbe6ce1ff5d219c42624851db5dbc:0:                        # changeme!
#    local:9ab3cd9d67bf49d01f6a2e33d0bd9bc804ddbe6ce1ff5d219c42624851db5dbc:1000:192.168.0.0/16       # changeme!

# Mask custom trail names for non-admin users (UID >= 1000)
ENABLE_MASK_CUSTOM true

# Listen address of (log collecting) UDP server
#UDP_ADDRESS 0.0.0.0
#UDP_ADDRESS ::
#UDP_ADDRESS fe80::12c3:7bff:fe6d:cf9b%eno1

# Listen port of (log collecting) UDP server
#UDP_PORT 8337

# Should server do the trail updates too (to support UPDATE_SERVER directive in [Sensor] parameters)
USE_SERVER_UPDATE_TRAILS false

# Aliases used in client's web browser interface to describe the src_ip and/or dst_ip column entries
#IP_ALIASES
#    8.8.8.8:google
#    8.8.4.4:google

# Option to change the top-left logo with a custom image/text
#HEADER_LOGO <img src="https://i.imgur.com/JxYJ5yX.png" style="width: 26px"> XYZ

# Regular expression to be used in external /fail2ban calls for extraction of attacker source IPs
FAIL2BAN_REGEX attacker|reputation|potential[^"]*(web scan|directory traversal|injection|remote code)|spammer|mass scanner

# [Sensor]

# Number of processes
PROCESS_COUNT $CPU_CORES

# Disable setting of CPU affinity (with schedtool) on Linux machines (e.g. because of load issues with other processes)
DISABLE_CPU_AFFINITY false

# Use feeds (too) in trail updates
USE_FEED_UPDATES true

# Disable (retrieval from) specified feeds (Note: respective .py files inside /trails/feeds; turris and ciarmy/cinsscore seem to be too "noisy" lately; policeman is old and produces lots of false positives)
DISABLED_FEEDS turris, ciarmy, policeman, myip, alienvault

# Ignore IPs that appear on lower than IP_MINIMUM_FEEDS number of feeds (Note: static IP trails are always included)
IP_MINIMUM_FEEDS 3

# Disable trails based on the following regular expression run against the corresponding info
#DISABLED_TRAILS_INFO_REGEX known attacker|tor exit node

# Update trails after every given period (seconds)
UPDATE_PERIOD 86400

# Use remote custom feed (too) in trail updates
#CUSTOM_TRAILS_URL http://www.test.com/custom.txt

# Location of directory with custom trails (*.txt) files
CUSTOM_TRAILS_DIR ./trails/custom

# (Max.) size of multiprocessing network capture ring buffer (in bytes or percentage of total physical memory) used by sensor (e.g. 512MB)
CAPTURE_BUFFER 10%

# Interface used for monitoring (e.g. eth0, eth1)
MONITOR_INTERFACE enp1s0f2

# Network capture filter (e.g. ip)
# Note(s): more info about filters can be found at: https://danielmiessler.com/study/tcpdump/
#CAPTURE_FILTER ip or ip6
CAPTURE_FILTER udp or icmp or (tcp and (tcp[tcpflags] == tcp-syn or port 80 or port 1080 or port 3128 or port 8000 or port 8080 or port 8118))

# Sensor name to appear in produced logs
SENSOR_NAME $HOSTNAME

# Remote Maltrail server instance to send log entries (Note: listening at <UDP_ADDRESS>:<UDP_PORT>)
#LOG_SERVER 192.168.2.107:8337
#LOG_SERVER [fe80::12c3:7bff:fe6d:cf9b%eno1]:8337

# Remote address to send Syslog events
#SYSLOG_SERVER 192.168.2.107:514

# Remote address to send JSON events (e.g. Logstash)
#LOGSTASH_SERVER 192.168.2.107:5000

# Regular expression used for calculating severity attribute when sending events to SYSLOG_SERVER or LOGSTASH_SERVER
REMOTE_SEVERITY_REGEX (?P<high>(remote )?custom\)|malwaredomainlist|malware(?! (distribution|site))|adversary|ransomware)|(?P<medium>potential malware site|malware distribution)|(?P<low>mass scanner|reputation|attacker|spammer|compromised|crawler|scanning)

# Set only (!) in cases when LOG_SERVER should be exclusively used for log storage
DISABLE_LOCAL_LOG_STORAGE false

# Remote address for pulling (latest) trail definitions (e.g. http://192.168.2.107:8338/trails). USE_SERVER_UPDATE_TRAILS directive should be active in [Server] parameters.
#UPDATE_SERVER http://192.168.2.107:8338/trails

# Use heuristic methods
USE_HEURISTICS true

# Capture HTTP requests with missing Host header (introducing potential false positives)
CHECK_MISSING_HOST false

# Check values in Host header (along with standard non-HTTP checks) for malicious DNS trails (introducing greater number of events)
CHECK_HOST_DOMAINS false

# Location of file with whitelisted entries (i.e. IP addresses, domain names, etc.) (note: take a look into 'misc/whitelist.txt')
#USER_WHITELIST

# Location of file with ignore event rules. Example under misc/ignore_events.txt
#USER_IGNORELIST misc/ignore_events.txt

# Regular expression to be used against the whole event entry to be ignored
#IGNORE_EVENTS_REGEX sql injection|long domain|117.21.225.3|sinkhole

# [All]

# Show debug messages (in console output)
SHOW_DEBUG false

# Directory used for log storage
LOG_DIR $SYSTEM_LOG_DIR/maltrail

# HTTP(s) proxy address
#PROXY_ADDRESS http://192.168.5.101:8118

# Disable checking of sudo/Administrator privileges (e.g. if using: setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /bin/python)
#DISABLE_CHECK_SUDO true

# Override default location for trail storage (~/.maltrail/trails.csv)
#TRAILS_FILE /etc/maltrail.csv

**Comment by MikhailKasimov** [comment]
Is ```192.168.1.101``` pingable from this "another pc" and back from ```192.168.1.101``` to "another pc"?

**Comment by MikhailKasimov** [comment]
Looking on your config -- everything should work OK... 

What does ```curl http://192.168.1.101:8337``` command return, being run on ```another pc``` ?

**Comment by risyadfahlevi** [comment]
> Looking on your config -- everything should work OK...
> 
> What does `curl http://192.168.1.101:8338` command return, being run on `another pc` ?

the result like this.
curl: (28) Failed to connect to 192.168.1.101 port 8338 after 21047 ms: Timed out

**Comment by MikhailKasimov** [comment]
An closed\filtered ports on firewall? I'm unable to reproduce thr problem because everything is OK on my side:

![image](https://user-images.githubusercontent.com/7167300/168247906-afabd2db-564a-4ee2-9c41-58b1901ddd87.png)

And it is successfully accessable from another subnet, where my laptop is.

**Comment by risyadfahlevi** [comment]
last question, is that possible 1 computer using 2 different port ?

example im using ntop for this pc and also im want to using maltrail in this pc.
maybe thats why i cant open access the web maltrail from another pc.

**Comment by MikhailKasimov** [comment]
> last question, is that possible 1 computer using 2 different port ?

Sure. You can use, e.g. ```ip:8443``` for some service and ```ip:8081``` for another.

> example im using ntop for this pc and also im want to using maltrail in this pc. maybe thats why i cant open access the web maltrail from another pc.

If ntop uses 8337 and 8338 ports for its own work, maltrail won't be accessable by its ```native``` 8338 port, yes.

**Comment by risyadfahlevi** [comment]
it solved i figure it out and just use this command "ufw allow 8338" and i can open web access from another PC with same network.
