### ISSUE TITLE
Problem SENSOR_NAME

### ISSUE THREAD

**Issue by conexioninversa** [stamparm/maltrail#19086]
The first. I am a maltrail fan. Congratulations
I have some problem with sensor name change in sensor_name. When I put a name for example:
SENSOR_NAME $HOST1
When I restart the computer, it does not take the change made and it only appears in the log "localhost"
What can happen?
thank you

**Comment by MikhailKasimov** [comment]
Hello!

https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L91

```SENSOR_NAME $HOSTNAME```

```$HOSTNAME``` means, that name is taken from environment variable ```HOSTNAME``` of the system.

I suppose, you put your hostname (SENSOR_NAME $HOST1) with ```$``` prefix. Try without ```$```: ```SENSOR_NAME HOST1``` and check the work.

**Comment by conexioninversa** [comment]
It still doesn't work.
I have put it like so:
![image](https://user-images.githubusercontent.com/29124284/169806933-c9fc966e-1123-411f-87fd-5e6ad36a47a1.png)
To test I write this:
# **ping -c 1 136.161.101.53**
and **cat /var/log/maltrail/$(date +"%Y-%m-%d").log**
which keeps showing "**localhost**"
![sensor1](https://user-images.githubusercontent.com/29124284/169807385-113c6c75-8494-4678-a098-6bc57eb53305.PNG)

**Comment by conexioninversa** [comment]
Fixed. It's a weird carriage return at the end of the sensor name line. Very rare, but in the end I have eliminated it and it has been solved.
Thank you very much for the help
