### ISSUE TITLE
False positive: koyu.space

### ISSUE THREAD

**Issue by austinhuang0131** [stamparm/maltrail#19085]
Public Mastodon instance by @koyuawsmbrtn, similar to #19048.

Malware scanners have in many times attempt to block Mastodon instances en masse without ever reaching out to site admins.

This is presumably relevant to https://github.com/nextdns/metadata/issues/878 since your list is part of the Threat Intelligence Feed

**Comment by MikhailKasimov** [comment]
In https://github.com/stamparm/maltrail/commit/fd01713a17bac9e609fb687a745114378da87330

**Comment by austinhuang0131** [comment]
Thank you.
