### ISSUE TITLE
Suggestion: Fail2Ban Integration

### ISSUE THREAD

**Issue by Gill-Bates** [stamparm/maltrail#19107]
This One-Liner inside `crontab -e` would simplify the fail2ban integration. If you route the result to `> /dev/null 2>&1`, then you also spare the syslog.

```
# Maltrail IP Check every 5 Min
*/5 * * * * for ip in $(curl http://127.0.0.1:8338/fail2ban 2>/dev/null); do sudo fail2ban-client set maltrail banip $ip > /dev/null 2>&1; done
```

**Comment by MikhailKasimov** [comment]
Hello!

It already exists (screenshot from documentation):

![image](https://user-images.githubusercontent.com/7167300/180745032-031fe620-9c10-4286-94d6-bb5a3a005226.png)

**Comment by Gill-Bates** [comment]
@MikhailKasimov The current solution uses `ipset` and not fail2ban. My suggestion uses  `fail2ban-client set`. There are many advantages for it:

- the Ban of the IP is fully managed by fail2ban
- you can exclude IPs from being banned
- you can use the fail2ban policies (retrys, bantime, etc)

**Comment by stamparm** [comment]
@Gill-Bates that was just a suggestion what to do with that list. you can do whatever you want with it. it just a dumb IP list
