### ISSUE TITLE
no alert on URL trails_type

### ISSUE THREAD

**Issue by ch1sh1rsk1** [stamparm/maltrail#19111]
Hello. Thank you for your awesome tool!!!
Can you explain what types of trails exist? I found DNS and IP and they work good. 

But also I found strings in file https://github.com/stamparm/maltrail/blob/master/trails/static/malicious/c2_panel.txt like this:
/adin/admin.php
/ajjuu/admin.php
/alti/admin.php
...

I think it is TXT type of trails.
I try to test them. I generate traffic like this:
![image](https://user-images.githubusercontent.com/11348001/188080669-680ba519-53fb-465e-a14c-237ea3c2ee7d.png)
![image](https://user-images.githubusercontent.com/11348001/188080797-183e8920-7d9e-4a09-8949-60d2c2093932.png)

And tcpreplay it on promisc interface, which is listened by maltrail-sensor. But there is no alerts in web. Can you help me?

Maybe my config is not good.
I set CHECK_HOST_DOMAINS **true**. But it doesn't help me.

**Comment by ch1sh1rsk1** [comment]
Thank you. My mistake. There wasn't `/server/das/dastdoor.php` in sugnatures and ofcourse in trails.csv. 

One more question. If I enable CHECK_HOST_DOMAINS true - it means that maltrail will catch every request (in header HOST) if malware sends multiple http requests to c2. If it is disabled maltrail will catch only UDP request to DNS-server.

**Comment by MikhailKasimov** [comment]
> Thank you. My mistake. There wasn't `/server/das/dastdoor.php` in sugnatures and ofcourse in trails.csv.

No problem. If this pattern is met for real ITW malware -- please, let me know the name of this malware and some VirusTotal references for samples: it looks to to get added. If it is "self-made" for internal tests, there's no sense to add detection.

> One more question. If I enable CHECK_HOST_DOMAINS true - it means that maltrail will catch every request (in header HOST) if malware sends multiple http requests to c2. If it is disabled maltrail will catch only UDP request to DNS-server.

I never used ```CHECK_HOST_DOMAINS true``` to be honest. Hope, @stamparm will clarify the correct behavior of this parameter.

**Comment by stamparm** [comment]
> 

sorry for waiting. that's correct

**Comment by stamparm** [comment]
@ch1sh1rsk1 sorry for waiting. that's correct

**Comment by ch1sh1rsk1** [comment]
Thank you for answers!
