### ISSUE TITLE
false positive: download[.]windowsupdate[.]com

### ISSUE THREAD

**Issue by elliotwutingfeng** [stamparm/maltrail#19110]
`download[.]windowsupdate[.]com` is a false positive. It is owned by Microsoft.

**Comment by MikhailKasimov** [comment]
Hello!

Facepalm on being blind myself... :(((

Fixed: https://github.com/stamparm/maltrail/commit/c80704eae7437f63eee6d2fa0aa46eda88fec34a
Whitelisted: https://github.com/stamparm/maltrail/commit/e255c50968da2d2d64b8432c233fbe445c53b01d
