### ISSUE TITLE
Add New IP

### ISSUE THREAD

**Issue by MxResearch** [stamparm/maltrail#19118]
I need to add some more IP in the maltrail to detect it 
Can any one help how to add new IP/doamin/URL

**Comment by MikhailKasimov** [comment]
Hello!

You can have your own trails, which should be placed to ```/static/custom/``` folder. After adding such trails you need to restart ```sensor.py```.

If you want to collaborate to add ```IP/domain/URL``` to Maltrail upstream, you can put respective pull request: https://github.com/stamparm/maltrail/pulls

Thank you!

**Comment by MxResearch** [comment]
Custom folder is not present in static .
I added my txt file in both the place  
(/static/custom/1.txt)
(/custom/1.txt)
Is there any specific pattern to keep the IP's.
Project is too good , but there are some issue also we are facing such as 
1> Not able to add new IP's
2> Not able to fetch the logs from network pc

Is any one help me in this

**Comment by MxResearch** [comment]
Thank's for your valuable support 
Actually because of UPDATE_PERIOD in config file i got the issue 
It is easy to add as per your given instruction , just have to decease the time in UPDATE_PERIOD.

I have one more query , if possible kindly help me 
Is it possible to execute the sensor in windows  platform

**Comment by MikhailKasimov** [comment]
> Thank's for your valuable support Actually because of UPDATE_PERIOD in config file i got the issue It is easy to add as per your given instruction , just have to decrease the time in UPDATE_PERIOD.

Good.
 
> I have one more query , if possible kindly help me Is it possible to execute the sensor in windows platform

Theoretically -- yes. Practically -- see https://github.com/stamparm/maltrail/issues/4326 for example.

**Comment by MikhailKasimov** [comment]
@MxResearch Can this issue get closed?
