### ISSUE TITLE
d1zkz3k4cclnv6.cloudfront.net - false positive?

### ISSUE THREAD

**Issue by kopaw** [stamparm/maltrail#19112]
Hi,

this domain points (CNAME) to the tracking-protection.cdn.mozilla.net [1], which I believe is used by Mozilla Firefox tracking protection mechanism. I guess it's been blacklisted due to malware found in the past [2] [3]. However, the current AlienVault OTX verdict is "Whitelisted" [2], so I'm not sure what to think about this. Maybe it should be escalated to the Mozilla team instead?

Sources:
[1] https://securitytrails.com/list/cname/d1zkz3k4cclnv6.cloudfront.net
[2] https://otx.alienvault.com/indicator/hostname/d1zkz3k4cclnv6.cloudfront.net
[3] https://www.virustotal.com/gui/domain/d1zkz3k4cclnv6.cloudfront.net/detection

**Comment by MikhailKasimov** [comment]
Hello!

Looks like different services return different resuts:

![image](https://user-images.githubusercontent.com/7167300/190861961-41eaaf5f-3cb2-4869-a532-cdbd0348b2ac.png)

OK, I currently will switch detection off: https://github.com/stamparm/maltrail/commit/9ba0da25da1b911aeae686825c0f51ec109af280 , but esclating this case to Mozilla team sounds also reasonable. Just to be sure, that this domains is really related to them in fact.

Thank you!

**Comment by kopaw** [comment]
Thanks for the quick response and fix!

Small mistake in the issue description, though. It should be:
"this domain is pointed to (CNAME) by the tracking-protection.cdn.mozilla.net" 
That's why you only get results with the SecurityTrails, because it shows the "reverse" CNAME records.
