### ISSUE TITLE
How to disable round brackets?

### ISSUE THREAD

**Issue by EugeneFenko** [stamparm/maltrail#19116]
Hello team, is it possible to disable the addition of round brackets to the trail?

For example
Now: `(aaa).evil.com`
Expected: `aaa.evil.com`

**Comment by stamparm** [comment]
Hi Eugene.

Sorry, but that's not possible. Currently those round brackets are just there to show the auxilary/misc part of the recognition, while the non-bracketed part shows the actual trail that triggered the detection. Without that, there would be a mess inside the web UI client.

BR
