### ISSUE TITLE
How trails.csv is generate and update?

### ISSUE THREAD

**Issue by EugeneFenko** [stamparm/maltrail#19114]
Hi team, I have a question about the process of updating the `trails.csv` file. Can you tell me exactly how `trails.csv` is generated? 
I tried deleting it, restarting the server and the sensor, but the new file is not generated, and if I create it manually, it remains empty.
A while ago I installed Maltril and everything was fine, but now it seems that this file is not updated according to the `/trails` folder

**Comment by EugeneFenko** [comment]
Ok, I replaced the maltrail.conf configuration file with the new one and the trails.csv generation started happening on startup.  
I also noticed that you need to restart the server regularly to update this file.

**Comment by stamparm** [comment]
https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L70-L71 (<- update should be done every 24h based on default options)
