### ISSUE TITLE
name 'exit' is not defined

### ISSUE THREAD

**Issue by jbakuwel** [stamparm/maltrail#19125]
Hi there,

I'm compiling sensor.py with nuitka3 (`nuitka3 --follow-imports --standalone sensor.py`) so I can distribute a relatively small executable to embedded routers instead of the full Python3 and related dev components.

```
# ./sensor 
Maltrail (sensor) #v0.50 {https://maltrail.github.io}

[*] starting @ 07:15:11 /2022-10-29/

[!] unhandled exception occurred ('name 'exit' is not defined')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "/data/maltrail/sensor.dist/sensor.py", line 1295, in <module>
  File "/data/maltrail/sensor.dist/sensor.py", line 1257, in main
  File "/data/maltrail/sensor.dist/core/settings.py", line 230, in read_config
NameError: name 'exit' is not defined

[*] ending @ 07:15:11 /2022-10-29/
# find . -iname "*.py" -exec grep -l "^def exit" {} \;
# find . -iname "*.py" -exec grep -l "^def" {} \; | wc -l
82
#

```

**Comment by MikhailKasimov** [comment]
@stamparm Please, take a look!

**Comment by MikhailKasimov** [comment]
@jbakuwel Hello! Have you re-checked compilation with the latest revision of Maltrail?

**Comment by jbakuwel** [comment]
@MikhailKasimov Yes, thanks for the super fast response :-). 
I considered submitting a PR but wasn't sure whether an exit function doing a bit more than sys.exit was intended.

**Comment by MikhailKasimov** [comment]
> @MikhailKasimov Yes, thanks for the super fast response :-). I considered submitting a PR but wasn't sure whether an exit function doing a bit more than sys.exit was intended.

Pretty nice! Thank you for feedback and confirmation!

**Comment by MikhailKasimov** [comment]
@jbakuwel  BTW: ```...I can distribute a relatively small executable to embedded routers``` <-- any git(hub/lab) for this project?

**Comment by jbakuwel** [comment]
@MikhailKasimov See above... just a matter of compiling the Python code into an executable with nuitka3

**Comment by MikhailKasimov** [comment]
> @MikhailKasimov See above... just a matter of compiling the Python code into an executable with nuitka3

OK, no problem. Just was an idea, that you're planning to have a dedicated project for embedded routers... :)
