### ISSUE TITLE
How to display IP on web maltrail interface

### ISSUE THREAD

**Issue by MxResearch** [stamparm/maltrail#19120]
If we add some more IP manually , that IP is not display on maltrail web interface 
Is there any way that we can display that IP after adding it

**Comment by MikhailKasimov** [comment]
Hello!

Have you restarted sensor.py after adding IPs?

**Comment by MxResearch** [comment]
Yes 
I observe that after adding the IP and restart the sensor.py  , those new IP will display if again that IP was connected through PC

**Comment by MikhailKasimov** [comment]
Could you, please, attach your trail-files, which contain "problematic" IPs here, if is acceptable? Wanna take a look on its format. Thank you!

**Comment by MxResearch** [comment]
[domains.txt](https://github.com/stamparm/maltrail/files/9733288/domains.txt)
[ip.txt](https://github.com/stamparm/maltrail/files/9733291/ip.txt)

**Comment by MxResearch** [comment]
pls check this

**Comment by MikhailKasimov** [comment]
After re-checking (have put respective IPs and\or domains from your lists into browser address string):
![image](https://user-images.githubusercontent.com/7167300/194564227-25387c35-aa75-49bd-b082-1d1915cf3371.png)

On format: please, meet respective wiki-page: https://github.com/stamparm/maltrail/wiki/Maltrail-trails-base-format

Hope, this works for you. Thank you!

**Comment by MxResearch** [comment]
In my case it will show when again the same ip us connected
Should we have to use same format as describe in the link

**Comment by MikhailKasimov** [comment]
> In my case it will show when again the same ip us connected

Please, attach the screenshot(s) from your side.

> Should we have to use same format as describe in the link

Very desirable.

**Comment by MikhailKasimov** [comment]
@MxResearch  Can this issue get closed?

**Comment by MxResearch** [comment]
Yes , sorry for delay and thanks for support

**Comment by MikhailKasimov** [comment]
Resolved.
