### ISSUE TITLE
the regular expression misses part of the domain name?

### ISSUE THREAD

**Issue by Tianer1123** [stamparm/maltrail#19124]
hello,

in [360bigviktor.py](https://github.com/stamparm/maltrail/blob/master/trails/feeds/360bigviktor.py), the regular expression `(?m)^([\w.]+)\s+2\d{3}\-` missing some domain names. these domains usually contain "`-`", like `buildconfident-draw.info` in the file [https://data.netlab.360.com/feeds/dga/bigviktor.txt](https://data.netlab.360.com/feeds/dga/bigviktor.txt).

Is this a bug or a feature?

**Comment by MikhailKasimov** [comment]
Hello!

If domains are missed, hence it is bug:

![image](https://user-images.githubusercontent.com/7167300/198566600-ea9b2b6f-0abd-40ce-9e0c-53f7760e2720.png)

Fixed variation:

![image](https://user-images.githubusercontent.com/7167300/198566757-68a45e52-a58a-4366-b8e5-74828693bde0.png)

Patch: https://github.com/stamparm/maltrail/commit/4de482c6171fe75f36b7e126fce596fa0cebaff1

Thank you for reporting!

**Comment by Tianer1123** [comment]
All source files that start with **360** (`360xxx.py`)  have the same problem.

I created a PR [595b071](https://github.com/Tianer1123/maltrail/commit/595b0714f298798a27d271dbcaecf615ef450cf7).

**Comment by MikhailKasimov** [comment]
> All source files that start with **360** (`360xxx.py`) have the same problem.

Currently, it is not a problem for other `360xxx.py` feeds, because all domains in respective lists do not contain hyphen sign in their names. But, to prevent situation, that caused with initial ```360bigviktor.py```, spreading detection of hyphen sign looks reasonable.

> I created a PR [595b071](https://github.com/Tianer1123/maltrail/commit/595b0714f298798a27d271dbcaecf615ef450cf7).

OK, thank you!
