### ISSUE TITLE
The provided Docker image is not usable 

### ISSUE THREAD

**Issue by abpostelnicu** [stamparm/maltrail#19121]
The provided docker image hangs on startup dur to some synchronisation issues of the threads and a deadlock occurs. Did someone else encounter this sort of issues?

**Comment by MikhailKasimov** [comment]
Hello!

Please, point details on what environment: OS, network, measurement tools, etc you use for reproducing? And, of course, step-by-step algo of reproducing would nice to have.

Thank you!

**Comment by MikhailKasimov** [comment]
Will try to reproduce a little bit later...

**Comment by MikhailKasimov** [comment]
Have tried with script https://github.com/stamparm/maltrail/blob/master/docker/README.md, adopted a little bit for my openSUSE-instance, and looks like everything is OK to run:

![image](https://user-images.githubusercontent.com/7167300/195855330-624becad-bf68-49bb-8908-0ce2c578f88a.png)

**Comment by MikhailKasimov** [comment]
> I've modified the title and submitted in #19122 a PR for this.

@stamparm Take a look, please.
