### ISSUE TITLE
[Request] Log Pull

### ISSUE THREAD

**Issue by zero77** [stamparm/maltrail#19139]
Can you please add support for log collection instead of alongside the current option to send logs.
As it can make things harder when your server is behind a firewall or on LAN and a client is on a different network or WAN.

This could be achieved by the server collecting logs from a shared directory, as this would allow logs to be collected by scp or rsync from the remote client.

**Comment by MikhailKasimov** [comment]
Hello!

```Can you please add support for log collection instead of alongside the current option to send logs.``` <--
log-pulling parameter: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L33-L34

```As it can make things harder when your server is behind a firewall or on LAN and a client is on a different network or WAN.``` <-- can be resolved via port mapping\forwarding on border firewall: white_IP:8337 -> private_IP:8337.

**Comment by stamparm** [comment]
@zero77 https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L136

**Comment by zero77** [comment]
@MikhailKasimov
Thanks for your comments but, this is what i already do for servers on the same network. I am trying to avoid portforeding to the internet as i have remote servers i would like to collect logs for.

@ stamparm
Thanks, to confirm i can just copy or move logs from remote servers into LOG_DIR on the maltrail server and they will be collected?

**Comment by zero77** [comment]
@stamparm
This looks ideal but, after testing it only seems to collect logs that are in one log file with that days date on.
Is It possible to add a second log directory as subdirectories in the log directory are not collected automatically.
