### ISSUE TITLE
False Positive: Nextcloud Android App User Agent

### ISSUE THREAD

**Issue by Xyaren** [stamparm/maltrail#19137]
```
fef174b2|lx0001|742022-12-22 15:35:09.777943, 15:35, 15:36, 15:37, 15:38, 15:39, 15:40, 15:41, 15:42, 15:43, 15:44, 15:45, 15:46|medium|22nd 15:35:09|22nd 15:46:39||10.80.255.1 ||10.80.255.100 |80 (http)|TCP|UA|xtc |user agent (suspicious)|(heuristic)|:
```

User Agent:
```
Mozilla/5.0 (Android) Nextcloud-android/3.23.0, Mozilla/5.0 (Windows) mirall/3.6.4stable-Win64 (build 20221208) (Nextcloud, windows-10.0.19044 ClientArchitecture: x86_64 OsArchitecture: x86_64)
```

**Comment by MikhailKasimov** [comment]
Hello! Please, try with this fix: https://github.com/stamparm/maltrail/commit/ec93364f4c6ef48f2a6dfa3862ef61bbdd954e12

**Comment by Xyaren** [comment]
No fix unfortunately

**Comment by MikhailKasimov** [comment]
Strange, because should be OK:
![image](https://user-images.githubusercontent.com/7167300/210118089-cc104642-11b0-4f49-aac5-a75c7cf36133.png)

**Comment by Xyaren** [comment]
![image](https://user-images.githubusercontent.com/5864045/210119154-7a1403a4-c949-4090-a9d9-cb6d7d62aad7.png)
I updated yesterday, so this should be fixed right ?

**Comment by MikhailKasimov** [comment]
> ![image](https://user-images.githubusercontent.com/5864045/210119154-7a1403a4-c949-4090-a9d9-cb6d7d62aad7.png) I updated yesterday, so this should be fixed right ?

Wanna take a small pause for some experiments how to avoid detection for Nextcloud, but saving ```xtc``` as a sign of malicious traffic...

**Comment by MikhailKasimov** [comment]
Try with this update: https://github.com/stamparm/maltrail/commit/0f1f3b11d2327fa5b3dfcedbd7daf6e8ff165cb0

**Comment by MikhailKasimov** [comment]
Or even so: https://github.com/stamparm/maltrail/commit/15baa777a76ff371c0a8c8405240131614a5b70a

**Comment by MikhailKasimov** [comment]
```curl -A Nextcloud <address>```
```curl -A Nexlocud-android <address>```

do not return detection. Considering as fixed as last.
