### ISSUE TITLE
[SOURCE] IP BlackHole.Monster

### ISSUE THREAD

**Issue by BlackHoleMonster** [stamparm/maltrail#19149]
Hello,
idk if you want it, but have for now 4 servers that catch the IPs (e.g. ssh brutes). Thanks!

https://github.com/BlackHoleMonster/IP-BlackHole

🚫 ALL IPs:
https://ip.blackhole.monster/blackhole

🚫 TODAY IPs:
https://ip.blackhole.monster/blackhole-today

**Comment by MikhailKasimov** [comment]
@stamparm Ideas?

**Comment by stamparm** [comment]
done

**Comment by BlackHoleMonster** [comment]
Cool thx!

**Comment by hbednar** [comment]
Can this be whitelisted as it's getting detected as suspicious:

![monster](https://user-images.githubusercontent.com/71215137/236867937-21d22f04-f90c-4fa9-b008-9b7951eaa120.png)

**Comment by hbednar** [comment]
> > Can this be whitelisted as it's getting detected as suspicious:
> > ![monster](https://user-images.githubusercontent.com/71215137/236867937-21d22f04-f90c-4fa9-b008-9b7951eaa120.png)
> 
> Done: [dfbc845](https://github.com/stamparm/maltrail/commit/dfbc845cf9b1afa6745c9e118c6b5424f8475886)

@MikhailKasimov 
Thanks

**Comment by BlackHoleMonster** [comment]
Please update to the new domain:
https://blackhole.s-e-r-v-e-r.pw/
:)

**Comment by BlackHoleMonster** [comment]
Forgot to renew domain and i had this one already so i can sub-domain my other projects, and also too little money in pocket :D

**Comment by MikhailKasimov** [comment]
> Forgot to renew domain and i had this one already so i can sub-domain my other projects too, and also too little money in pocket.

OK, got that. Thank you!

**Comment by BlackHoleMonster** [comment]
Got original domain back :)
Please update thanks.

https://github.com/BlackHoleMonster/IP-BlackHole/commit/6dd16e96bb3c851c0f3e2c1e32262c9d4b857ec2

🚫 ALL IPs:
https://blackhole.monster/blackhole

🚫 TODAY IPs:
https://blackhole.monster/blackhole-today

🚫 15-DAYS IPs:
https://blackhole.monster/blackhole-15days

🚫 30-DAYS IPs:
https://blackhole.monster/blackhole-30days

**Comment by MikhailKasimov** [comment]
Done: https://github.com/stamparm/maltrail/commit/e466d9405be31067b5bc9e7386c99e47b254f6c7

Hope, it is the last "grass-hopping" on feed. Thank you!
