### ISSUE TITLE
[False Positive] myip.ms

### ISSUE THREAD

**Issue by hbednar** [stamparm/maltrail#19159]
myip.ms is used as one of the trails but, its mistakenly being detected as suspicious:

![2023-06](https://github.com/stamparm/maltrail/assets/71215137/80084891-c66e-4557-950a-99112d180a6b)

**Comment by MikhailKasimov** [comment]
Hello!

Not a FP itself. Use ```#USER_WHITELIST``` variable of ```/maltrail.conf``` file to suppress detection on your side: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L121-L122

**Comment by hbednar** [comment]
> Hello!
> 
> Not a FP itself. Use `#USER_WHITELIST` variable of `/maltrail.conf` file to suppress detection on your side: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L121-L122

I am using the whitelist.txt but, i can't see it listed:

https://github.com/stamparm/maltrail/blob/master/misc/whitelist.txt

**Comment by MikhailKasimov** [comment]
> > Hello!
> > Not a FP itself. Use `#USER_WHITELIST` variable of `/maltrail.conf` file to suppress detection on your side: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L121-L122
> 
> I am using the whitelist.txt but, i can't see it listed:
> 
> https://github.com/stamparm/maltrail/blob/master/misc/whitelist.txt

It is general whitelist. ```#USER_WHITELIST``` variable allows to use your own whitelist simultaneously to general whitelist.

Create some text file, e.g. ```/opt/maltrail/misc/my-whitelist.txt```, place ```myip.ms``` into it, save ```/opt/maltrail/misc/my-whitelist.txt```, initiate ```#USER_WHITELIST``` variable to be like: ```USER_WHITELIST /opt/maltrail/misc/my-whitelist.txt```, then restart MT's ```sensor.py```.

**Comment by hbednar** [comment]
@MikhailKasimov 
Would you accept a pull request for this

**Comment by hbednar** [comment]
I understand the reason for not whitelisting ip info services but, as this one is a trail should it be an exception.

**Comment by stamparm** [comment]
`ipinfo` domain requests are suspicious by default (extensively used by malware). you'll get other similar suspicious events too. suspicious doesn't mean malicious. you'll have to just ignore it if you are certain of its validity

**Comment by hbednar** [comment]
@stamparm 
It makes sense to report ip info services as suspicious.

Is there a way to not monitor trail updates as it means you have to either ignore these events or whitelist them and both options mean you would miss something that should be investigated.

**Comment by stamparm** [comment]
i see what you mean. will comment it out as it makes that problem (haven't realized till now)

**Comment by hbednar** [comment]
Thanks @stamparm 
Another option might be to just ignore `/opt/maltrail/core/update.py` as that may be the simplest way to stop this happening again with other trails that are picked up as suspicious.
