### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by mskf3000** [stamparm/maltrail#19160]
docker build -t maltrail . && \
    docker run -d --name maltrail-docker --privileged -p 8337:8337 -p 8338:8338 -v /var/log/maltrail/:/var/log/maltrail/ maltrail

 
---> Running in 13149f6526be
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'

**Comment by MikhailKasimov** [comment]
Hello!

You sure it is Maltrail issue instead of DNS?

**Comment by stamparm** [comment]
seems like DNS issue

**Comment by MikhailKasimov** [comment]
@mskf3000 Hello! Is this ticket could be closed, if there's no other questions?

**Comment by MikhailKasimov** [comment]
Considering as resolved by not a Maltrail-related issue.
