### ISSUE TITLE
how do i add a user agent

### ISSUE THREAD

**Issue by fullfill13** [stamparm/maltrail#19194]
Hello！
    I think a type of user agent is a malicious type, how can I modify the trails so that maltrail can recognize this malicious behavior

**Comment by MikhailKasimov** [comment]
Hello!

Please, meet ```/ua.txt``` file in ```maltrail/misc``` folder:

![image](https://github.com/stamparm/maltrail/assets/7167300/a009d226-38ea-479a-b1e4-c3f969d25189).

Modify it on your own side and add user agent detection, then restart ```/sensor.py```. If you would like to share detection to Maltrail upstream, please, put pull request.

Thank you!

**Comment by MikhailKasimov** [comment]
Also, please, take a time to read these wiki-articles:

[1] https://github.com/stamparm/maltrail/wiki/Maltrail-trails-structure
[2] https://github.com/stamparm/maltrail/wiki/Maltrail-trails-base-format
[3] https://github.com/stamparm/maltrail/wiki/Maltrail-trails-contribution

**Comment by MikhailKasimov** [comment]
@fullfill13 While silence is rolling up, could you, please, citate here entire string of user-agent you wanna to be detected?

**Comment by fullfill13** [comment]
Thank you, just Windows Installer.

**Comment by MikhailKasimov** [comment]
Considering as resolved
