### ISSUE TITLE
[BUG] No results from Trail searx mouse over 

### ISSUE THREAD

**Issue by emsofo** [stamparm/maltrail#19199]
**Describe the bug**
Great stuff!! Just installed on a virtual instance of OPNSense 23.7.1_3 and seems to work except for one thing - when hovering over the Trail section - the searx results always say: "Sorry! we didn't find any results. Please use another query or search in more categories." - so seems broken ?!?.

**How To Reproduce**
1. Go to HTTP GUI
2. Hover mouse over "Trail" IP and wait for pop up box - which shows no results

**Expected behavior**
As described in the User Guide - expected proper search results

**Screenshots**
![image](https://github.com/stamparm/maltrail/assets/107464168/235207c0-1744-4249-bd12-078a2d425fb4)

**Environment:**
 - Device: Proxmox based OPNSense instance 23.7.1_3 running latest plugin version
 - OS: BSD
 - OPNSense Plugin
 - Problematic Maltrail component: web-interface
 - Maltrail version: v0.59

**Comment by mimugmail** [comment]
No, this comes from mailtrail itself.
If the contents are read from file (which I dont know) maybe we can check if its there

**Comment by MikhailKasimov** [comment]
> No, this comes from mailtrail itself. If the contents are read from file (which I dont know) maybe we can check if its there

OK, thanks. Will try to play with it today in evening...

**Comment by emsofo** [comment]
As far as I can see - the hover over function calls up a serach website called "searx" and tries to perform a lookup on that IP address from the Trail - seems like the searx website doesn't function right or the api call from maltrail is wrong?!?

**Comment by MikhailKasimov** [comment]
Looks like the deal is not in Maltrail itself, but ```searx.nixnet.services``` only.

E.g. (just to compare):

https://searx.nixnet.services/search?q=8.8.8.8
https://searx.nixnet.services/search?q=91.195.240.94

**Comment by emsofo** [comment]
> Looks like the deal is not in Maltrail itself, but `searx.nixnet.services` only.
> 
> E.g. (just to compare):
> 
> https://searx.nixnet.services/search?q=8.8.8.8 https://searx.nixnet.services/search?q=91.195.240.94

Agreed - so they have to find another backend search mechanism, because that feature is broken

**Comment by stamparm** [comment]
p.s. it should be fixed for the moment. hard to find working searx server (or similar search engine) which allows showing of in-frame query results
