### ISSUE TITLE
docker server

### ISSUE THREAD

**Issue by Chelito4** [stamparm/maltrail#19203]
Hello, I have had problems when starting the maltrail server. I am using docker and when I configure the server tab, adjusting UDP_PORT 8337 and UDP_ADDRESS 10.14.20.60 and it returns an error when starting the server Attaching to maltrail-sensor-1, maltrail-server-1
maltrail-server-1 exited with code 0

**Comment by MikhailKasimov** [comment]
Closed as dup of #19202
