### ISSUE TITLE
[Questions and Support] Maltrail docker environment

### ISSUE THREAD

**Issue by Chelito4** [stamparm/maltrail#19201]
There is not much information regarding the docker environment I already have the maltrail in a container but it does not record the traffic of the sites please help me

**Comment by MikhailKasimov** [comment]
Hello!

Not clear, which sites you use\test for Maltrail's detection. Please, describe your problem more detailed. Thank you!

**Comment by Chelito4** [comment]
I have other computer equipment and I would like to add them to my maltrail server, could this be done?

**Comment by MikhailKasimov** [comment]
> I have other computer equipment and I would like to add them to my maltrail server, could this be done?

https://github.com/stamparm/maltrail/wiki/Miscellaneous#2-setting-up-centralized-maltrail-server-log-collector-for-multi-sensor-maltrail-installation

**Comment by Chelito4** [comment]
> > I have other computer equipment and I would like to add them to my maltrail server, could this be done?
> 
> https://github.com/stamparm/maltrail/wiki/Miscellaneous#2-setting-up-centralized-maltrail-server-log-collector-for-multi-sensor-maltrail-installation

It already works, thanks, another question, can you add alma linux servers, centos rhel to maltrail?

**Comment by MikhailKasimov** [comment]
> > > I have other computer equipment and I would like to add them to my maltrail server, could this be done?
> > 
> > 
> > https://github.com/stamparm/maltrail/wiki/Miscellaneous#2-setting-up-centralized-maltrail-server-log-collector-for-multi-sensor-maltrail-installation
> 
> It already works, thanks, another question, can you add alma linux servers, centos rhel to maltrail?

Take a look on this topic: https://github.com/stamparm/maltrail/issues/19072

Also there are Maltrail RPM-packages for various RPM-based Linux distros: https://build.opensuse.org/package/show/home:k_mikhail/maltrail

Currently down, reason: https://lists.opensuse.org/archives/list/project@lists.opensuse.org/thread/6K7XWWXNLVESDYOKRUKKCII5L3B4R3NH/). But soon should be OK again.

**Comment by MikhailKasimov** [comment]
> > > > I have other computer equipment and I would like to add them to my maltrail server, could this be done?
> > > 
> > > 
> > > https://github.com/stamparm/maltrail/wiki/Miscellaneous#2-setting-up-centralized-maltrail-server-log-collector-for-multi-sensor-maltrail-installation
> > 
> > 
> > It already works, thanks, another question, can you add alma linux servers, centos rhel to maltrail?
> 
> Take a look on this topic: #19072
> 
> Also there are Maltrail RPM-packages for various RPM-based Linux distros: https://build.opensuse.org/package/show/home:k_mikhail/maltrail
> 
> Currently down, reason: https://lists.opensuse.org/archives/list/project@lists.opensuse.org/thread/6K7XWWXNLVESDYOKRUKKCII5L3B4R3NH/). But soon should be OK again.

https://build.opensuse.org/ is online again for now. Please, visit https://build.opensuse.org/package/show/home:k_mikhail/maltrail

**Comment by Chelito4** [comment]
Thank you so much, I really appreciate your help. Kind regards!

**Comment by MikhailKasimov** [comment]
Glad to help you! Any questions -- welcome! Have a nice week-end!

**Comment by Chelito4** [comment]
Hello, I have had problems when starting the maltrail server. I am using docker and when I configure the server tab, adjusting UDP_PORT 8337 and UDP_ADDRESS 10.14.20.60 and it returns an error when starting the server Attaching to maltrail-sensor-1, maltrail-server-1
maltrail-server-1 exited with code 0
