### ISSUE TITLE
How to add severity to local logs?

### ISSUE THREAD

**Issue by andyoulovexy** [stamparm/maltrail#19223]
![图片](https://github.com/stamparm/maltrail/assets/38940994/4af520f0-1c77-404c-b10b-d7e9f5946152)

**Comment by MikhailKasimov** [comment]
> ![图片](https://user-images.githubusercontent.com/38940994/282765427-4af520f0-1c77-404c-b10b-d7e9f5946152.png)

Currently, no way. Need for @stamparm assistance here.

**Comment by andyoulovexy** [comment]
> > ![图片](https://user-images.githubusercontent.com/38940994/282765427-4af520f0-1c77-404c-b10b-d7e9f5946152.png)
> 
> Currently, no way. Need for @stamparm assistance here.

I need to analysis local log ,include severity field is very import,thanks

**Comment by stamparm** [comment]
currently there is no way how to do it. severity logic is done inside the web UI, not in sensor logs. that was done from start so everybody could adapt severity (of logs) to their needs
