### ISSUE TITLE
api:how to curl maltrail info

### ISSUE THREAD

**Issue by andyoulovexy** [stamparm/maltrail#19222]
I want to curl severity and so on?how to get it in commandline?
![图片](https://github.com/stamparm/maltrail/assets/38940994/3dd1e23e-cb16-4a24-a9d9-0be7ccf4d364)

**Comment by MikhailKasimov** [comment]
Hello! You want to pass maltrail info to some external log-collector, right?

**Comment by andyoulovexy** [comment]
> Hello! You want to pass maltrail info to some external log-collector, right?

I just want to get severity ,src_ip,src_port info and so on by comandline

**Comment by MikhailKasimov** [comment]
Something like ```curl -X POST <link> -H "severity" -H "src_ip" ... - H "what is needed"```

**Comment by andyoulovexy** [comment]
> Something like `curl -X POST <link> -H "severity" -H "src_ip" ... - H "what is needed"`
Yes

**Comment by stamparm** [comment]
duplicate of #19223
