### ISSUE TITLE
Custom image

### ISSUE THREAD

**Issue by Chelito4** [stamparm/maltrail#19231]
Good morning, just to ask if there is any way to add a custom image to the maltrail server. I see that there is a way that calls an image from the web. My question is if there is a way to take the image from the same server.

**Comment by MikhailKasimov** [comment]
Hello!

You mean this image?

![image](https://github.com/stamparm/maltrail/assets/7167300/fde5dcdc-a17a-4c83-ab7c-534628df39ec)

**Comment by Chelito4** [comment]
Yes, it could be customized ?

**Comment by MikhailKasimov** [comment]
Yes, by manual modication of ```/httpd.py``` code.

**Comment by Chelito4** [comment]
I appreciate your attention, it already works for me, thank you very much for the support, greetings

**Comment by MikhailKasimov** [comment]
Closing as resolved successfully.
