### ISSUE TITLE
External IP Flagged in Blocklist in Maltrail and Appears to also be affecting blocks on other sites...

### ISSUE THREAD

**Issue by secdoc** [stamparm/maltrail#19249]
**Question**
For some reason Maltrail is blocking my external IP See below:

![maltrail](https://github.com/stamparm/maltrail/assets/55542561/aaa610bb-0bc1-4862-ab53-8ef699ab12bf)

I have added an allow rule within the firewall above the maltrail block, so I am able to get exetrnal access now, but when I have gone to other sites, it appears my IP is still flagged for some reason. most appear to be associated with DNS for some reason as seen in the image...

**Support**
Any thoughts on what would cause this or why it is getting flagged?

**Comment by MikhailKasimov** [comment]
Hello!

Maltrail doesn't block connections itself, it is just IDS. It can be set up to work together with block mechanism (https://github.com/stamparm/maltrail/wiki/Miscellaneous#1-setting-up-maltrail-as-an-intrusion-prevention-system-ips), but I think your case is not related.

Also have re-chehcked your IP in static trails for FP -- also clear. What environment do you use for Maltrail? Is it a plugin in OPNSense?

**Comment by stamparm** [comment]
is `99.137.X.Y` your external IP? if yes, that means that Maltrail detected your IP as a source of suspicious behavior - and that's perfectly normal. in such case you should inspect why are there such requests and if there is a need to be worry of

**Comment by stamparm** [comment]
p.s. from what i can see, those are most probably benign (but marked as "suspicious" by Maltrail - not meaning "malicious")

**Comment by secdoc** [comment]
> Hello!
> 
> Maltrail doesn't block connections itself, it is just IDS. It can be set up to work together with block mechanism (https://github.com/stamparm/maltrail/wiki/Miscellaneous#1-setting-up-maltrail-as-an-intrusion-prevention-system-ips), but I think your case is not related.
> 
> Also have re-chehcked your IP in static trails for FP -- also clear. What environment do you use for Maltrail? Is it a plugin in OPNSense?

Yes, This is an OPNsense plugin. I have the following configuration  **ISP <===| OPNsense (Transparent FW) |===> Unifi UDM** with IP Passthrough from ISP. This was not an issue previously, but started getting dropped, via the Maltrail ACL on OPNsense. My question is around why I am getting tagged. I do not see a clear answer. I run internal unbound DNS with Pihole for my DNS request, so not sure why or how I am being flagged there either. I do host services internall and use cloudflare DNS/reverse proxy for access again that has been that way for some time.

**Comment by secdoc** [comment]
> p.s. from what i can see, those are most probably benign (but marked as "suspicious" by Maltrail - not meaning "malicious")
Yes that is my external IP. I realize that it is showing as suspicious but trying to understand the Trails References for the items...

**Comment by MikhailKasimov** [comment]
> > Hello!
> > Maltrail doesn't block connections itself, it is just IDS. It can be set up to work together with block mechanism (https://github.com/stamparm/maltrail/wiki/Miscellaneous#1-setting-up-maltrail-as-an-intrusion-prevention-system-ips), but I think your case is not related.
> > Also have re-chehcked your IP in static trails for FP -- also clear. What environment do you use for Maltrail? Is it a plugin in OPNSense?
> 
> Yes, This is an OPNsense plugin. I have the following configuration **ISP <===| OPNsense (Transparent FW) |===> Unifi UDM** with IP Passthrough from ISP. This was not an issue previously, but started getting dropped, via the Maltrail ACL on OPNsense. My question is around why I am getting tagged. I do not see a clear answer. I run internal unbound DNS with Pihole for my DNS request, so not sure why or how I am being flagged there either. I do host services internall and use cloudflare DNS/reverse proxy for access again that has been that way for some time.

@mimugmail Hello! Could you, please, attend to our conversation? Need details how OPNSense firewall builds its blocking rules due to Maltrail's detections. Thank you!

**Comment by secdoc** [comment]
> > > Hello!
> > > Maltrail doesn't block connections itself, it is just IDS. It can be set up to work together with block mechanism (https://github.com/stamparm/maltrail/wiki/Miscellaneous#1-setting-up-maltrail-as-an-intrusion-prevention-system-ips), but I think your case is not related.
> > > Also have re-chehcked your IP in static trails for FP -- also clear. What environment do you use for Maltrail? Is it a plugin in OPNSense?
> > 
> > 
> > Yes, This is an OPNsense plugin. I have the following configuration **ISP <===| OPNsense (Transparent FW) |===> Unifi UDM** with IP Passthrough from ISP. This was not an issue previously, but started getting dropped, via the Maltrail ACL on OPNsense. My question is around why I am getting tagged. I do not see a clear answer. I run internal unbound DNS with Pihole for my DNS request, so not sure why or how I am being flagged there either. I do host services internall and use cloudflare DNS/reverse proxy for access again that has been that way for some time.
> 
> @mimugmail Hello! Could you, please, attend to our conversation? Need details how OPNSense firewall builds its blocking rules due to Maltrail's detections. Thank you!


This is my two cents on what I know on the blocks, there is an alias created that is associated with the fail2ban item and then an ACL on the interface.
![maltrail_alias](https://github.com/stamparm/maltrail/assets/55542561/1365f25e-dc01-4967-b0c9-5784ac7ba193)
![maltrail_acl](https://github.com/stamparm/maltrail/assets/55542561/71c36aeb-a5ef-4ac8-9e8c-92b791ccb239)

**Comment by mimugmail** [comment]
Exactly, opnsense fetches the fail2ban url at Regularien intervall and builds an dynamic alias

**Comment by MikhailKasimov** [comment]
Would suspect, that's the reason of blocking:

![image](https://github.com/stamparm/maltrail/assets/7167300/88de200f-8624-475e-a2d9-242d6f816a9e)

See ```FAIL2BAN_REGEX``` triggers list: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L48

**Comment by secdoc** [comment]
> Exactly, opnsense fetches the fail2ban url at Regularien intervall and builds an dynamic alias

How do you exclude (allowlist) explicit IPs or domains because I have placed the IP in the config but not bypassing:
![maltrail_general](https://github.com/stamparm/maltrail/assets/55542561/5b5ddb08-37e3-4227-8ea0-d97ad02bcd27)

**Comment by MikhailKasimov** [comment]
Due to CHANGELOG: MT from 0.65 version (https://github.com/stamparm/maltrail/blob/master/CHANGELOG#L43) has possibility to build custom blacklists (https://github.com/stamparm/maltrail/pull/19230):

![image](https://github.com/stamparm/maltrail/assets/7167300/5c5011b8-a487-48fc-b670-0856f648a2e7). Looks like this mechanism allows to build bypass rule for defined filter (e.g. mass_scanner due to current case).


but not sure it is implemented in OPNSense plugin, in particular, in UI. @mimugmail ?

**Comment by secdoc** [comment]
> Due to CHANGELOG: MT from 0.65 version (https://github.com/stamparm/maltrail/blob/master/CHANGELOG#L43) has possibility to build custom blacklists (#19230):
> 
> ![image](https://private-user-images.githubusercontent.com/7167300/320971996-5c5011b8-a487-48fc-b670-0856f648a2e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTcyMTYsIm5iZiI6MTcxMjcxNjkxNiwicGF0aCI6Ii83MTY3MzAwLzMyMDk3MTk5Ni01YzUwMTFiOC1hNDg3LTQ4ZmMtYjY3MC0wODU2ZjY0OGEyZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMDI0MTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBmOWMzNTJjMTIwNDA0YjI3MTkxMTY2MzBjNmIwNmFlNTk2NzczNzM3OGU5NTg2YzY2YjBjNDcyMTVmYjk5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rSdQKRbYz6pxkIk9gmyIyNpAYqypbmv-pDZAeySh3sk). Looks like this mechanism allows to build bypass rule for defined filter (e.g. mass_scanner due to current case).
> 
> but not sure it is implemented in OPNSense plugin, in particular, in UI. @mimugmail ?

Is the plugin maintained by OPNsense then or is that part of the Maltrail project?

**Comment by MikhailKasimov** [comment]
> Is the plugin maintained by OPNsense then or is that part of the Maltrail project?

Plugin is maintained by OPNsense.

**Comment by secdoc** [comment]
> > Is the plugin maintained by OPNsense then or is that part of the Maltrail project?
> 
> Plugin is maintained by OPNsense.

Thanks

**Comment by secdoc** [comment]
> > > > Is the plugin maintained by OPNsense then or is that part of the Maltrail project?
> > > 
> > > 
> > > Plugin is maintained by OPNsense.
> > 
> > 
> > Thanks
> 
> As the workaround I can propose to manually modify `/maltrail.conf` file by deleting string `mass_scanner` (see https://github.com/opnsense/plugins/blob/master/security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf#L11) and restart the MT plugin. Hope, this will OK for you.

No I do not think that is the right direction...If OPNsense maintains the plugin (thought is was handled by maltrail like other OPNsense plugins) , they should try to resolve, especially since I shoudl be whitelisted from the console perspective within OPNsense. Removing the `mass_scanner` is definitely good info for monitoring, which I do.

**Comment by secdoc** [comment]
@MikhailKasimov on a side note, has there been a change in the way the `known_attacker` is handled? This may be another OPNsense related issue, but since I have gone to explicit FW to transparent FW, the known_attacker hits have completely disappeared, where I was averaging a few dozen a day previously.

**Comment by MikhailKasimov** [comment]
> on a side note, has there been a change in the way the `known_attacker` is handled?

As far I remember, there were no changes.

But, what I can see, when comparing "native" ```/maltrail.conf``` (https://github.com/stamparm/maltrail/blob/master/maltrail.conf) and OPNSense's one (https://github.com/opnsense/plugins/blob/master/security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf), OPNSense one does not contain the option ```DISABLED_TRAILS_INFO_REGEX``` (https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L72-L73), which allows to supress "noisy" detections like ```known attacker```.

Perhaps, @mimugmail would give a more thoughtful hint here...

**Comment by secdoc** [comment]
This is just an update to this issue. After applying the OPNsense 24.7.3 update today, the Maltrail traffic patterns that were expected returned. So not sure if part of the issue was associated with the delta and/or changes between 24.7.2, but now seeing the visibility previously ...

![image](https://github.com/user-attachments/assets/bd2493b4-0093-4375-ba79-98b221cb19bd)

**Comment by MikhailKasimov** [comment]
This is just one more confirmation, that Maltrail works OK itself. The deal was in its environment. Thank you for letting know!
