### ISSUE TITLE
[Questions and Support] The server.py does not raise if I define an ip in UDP_ADDRESS

### ISSUE THREAD

**Issue by gabrielbasetti** [stamparm/maltrail#19246]
**Question**
The server.py does not raise if I define an ip in UDP_ADDRESS

**Support**
Hi folks, I'm trying to configure maltrail with the docker image to have multiple sensors sending data to a maltrail server (docker too).
Following the guide at https://github.com/stamparm/maltrail/wiki/Miscellaneous, I can't get it to work.
I have observed the following:
1. server.py throws on /var/log/maltrail/error.log
```
[!] session abruptly terminated
[?] (hint: "https://stackoverflow.com/a/20997655")
```
2. Other issues commenting on the same thing, but none of them mention the solution and yet they have been closed:: [19201](https://github.com/stamparm/maltrail/issues/19201) [19202](https://github.com/stamparm/maltrail/issues/19202)

3. From the remote sensor, communication with the server is effective:
![image](https://github.com/stamparm/maltrail/assets/39503933/619c0f60-62a4-469f-926d-9f952ba541fb)

**Comment by MikhailKasimov** [comment]
@Chelito4 Hello! Please, take a look on point 2. You've mentioned in https://github.com/stamparm/maltrail/issues/19202#issuecomment-1696014369 , that solved, Please, put a hint how it was solved. Thank you!

**Comment by Chelito4** [comment]
> @Chelito4 Hello! Please, take a look on point 2. You've mentioned in [#19202 (comment)](https://github.com/stamparm/maltrail/issues/19202#issuecomment-1696014369) , that solved, Please, put a hint how it was solved. Thank you!

Hi Mikhail i solved it by installing as an maltrail as application not in a container.

**Comment by stamparm** [comment]
@gabrielbasetti you are most probably running it wrong. please post your "Dockerfile" here

also, I don't see what does the `UDP_ADDRESS` have to do with that error. have you tried to run your maltrail configuration file (with maltrail) outside of the Docker container?

in https://github.com/stamparm/maltrail/issues/19202, guy said "I solved", so I guess that in your case you should try to properly configure environment too? We have zero useful information here

p.s.:
![image](https://github.com/stamparm/maltrail/assets/921555/4d6f8b4e-0c65-47fa-a6cd-d1bf02d20209)

you can try the following:

instead of (https://github.com/stamparm/maltrail/blob/master/sensor.py#L1305-L1307):

```
    except IOError:
        log_error("\n\n[!] session abruptly terminated\n[?] (hint: \"https://stackoverflow.com/a/20997655\")")
        code = 1
```

use

```
    except IOError as err:
        log_error("\n\n[!] session abruptly terminated\n[?] (%s)" % err)
        code = 1
```

**Comment by gabrielbasetti** [comment]
Thank you very much for your help.
I have found the problem.
I was trying to configure the multi-sensor feature with containers and was blaming docker and NAT, but the problem was that the container where the server is, was not receiving information on udp port 8337
The command to run the container does not expose port 8337 correctly, as it should be UDP and not TCP.

`docker run -d --name maltrail-docker --privileged -p 8337:8337/udp -p 8338:8338 -v /var/log/maltrail/:/var/log/maltrail/ maltrail
`
![image](https://github.com/stamparm/maltrail/assets/39503933/bb2149e6-8d37-4306-b303-f75e73cd4fb8)

**Comment by MikhailKasimov** [comment]
> The command to run the container does not expose port 8337 correctly, as it should be UDP and not TCP.

https://github.com/stamparm/maltrail/commit/437fd5da349f15eafe157fd2600b04c5385b4d8f
