### ISSUE TITLE
[BUG] cruzit URL changed

### ISSUE THREAD

**Issue by mbrother2** [stamparm/maltrail#19253]
**Describe the bug**
cruzit has changed URL list from https://www.cruzit.com/xxwbl2txt.php to https://www.cruzit.com/xxwbl2txt1.php

Please update!

**Comment by MikhailKasimov** [comment]
Fixed in https://github.com/stamparm/maltrail/commit/3a8eaa863831300ab3035c4db91f54925f75a43f . Thank you for letting know!
