### ISSUE TITLE
Bad domains

### ISSUE THREAD

**Issue by jjwrolstad** [stamparm/maltrail#19259]
**Describe the bug**
The source  https://www.cyberresilience.com/threatonomics/resilience-threat-researchers-identify-new-campaigns-from-scattered-spider/

These domains should not be present: powerdms.com, polaris.me, docusign.net

**How To Reproduce**
Link: https://github.com/stamparm/maltrail/blob/master/trails/static/malware/0ktapus.txt

**Expected behavior**

**Screenshots**

**Environment:**
 - Device: [e.g. Linux-based device, OPNSense plugin]
 - OS: [Linux, *BSD]
 - Type of Maltrail installation: [e.g. ```git clone``` command]
 - Problematic Maltrail component: [e.g. server, sensor, web-interface]
 - Maltrail version: [e.g. 0.59]
 - ```python-pcapy-ng``` version: [e.g. 1.0.9]

**Additional context**

**Comment by MikhailKasimov** [comment]
Hello!

Fixed: https://github.com/stamparm/maltrail/commit/916ce06a90227a0f3ab4629aa101417effcc0b47

**Comment by MikhailKasimov** [comment]
Considering as resolved.
