### ISSUE TITLE
[Questions and Support] Suspicious Domain High False Positive

### ISSUE THREAD

**Issue by zero77** [stamparm/maltrail#19271]
**Question**
I am getting a very high false positive for suspicious domains in particular domains ending in xyz, cc, ws

Is there any way i can disable suspicious domain detection for multiple clients

Looking through the trails it seems to be coming from the top part of this file which detects all domains ending with certain terms:

https://raw.githubusercontent.com/stamparm/maltrail/9dcfd0a4c0402feeae25ee00a288cf0d04840ce4/trails/static/suspicious/domain.txt

**Support**

**Comment by MikhailKasimov** [comment]
Hello!

Try this option to use: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L132-L133

**Comment by MikhailKasimov** [comment]
> Could the top part of the domain.txt be separated into a different file. So people can decide if they want to keep it as it's very broad and leads to false positives.

No problem to use different file iwth respective format: https://github.com/stamparm/maltrail/wiki/Maltrail-trails-base-format and use it as user-defined whitelist (https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L126-L127).

**Comment by MikhailKasimov** [comment]
The second way (more global): is just to put ```#``` sign in front of domain you want to exclude. E.g. ```.cc``` --> ```# .cc```, save ```/domain.txt``` file and restart the ```/sensor.py```. Downside of this method: you potentially can miss real malware/malicious connections to ```.cc```-based domains.

**Comment by MikhailKasimov** [comment]
> Thanks for the suggestions, if i commented out .cc i would still detect known malicious cc domains right ?

Known would stay detected.

**Comment by MikhailKasimov** [comment]
@zero77 Hello! Is the problem resolved?

**Comment by stamparm** [comment]
you are the first one that claims that usage of TLDs like `.cc, .su, .tt, .ws, .xyz, .pw, .tk, .cf, .gq, .icu` is not suspicious.

**personally** i haven't seen too much valid usage of those domains, where i've seen lots and lots of malware/scam sites using those

there is not documentation for usage of `IGNORE_EVENTS_REGEX`. i though that it is self-described here: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L132-L133. i mean, if you can list those domains you find "non-suspicious" into a regex, you'll be ok

one more thing. putting `IGNORE_EVENTS_REGEX=suspicious` will remove all those "suspicious" events, which you do not find as suspicious, from all future events
