### ISSUE TITLE
[Questions and Support] DNS queries type 28 (AAAA)

### ISSUE THREAD

**Issue by JSteegmueller** [stamparm/maltrail#19277]
**Question**
Hey @stamparm, just a small question:
Why are DNS quieries with type 28 filtered out in this line?

https://github.com/stamparm/maltrail/blob/f0bc2e97186d9ce06f49e3863bc0023414486727/sensor.py#L738

Shouldn't AAAA requesters also be analyzed regarding suspicious domain names?

Thanks for your time!
Greetings, Janik

**Comment by stamparm** [comment]
@JSteegmueller took one example of such DNS request(s) from here: https://www.cloudshark.org/captures/ea72fbab241b?filter=frame%20and%20eth%20and%20ip%20and%20udp. It seems that everything should be good for Maltrail to parse those AAAA records, but...

AFAIR, this was the main issue:
![image](https://github.com/user-attachments/assets/80bbfd54-4c78-4017-bd36-3d3b28ae2339)

Currently I am not anymore in the network traffic monitoring job position, but AFAIR, this was a regular annoyance - repeating of A and AAAA queries in subsequent manner. So, if not mistaken, this decision was done to reduce the redundancy in such cases

**Comment by stamparm** [comment]
Apparently it is called **Happy Eyeballs** algorithm:

_As seen, DNS entries for a host can have multiple addresses, both for IPv4 and IPv6. The client will make a AAAA request, followed immediately by an A request. Happy Eyeballs, says the client must attempt to make a connection to the first IP address that is returned, regardless of address family._

* Reference: http://www.makikiweb.com/netsig/2020_11_happy_eyeballs.html

**Comment by JSteegmueller** [comment]
Sorry for the delayed response; I was on vacation. 
Thank you for the clarification - it makes sense, and I've learned something new! :) 

Thanks again and best regards, Janik
