### ISSUE TITLE
Has there been any change in the blacklist updates in the past week?

### ISSUE THREAD

**Issue by secdoc** [stamparm/maltrail#19272]
**Question**
Has there been any change in the blacklist updates in the past week?

**Support**
It seems that Maltrail on OPNsense was fine up to 8/7/2024 as far as over all visibility, but after that time it has progressively diminished to the point that there is no hits at all as of today...

8/7/2024
![image](https://github.com/user-attachments/assets/f2fc31ed-e9a9-4144-af59-41e02625484a)
8/12/2024
![image](https://github.com/user-attachments/assets/d37af22a-0073-4823-92e9-5d858997b82f)
overall activity by date (maltrail calendar view)
![image](https://github.com/user-attachments/assets/600f42fa-fae4-45a0-9933-703320c1805e)

**Comment by MikhailKasimov** [comment]
Hello!

Nothing was changed. Please, check sensor's status, if it is run or no.

**Comment by secdoc** [comment]
@MikhailKasimov the client is running. 
![image](https://github.com/user-attachments/assets/e3ff914f-1efd-4bad-a050-9b29b95379ee)
![image](https://github.com/user-attachments/assets/9002f1cb-bd87-45da-8cd7-bd20b101d2fb)
![image](https://github.com/user-attachments/assets/5c102959-9000-44fe-8cc3-84f0d38536a5)

**Comment by stamparm** [comment]
looks like sensor is dead (not web server). you should restart it somehow

**Comment by secdoc** [comment]
> looks like sensor is dead (not web server). you should restart it somehow

It  is showing as having been restarted, but I will restart the OPNsense FW to see if that makes a difference..., but from a process perspective all is showing as running and recreated when restarted....

**Comment by secdoc** [comment]
@MikhailKasimov do you want "all" or the last/most resent set covering the last week or two?

**Comment by MikhailKasimov** [comment]
> @MikhailKasimov do you want "all" or the last/most resent set covering the last week or two?

![image](https://github.com/user-attachments/assets/280adb12-d9f9-4f2b-bb58-dd421c4c014d)

For these days, for example....

**Comment by secdoc** [comment]
Here are the logs....
[maltrail.tar.gz](https://github.com/user-attachments/files/16602648/maltrail.tar.gz)

**Comment by MikhailKasimov** [comment]
Interesting, why SIGTERM...

![image](https://github.com/user-attachments/assets/117260af-4d16-44bb-8459-d23cb3bd5c4d)

@mimugmail Hello! Could you, please, give a hint how suchlike cases could be debugged in OPNSense? Thank you!

**Comment by secdoc** [comment]
Just an FYI I created a ticket in the [OPNsense  community discussion board](https://forum.opnsense.org/index.php?topic=42161.msg207842#msg207842)

**Comment by secdoc** [comment]
Some additional data points and not sure if it would be a rabbit trail to nothing but an issue where ICMP is being sent to the loopback address from the loopback in high volumes?

Here is example logs"

`<134>1 2024-08-14T11:56:43+00:00 xxxx.acme.tech filterlog 12611 - [meta sequenceId="7416432"] 66,,,1232f88e5fac29a32501e3f051020cac,lo0,match,pass,out,4,0x0,,64,1281,0,none,1,icmp,596,127.0.0.1,127.0.0.1,datalength=576
`

When looking at the logs there is a rather large volume of traffic to the loopback from the loopback which does not make sense.

![2024-08-14_07-37](https://github.com/user-attachments/assets/0cc1aed3-ca81-4e31-9fa2-54076fa358c0)

**Comment by MikhailKasimov** [comment]
Please, attach also ```ps -aux``` and ```netstat``` commands outputs... Because all this "activity" seems not to be a normal one.

**Comment by secdoc** [comment]
> Please, attach also `ps -aux` and `netstat` commands outputs... Because all this "activity" seems not to be a normal one.

Agree... see attached
[ps_aux.txt](https://github.com/user-attachments/files/16614376/ps_aux.txt)
[netstat.txt](https://github.com/user-attachments/files/16614378/netstat.txt)

**Comment by SgtDornan8** [comment]
Today I discovered oddities in the behavior of MT 0.66 on OPNsense. The databases have not been updated since January 31, 2024. Now I am conducting an experiment with manually updating the MT version to 0.72. I'm waiting until Monday to see if the automatic update will work
![image](https://github.com/user-attachments/assets/b3b3792e-6248-4021-bbc8-5dad036763b6)

**Comment by secdoc** [comment]
For reference, this is the spec's of the OPNsense system:

Versions:
OPNsense 24.7.1-amd64
FreeBSD 14.1-RELEASE-p3
OpenSSL 3.0.14
CPU:
12th Gen Intel(R) Core(TM) i5-1240P
Memory:
32GB

Installed Modules:
os-acme-client
os-clamav
os-crowdsec
os-dmidecode
os-etpro-telemetry
os-git-backup
os-haproxy    
os-intrusion-detection-content-et-open
os-intrusion-detection-content-et-pro    
os-intrusion-detection-content-pt-open
os-intrusion-detection-content-snort-vrt
os-iperf
os-maltrail
os-sensei
os-sensei-agent
os-sensei-updater
os-sunnyvalley
os-theme-cicada
os-theme-rebellion
os-vnstat

**Comment by MikhailKasimov** [comment]
@secdoc  Honestly speaking, currently I have no idea what is this bedlam at all... Is it an option to plan a conf-call (Meet, Teams, Zoom - doesn't matter) on Saturday, for example?

**Comment by mimugmail** [comment]
Currently off for two weeks, cant have a look

**Comment by MikhailKasimov** [comment]
> Weekend would be fine and can do zoom to discuss... Just need Timezone...

EEST

**Comment by secdoc** [comment]
How does 6PM EEST or 10 AM CST work for you on Sat 8/17?

**Comment by MikhailKasimov** [comment]
> How does 6PM EEST or 10 AM CST work for you on Sat 8/17?

Yes, 6PM EEST on Sat 8/17 is fine.

**Comment by secdoc** [comment]
Do you want to do zoom or want me to setup?

**Comment by MikhailKasimov** [comment]
> Do you want to do zoom or want me to setup?

Zoom. Wanna take a look by my eyes.

**Comment by secdoc** [comment]
@MikhailKasimov  here is the invite:

Lester Nichols is inviting you to a scheduled Zoom meeting.

Topic: Lester Nichols' Zoom Meeting
Time: Aug 17, 2024 10:00 Central Time (US and Canada)

Join Zoom Meeting
https://us06web.zoom.us/j/86162175588?pwd=f8tKpgB9yq3XbNE8JLBVahSR50hZIY.1

Meeting ID: 861 6217 5588
Passcode: 181892

---

**Comment by MikhailKasimov** [comment]
Hello!

@secdoc Would be interesting how's going with with latest OPNSense: https://forum.opnsense.org/index.php?topic=42355.0 and is it going on today better after we had a conf-call ?

**Comment by secdoc** [comment]
> Hello!
> 
> @secdoc Would be interesting how's going with with latest OPNSense: https://forum.opnsense.org/index.php?topic=42355.0 and is it going on today better after we had a conf-call ?
I had checked this morning (0500 CST) and there were no updates, but after seeing your message, it looks like they have pushed the updates to the repo. I will update to the latest version and let you know. As far as current issues, they still are the same, so looks like outbound (sourced from my network, primarily DNS lookups) shows but still no change in what should be expected volume.

**Comment by secdoc** [comment]
> > Hello!
> > @secdoc Would be interesting how's going with with latest OPNSense: https://forum.opnsense.org/index.php?topic=42355.0 and is it going on today better after we had a conf-call ?
> 
> @MikhailKasimov I had checked this morning (0500 CST) and there were no updates, but after seeing your message, it looks like they have pushed the updates to the repo. I will update to the latest version and let you know. As far as current issues, they still are the same, so looks like outbound (sourced from my network, primarily DNS lookups) shows but still no change in what should be expected volume.

@MikhailKasimov I applied the update and there has been no change in traffic visibility. So it appears based on visibility, traffic patterns have drastically change on inbound activity in comparison to what what happening 2 weeks ago.

![image](https://github.com/user-attachments/assets/f1b6270e-a3a6-4035-b939-30063196b140)

**Comment by secdoc** [comment]
I am closing the issue because I think this is more associated now with a drastic traffic pattern change at the ingress. The errors or ancillary errors I think were red herrings...

**Comment by MikhailKasimov** [comment]
Ok on closing. Anyway, we've tried all variants to debug Maltrail's detection behavior due to conf-call session and detection was correct.

**Comment by secdoc** [comment]
This is just an update to this issue. After applying the OPNsense 24.7.3 update today, the Maltrail traffic patterns that were expected returned. So not sure if part of the issue was associated with the delta and/or changes between 24.7.2, but now seeing the visibility expected...

![image](https://github.com/user-attachments/assets/f25f23d7-91f6-4c30-87e7-8368c0310ef8)

**Comment by MikhailKasimov** [comment]
This is just one more confirmation, that Maltrail works OK itself. The deal was in its environment. Thank you for letting know!
