### ISSUE TITLE
[SOURCE] PacketDump

### ISSUE THREAD

**Issue by BlackHoleMonster** [stamparm/maltrail#19273]
Hello,
if you want we made new attacker ips list updated every 5 min. based on tcpdump.

There is also web interface so you can live view who is attacking - https://packetdump.s-e-r-v-e-r.pw/

```
🚫 ALL IPs:
https://packetdump.s-e-r-v-e-r.pw/ips
```

Thanks!

**Comment by MikhailKasimov** [comment]
Hello! ``ips list updated every 5 min``` <-- Do these IPs aggreate in ```/blackhole-today```? Or it is separated database?

**Comment by MikhailKasimov** [comment]
@stamparm plz, take a look, seems resonable.

**Comment by stamparm** [comment]
what's the methodology? there is zero information on how that list is generated.

also, what's the retention time for individual IPs? it is not clear what that list represents nor for how long those entries stay inside after the last offense

**Comment by BlackHoleMonster** [comment]
Hi :)
as being said the list is generated from tcpdump (those servers listen on every port for incoming IPS)

added new today list (so only today ips that attacked are included)
```https://packetdump.s-e-r-v-e-r.pw/ips-today```

those list have all ips attacked and will not be removed from list
``https://packetdump.s-e-r-v-e-r.pw/ips``

**Comment by stamparm** [comment]
i don't see whether this is TCP and UDP or only TCP capture. also, i can't comprehend what's the nature of such list? like, capturing "attackers" or "scanners" or anything

p.s. I've just seen UDP now captured at the main page. just food for thought. anybody can spoof a UDP packet with an arbitrary source address and fill your list with "fake" attackers. anyhow, currently I see more problems than benefits TBH

**Comment by BlackHoleMonster** [comment]
i dont want to be bad or so it your project after all, but you saying that you can spoof IP, so basically EVERY ip blacklist is unusable as it get spoofed ips right? so the point of blacklist ips is what then ? :)
