### ISSUE TITLE
[BUG] FingerprintJS domain and IP of STUN server flagged as malicious - Rhadamanthys IOCs

### ISSUE THREAD

**Issue by ZPetricusic** [stamparm/maltrail#19288]
**Describe the bug**
Hi, while hunting for Rhadamanthys IOCs in an environment, I noticed that Maltrail is flagging the IP address `3.66.243[.]164` and domain `use1-turn.fpjs[.]io` as malicious:

- https://github.com/stamparm/maltrail/blob/master/trails/static/malware/rhadamanthys.txt#L1855
- https://github.com/stamparm/maltrail/blob/master/trails/static/malware/rhadamanthys.txt#L1856

The indicators are mentioned in the Anyrun task referenced above the entries (under the `Connections` tab):

- https://github.com/stamparm/maltrail/blob/master/trails/static/malware/rhadamanthys.txt#L1850

After some research, I found that this domain is related to the [FingerprintJS](https://dev.fingerprint.com/docs/protecting-the-javascript-agent-from-adblockers) service, as referenced in the documentation:

> _Ad blockers like Adblock or uBlock Origin and privacy-focused browsers like Brave block all these requests. They are keeping track of Fingerprint domains hosting our APIs (for example, **fpjscdn[.]net, api.fpjs[.]io, fptls[.]com**) and blocking all browser requests matching those domains._

This service appears to be used legitimately by Dropbox, which is used by Rhadamanthys to deliver the initial payload.

**How To Reproduce**
1. Start a network capture (e.g., using Wireshark)
2. Navigate to `https://www.dropbox.com/`
3. Interact with the page for a few seconds
4. Filter for DNS queries containing `fpjs[.]io` - e.g., `dns.qry.name contains "fpjs.io"`
4.1. Alternatively, filter for the STUN protocol and IP addresses resolved from the queried domain. For `use1-turn.fpjs.io`, the IPs were:
    - 3.66.243[.]164
    - 18.196.235[.]131

**Expected behavior**
Interacting with the Dropbox web page should cause network connections toward the mentioned domain/IPs. These will, however, not be visible in the Network tab in Developer Tools as they are STUN requests.

**Screenshots**
![image](https://github.com/user-attachments/assets/d481151f-5692-4362-ab9f-72447c7945f8)

**Additional context**
Using Maltrail as a source of open-source Intelligence data about malicious activity. Not directly as a sensor.

**Comment by MikhailKasimov** [comment]
Hello! Thank you for the info. This should b fixed now. Update, please, Maltrail database and restart the sensor.

**Comment by ZPetricusic** [comment]
Thank you for the prompt response!
