### ISSUE TITLE
[Questions and Support] Pylint alerts corrections as part of an intervention experiment

### ISSUE THREAD

**Issue by evidencebp** [stamparm/maltrail#19282]
I'd like to conduct a software engineering experiment regarding the benefit of [Pylint](https://pypi.org/project/pylint/)  alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).
In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control.
After the interventions are done, one can wait and examine the results.

I'm asking for your approval for conducting an intervention in your repository.

See examples of interventions in [stanford-oval/storm](https://github.com/stanford-oval/storm/pull/181), [gabfl/vault](https://github.com/gabfl/vault/pull/82), and [coreruleset/coreruleset](https://github.com/coreruleset/coreruleset/pull/3837).

You can see the [planed interventions](https://github.com/evidencebp/pylint-intervention/tree/main/interventions/candidates/stamparm_maltrail_interventions_October_06_2024.csv)

May I do the interventions?

**Comment by MikhailKasimov** [comment]
Hello!

What are the benefits for Maltrail, as the product, here?

**Comment by evidencebp** [comment]
The [plan](https://github.com/evidencebp/pylint-intervention/blob/main/interventions/candidates/stamparm_maltrail_interventions_October_06_2024.csv) is generated automatically in order not to introduce bias.

It includes 33 intervantions in 23 files.
Out of them 3 are structural alerts (too-many-branches) and a simplification alert.
@MikhailKasimov , I belive these will lead to most benefit since too many barnches are related to tendency to bugs and more time for modifications.

Most others are readabliity alerts (line-too-long).
There influence seems to be very small (this is part of what the experiment tries to evaluate).
On the other hand, the fix is usually adding a new line, making the intervantion and its review very simple.

Hence, the product might avoid some bugs, and code will be easier to work with.
Note that I still don't have enough data to support this estimation yet the benefit of reducing the number of branches is well supported in prior research.

**Comment by stamparm** [comment]
sorry, not interested. python part of the project is simplistic. there is no need for over-engineering. used pylint and similar tools years and years ago
