### ISSUE TITLE
Capture traffic of my local network to internet

### ISSUE THREAD

**Issue by sergioandresrr** [stamparm/maltrail#193]
Hi, need help. I don't understand how configure maltrail for capture the traffic of my network. When I use maltrail it just capture the traffic of the host who is running the sensor and the server but it no capture the traffic of the hosts what are connected to the local network by a HUB. The hosts are connected to the local network and internet also and I can access to the server from all the host connected to the network but I need what the sensor capture the traffic of the network.

I need solve this for a homework of my university.
I'm sorry by my English it's really bad, I'm a Latin boy. Thank you.

**Comment by stolimarie** [comment]
Make sure your nic is in Promiscuous Mode.

Kind Regards,
Tequila Schramm
(229) 854-0643

On Thu, May 24, 2018 at 10:13 AM, Sergio Rodríguez <notifications@github.com

**Comment by sergioandresrr** [comment]
@stolimarie Yes, it is in promiscuous mode.

**Comment by sergioandresrr** [comment]
I have a question: Should maltrail be installed in every host of the local network and send logs to the server? or just with it installed and working in the server is enough?.
