### ISSUE TITLE
use tcpdump as sensor for maltrail

### ISSUE THREAD

**Issue by blackyellowred** [stamparm/maltrail#194]
Hey,

I am able to ssh into pfsense and pipe the tcpdump data to my local copy of wireshark. I was wondering if I can pipe tcpdump output to maltrail.

**Comment by stamparm** [comment]
A) Console output of tcpdump is basically an ASCII representation of traffic being sniffed
B) tcpdump's `-w` can be used to save captured traffics (and pipe remotely) to PCAP. Maltrail supports parsing of PCAP file format, though, it reads it in one go (reads everything without blocking mode for new packets)

**Comment by blackyellowred** [comment]
I tried that but the sensor loads the file and then just exists, is that normal?

**Comment by stamparm** [comment]
`Maltrail supports parsing of PCAP file format, though, it reads it in one go (reads everything without blocking mode for new packets)` <- that basically means the behavior you described. Currently it can't read piped files - only reads the current content of that same file
