### ISSUE TITLE
Custom feed issue

### ISSUE THREAD

**Issue by jtorrejon** [stamparm/maltrail#195]
Hi team,

I've recently deployed Maltrail and I've some doubts about the custom feeds in the config file.

Is it possible to add more than one CUSTOM_TRAILS_URL source in the config file? I've tried several times by putting some URLs separated by comma, or space or adding all of them line by line preceding the CUSTOM_TRAILS_URL tag, but none of them worked.

Thanks in advance.

Regards,

**Comment by stamparm** [comment]
Sorry for not replying earlier. I'll implement this today and let you know.

**Comment by stamparm** [comment]
Done. From now on you can also use multiple urls inside `CUSTOM_TRAILS_URL` like:

`CUSTOM_TRAILS_URL http://www.test1.com/list1.txt,http://www.test2.com/list2.txt,....`

**Comment by jtorrejon** [comment]
Thank you so much for doing this.

Regards,
