### ISSUE TITLE
SecurityError: The operation is insecure. Script: http://127.0.0.1:8338/js/papaparse.min.js Line: 6

### ISSUE THREAD

**Issue by hktalent** [stamparm/maltrail#1960]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/18223385/58001095-1a724b00-7b0d-11e9-9e1f-d6e5e65754a1.png">

**Comment by hktalent** [comment]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/18223385/58001170-4f7e9d80-7b0d-11e9-9bee-35dbf35f02b2.png">

**Comment by hktalent** [comment]
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.

**Comment by stamparm** [comment]
How to reproduce this?

**Comment by stamparm** [comment]
Ok. Reproduce on my local machine. Thing is that this shouldn't cause problems like you are having in #1964

**Comment by hktalent** [comment]
https.py
```
# self.send_header(HTTP_HEADER.CONTENT_SECURITY_POLICY, "default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self'; " +
                        #                                                       "script-src 'self' 'unsafe-eval' https://stat.ripe.net; connect-src 'self'; form-action 'self'; " +
                        #   
```
so is ok

**Comment by stamparm** [comment]
I believe that some of your browser plugins (e.g. Adblock) is trying to inject its own JS
