### ISSUE TITLE
Working with IP ranges

### ISSUE THREAD

**Issue by jtorrejon** [stamparm/maltrail#197]
Hi again,

After implementing some custom feeds, We've noticed that some IoCs containing IP ranges (i.e. 175.225.36.22/26) are not parsed by Maltrail.

Is there any way to read those kind of values?

Many thanks and kind regards,

**Comment by stamparm** [comment]
It should be possible now

**Comment by jtorrejon** [comment]
Hi again,

We're having some problems with this issue. After getting some IP ranges from custom feeds (issue #195), this error is shown in the command prompt:

[o] '(remote custom)'
[!] unhandled exception occurred ('negative shift count')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "sensor.py", line 1005, in <module>
    main()
  File "sensor.py", line 996, in main
    init()
  File "sensor.py", line 722, in init
    update_timer()
  File "sensor.py", line 697, in update_timer
    _ = update_trails(server=config.UPDATE_SERVER)
  File "/usr/share/maltrail/core/update.py", line 200, in update_trails
    start_int = addr_to_int(prefix) & make_mask(mask)
  File "/usr/share/maltrail/core/addr.py", line 18, in make_mask
    return 0xffffffff ^ (1 << 32 - bits) - 1
ValueError: negative shift count

Could you please check it out? Is it possible that this script is running for all IP addresses and ranges we're getting? In our custom feeds, IP ranges come with the value behind a /, but IP addresses does not come with it.

Thanks and regards,

**Comment by stamparm** [comment]
Can you post here an example of used IP ranges in your case? It doesn't seem to be a standard `prefix/mask` (e.g. `192.168.5.0/24`)

**Comment by stamparm** [comment]
I've pushed a related patch (to prevent the crash), but I believe that in your case something like `x.x.x.x/y.y.y.y` occurred (i.e. mask in IP form)

**Comment by jtorrejon** [comment]
Okay, so finally our problem is We're getting some URLs with the same pattern as an IP range, for example:

http://152.236.2.45/1.aspx

In that case we don't need to parse the IP.

Thanks

**Comment by jtorrejon** [comment]
Hi again,

We solved this issue by doing some modifications in line 197-208 in update.py file.

Find attached the file in case you want to modify in your code.

Many thanks,
[update.zip](https://github.com/stamparm/maltrail/files/2123463/update.zip)

**Comment by stamparm** [comment]
My fault. Find your changes merged in the latest revision. Thx
