### ISSUE TITLE
maltrail architecture

### ISSUE THREAD

**Issue by avzhudzaifah92** [stamparm/maltrail#199]
I am interested in learning about the maltrails in the github that are amazing.
But after I read, there are I do not understand the architecture of maltrail, I have tried to understand but also failed. Let me ask what is the maltrail sensor?
and whether installed on the router or laptop that has been installed kali linux. Sorry if there is a mistake, I thank you in advance

**Comment by stamparm** [comment]
Already replied to your email. Including the reply here too:

```
Sensor should be (ideally) run on an isolated (Linux) machine where you are redirecting the copy of your traffic (ideally the Internet traffic from your router).

It is not of much of a use if you run it at your laptop.
```
