### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by scriptzteam** [stamparm/maltrail#20]
If server is behind cloudflare it shows coudflare ip, not the real ip :) Pls fix it.

**Comment by stamparm** [comment]
Trolololo (not sure if I need to explain...)

**Comment by scriptzteam** [comment]
in php you can get visitor source ip:
http://stackoverflow.com/questions/14985518/cloudflare-and-logging-visitor-ip-addresses-via-in-php

why not show real visitor ip?

**Comment by stamparm** [comment]
@scriptzteam aha... you want to show that small text in `trail` beside the IP for Cloudflare addresses?

**Comment by scriptzteam** [comment]
yep, the real ip of visitor :)

**Comment by stamparm** [comment]
now i am again confused :). can you please describe in detail what you mean by "real ip of visitor"? maybe on one example. what maltrail does now and what you would like it to do (more)?

**Comment by stamparm** [comment]
ahhaaaaaaa....
`HTTP_CF_CONNECTING_IP`

**Comment by stamparm** [comment]
so, you want to extract the `HTTP_CF_CONNECTING_IP` from requests itself. makes sense :)

**Comment by scriptzteam** [comment]
yes thats it :) sry just 12 hours at work and no sleed :D i cant think properly now :D

**Comment by unixfox** [comment]
You can restore the IP with : 
- nginx : https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-
- apache : https://support.cloudflare.com/hc/en-us/articles/200170836-How-do-I-restore-original-visitor-IP-to-Apache-Web-Servers-
