### ISSUE TITLE
how monitor anything；Achieve such an effect

### ISSUE THREAD

**Issue by hktalent** [stamparm/maltrail#2030]
how monitor anything
Not just the ip in the alarm blacklist

and 
Define warnings, threat levels online
Achieve such an effect
![image](https://user-images.githubusercontent.com/18223385/58394610-bc96b380-8076-11e9-920e-9d12b6d9ffab.png)

**Comment by hktalent** [comment]
https://docs.python.org/2/library/gettext.html

**Comment by hktalent** [comment]
https://github.com/markmarkoh/datamaps

**Comment by hktalent** [comment]
```
find . -name "*.py"|xargs grep -Eo '("[^"]+")' %
```

**Comment by vicjos** [comment]
Hello hktalent,

Did you manage to monitor everything, not only the integration with maps, but, the way to collect both URLs and IPs.

Thank you very much,

**Comment by hktalent** [comment]
@vicjos  I use my python3 code, now
