### ISSUE TITLE
Not logging - sorry first issue closed

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [stamparm/maltrail#21]
Hello.

I have problem with logging like this user on https://github.com/stamparm/maltrail/issues/14 . My server run on 0.0.0.0:8338 and sensors running too (opening interface 'any'). Server run without sudo and sensors with sudo command. But there is no log when ping some IP. I can login on my server panel successfully. First I try with screen on server but nothing happen then I install VNC and run on VNC and this not problem. My configuration is default.

Please help me, thank you.

**Comment by stamparm** [comment]
What do you get for:

1) `ps aux | grep python`
2) `ifconfig -a`

**Comment by 15w34r0n3D4y** [comment]
Results of:

1) ip route get 8.8.8.8

8.8.8.8 via 172.31.0.1 dev eth0 src 172.31.5.161

2) ifconfig -a

eth0 - my local ip address

lo - 127.0.0.1

3) ps aux | grep python

username - /usr/bin/python /usr/share/system-config-printer/applet.py
username - python server.py
root - sudo python sensor.py
root - python sensor.py
username - grep --color=auto python

Thank you for fast answer :+1:

**Comment by stamparm** [comment]
`ifconfig -a` should tell you if `eth0` is in `PROMISC` mode. Is it?

**Comment by 15w34r0n3D4y** [comment]
When type sudo ifconfig eth0 -promisc and then sudo tail -f /var/log/syslog there is msg device eth0 entered promiscuous mode

**Comment by stamparm** [comment]
So, now its in promiscuous mode. Can you please retry that "ping test"?

E.g.:

```
ping -c 1 136.161.101.53
cat /var/log/maltrail/$(date +"%Y-%m-%d").log
```

**Comment by stamparm** [comment]
Also, just in case please write if you see anything with:

`cat ~/.maltrail/trails.csv | grep 136.161.101.53`

**Comment by 15w34r0n3D4y** [comment]
when ping 8.8.8.8 (I see on screenshot this IP)

for cat /var/log/maltrail/$(date +"%Y-%m-%d").log 

get this error cat: /var/log/maltrail/2015-12-17.log: No such file or directory

for this IP address

but now when I ping 136.161.101.53 ip address there is log. It's works!

Thank you again and sorry for new issue

**Comment by stamparm** [comment]
`8.8.8.8` is not malicious :)

on which screenshot did you see this?

**Comment by 15w34r0n3D4y** [comment]
I know Google IP it is :dart:  ... nevermind haha :ice_cream: :package: 
Thank you again :+1:
