### ISSUE TITLE
Update collecting feeds from data.netlab.360.com_dga_

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#211]
Hello!

Nowadays, we have such feeds from ```360.com``` in ```Maltrail```:

```
 [o] 'http://data.netlab.360.com/feeds/dga/conficker.txt'
 [o] 'http://data.netlab.360.com/feeds/dga/cryptolocker.txt'
 [o] 'http://data.netlab.360.com/feeds/dga/locky.txt'
 [o] 'http://data.netlab.360.com/feeds/dga/necurs.txt'

```

But, seems, there are also many feeds from ```360.com```, that can be added to ```Maltrail```:

[0] http://data.netlab.360.com/dga/

Doable?

**Comment by stamparm** [comment]
Including tens of thousands of DGA addresses is (memory) expensive, especially on low-memory servers. Only "popular" DGA algorithms can be included (IMO).

DNS queries graph (on that same page) should be the BEST indicator what to include. Conficker is by far the most wide-spread DGA malware. Out of those non-included, I can see that I could include `virut`, `chinad`, `gameover` and `tofsee`.

**Comment by MikhailKasimov** [comment]
OK, let it be so.
