### ISSUE TITLE
login

### ISSUE THREAD

**Issue by mrglobule** [stamparm/maltrail#22]
Hello,
first congrats for your job.

I wrote you because i try to change the password in the maltrail.conf, and now i can't connect to the server...
here is the mailtrail.conf user's section
    USERS 
	    #admin:$ff0ae5570e1f39a8$10000$d42e622afe0b0ede53b64b97a59d65c221edbf9dde2f0e95:0:0.0.0.0/0                        # changeme!
	    toto:$8c81af41b9a90583$10000$650a0db5a4df76fee8a2557c1388be3c2b0b16362c423680:0:0.0.0.0/0

i ran on windows and all was ok before i change the password.

Thanks for your help

**Comment by stamparm** [comment]
@mrglobule is there a line space before those entries? from your copy-paste it doesn't look like there is

valid entries would be like:

```
USERS
  #admin:$ff0ae5570e1f39a8$10000$d42e622afe0b0ede53b64b97a59d65c221edbf9dde2f0e95:0:0.0.0.0/0 # changeme!
  toto:$8c81af41b9a90583$10000$650a0db5a4df76fee8a2557c1388be3c2b0b16362c423680:0:0.0.0.0/0
```

**Comment by stamparm** [comment]
With the latest revision you'll be warned in this kind of cases (if I was right in last message)

**Comment by gerroon** [comment]
Could you tell me how to generate the proper password? I tried couple sha256 methods but I still cant get it to work :(

**Comment by stamparm** [comment]
@gerroon can you please give me an example user configuration line (containing that SHA256) have you used and what was the expected password behind it?

For example, if you go to (e.g.) https://www.xorbin.com/tools/sha256-hash-calculator and type in `test` you'll get a value `9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08` as SHA256 digest. Now, if you use `admin:9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08:0:` inside the maltrail.conf (section `USERS`), you'll be able to login with `admin:test`. Note: you have to restart the server once you do the changes to `maltrail.conf`
