### ISSUE TITLE
Re-check direct .apk downloading (not detected)

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#236]
Hello!

On ```v.0.10.350```

Link: [0] hxxps://huhu-1251744023.file.myqcloud.com/apk/domain/huhu.apk

```
curl -I hxxps://huhu-1251744023.file.myqcloud.com/apk/domain/huhu.apk
HTTP/1.1 200 OK
Server: NWSs
Date: Sat, 18 Aug 2018 18:05:31 GMT
Content-Type: application/vnd.android.package-archive
Content-Length: 26931504
Connection: keep-alive
Cache-Control: max-age=600
Expires: Sat, 18 Aug 2018 18:15:31 GMT
Last-Modified: Sun, 05 Aug 2018 11:04:07 GMT
X-NWS-LOG-UUID: 512d22e5-f86c-46e3-98ab-e71adba108ed
X-Cache-Lookup: Hit From Disktank
Content-Disposition: attachment; filename*="UTF-8''huhu.apk"
Accept-Ranges: bytes
```
Domain ```myqcloud.com``` is not present in ``` maltrail/misc/whitelist.txt ```.

And MT doesn't report on suspicious action: ``` Direct .apk download ```.

https://github.com/stamparm/maltrail/blob/master/core/settings.py file shows, such function is present:

``` SUSPICIOUS_DIRECT_DOWNLOAD_EXTENSIONS = set((".apk", ".exe", ".scr")) ```

Please, consider! Thanks!

**Comment by stamparm** [comment]
You are downloading from encrypted (HTTPS) connection

**Comment by MikhailKasimov** [comment]
Indeed...
