### ISSUE TITLE
error and question regarding web client

### ISSUE THREAD

**Issue by jpgpi250** [stamparm/maltrail#2423]
I'm trying to run maltrail on a older tablet, android 4.1.1. I'm getting the error: ´[object Event] Script: undefined Line: undefined'. If I click OK, the page loads. Unfortunately, there aren't many troubleshooting options on the tablet.

Question(s):
- Is it possible to define a user without a password in the configuration file? I've tried, but neither the sensor, nor the server start anymore. They both complain about the invalid user configuration.
- Is it possible to restrict this user to a single IP address (the tablet)?

Great application, thank you for your time and effort.

**Comment by stamparm** [comment]
Hi.

A) I couldn't reproduce the command line error when `USERS` is empty or non-existent. Nevertheless, I need to implement the possibility to have it empty in the browser client itself
B) There is no possibility to do the per-IP restriction. That's why there is an option for username:password in the first place

**Comment by stamparm** [comment]
@jpgpi250 with the latest revision, if you just remove the `USERS` part (and subitems - i.e. `admin`), you'll be able to run and access the Maltrail without any credentials

**Comment by jpgpi250** [comment]
thank you for the update
- I've removed the user section, perfect, no authentication
- the error, mentioned earlier, does NOT appear until there is an actual entry, which I force, per instructions by entering `ping -c 1 136.161.101.53`. As soon as the error is registered, updating the screen causes the error.

Thank you for your time and effort

**Comment by jpgpi250** [comment]
attached screenshot of error
![Screenshot_2019-06-28-20-49-28](https://user-images.githubusercontent.com/24669386/60364489-9d2cd680-99e6-11e9-9bc1-f1cff434555e.png)

**Comment by stamparm** [comment]
Tried on Android's Firefox, Chrome and Mi's Browser. Can't reproduce (events are being server normally).

How to reproduce this issue

**Comment by stamparm** [comment]
With the latest commit you'll should be able to get more informative error message

**Comment by jpgpi250** [comment]
Installed the latest version (I asume) same error message, no detail. I currently have 9 entries in maltrail en get the error 9 times. So it's somewhere in the routine that writes an entry. Tried the default android browser (android 4.1.1 - can't upgrade - out of support) and https://play.google.com/store/apps/details?id=tk.klurige.fullscreenbrowser&hl=en (which I would like to use - full screen)

**Comment by jpgpi250** [comment]
sorry accidental close....

**Comment by stamparm** [comment]
![aaaa0](https://user-images.githubusercontent.com/921555/60511871-4fa8b600-9cd3-11e9-93fc-c0aa35088146.png)

**Comment by stamparm** [comment]
I can't reproduce. Also, browser you've mentioned doesn't look like a mainstream one:

![1111](https://user-images.githubusercontent.com/921555/60511976-a57d5e00-9cd3-11e9-9b38-605fdfac2824.png)

**Comment by stamparm** [comment]
Conclusion: un-reproducible issue and system not supported by non-mainstream (i.e. Firefox, IE, Chrome) browsers
