### ISSUE TITLE
tools - Flush Local Storage

### ISSUE THREAD

**Issue by OIEIEIO** [stamparm/maltrail#2448]
What a great TooI....thankyou guys! 
I tried using the tool to flush but did not change anything on the screen. How do you clear data so the http login shows fresh results?

**Comment by stamparm** [comment]
Hi.

Basically, flush local storage only clears the data stored locally (i.e. tags and custom IP aliases).

Hence, I am not sure to which "clear data" and "fresh results" are you referring to? If you want to get the latest data/events you just have to press F5 to refresh the tab/window itself

Bye

**Comment by OIEIEIO** [comment]
Hi,

Thank you for responding to my email. Great tool you made. I figured it out. Keep up the awesome work.

Regards,

OIEIEIO

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
