### ISSUE TITLE
Multiple sensors

### ISSUE THREAD

**Issue by unixfox** [stamparm/maltrail#25]
Ability to manage multiple sensors with the web interface.

**Comment by stamparm** [comment]
@unixfox but you already can do that. Can you please be more specific what you need/want.

**Comment by unixfox** [comment]
I want to analyse logs from multiple sensors in the main web interface (Server) but I didn't found any documentation about that.

**Comment by stamparm** [comment]
Are multiple sensors (e.g. one sensor per interface) being run on same machine or different? If on different, you can use the `UDP_ADDRESS` for setting the collecting address where sensors should send their data to. That should be the same machine as the server itself.

**Comment by stamparm** [comment]
Minor update:
1) `LOG_SERVER` should point to the collecting machine (same where `server.py` is being run)
2) `UDP_ADDRESS` should be the listening address (leave it to `0.0.0.0`)

**Comment by unixfox** [comment]
Two sensor on two different machine and one main web interface on one machine.
I'll try, thank you !

**Comment by stamparm** [comment]
I'll most probably rename `UDP_ADDRESS` to something like: `LOG_ADDRESS`

**Comment by unixfox** [comment]
I tried to configure sensors and server but web interface returns null informations.
Chrome console returns me : `Failed to load resource: the server responded with a status of 404 (Not Found) : https://x.x.x.x:8338/events?date=2015-12-18`
Config file on the first machine (one sensor) : https://paste.unixfox.eu/ixegupuvob.txt.
Config file on the second machine (with one sensor and the web interface) : https://paste.unixfox.eu/vetejumora.txt.
What I have done wrong?

**Comment by stamparm** [comment]
Looks ok. That 404 just means that there are no events for that date.

Can you please do the test ping on the remote sensor (https://paste.unixfox.eu/ixegupuvob) and recheck the web interface on the server:

`ping -c 1 136.161.101.53`

**Comment by unixfox** [comment]
I've already tried it but the web interface don't found any event.
When I do `cat /var/log/maltrail/$(date +"%Y-%m-%d").log`, the terminal returns me strange logs : 
>"2015-12-17 19:09:42.923035" vps07 x.x.x.x 30640 94.23.218.25 25900 TCP IP x.x.x.x "potential port scanning" (heuristic)
"2015-12-17 19:09:43.019070" vps07 x.x.x.x 36626 94.23.218.25 25901 TCP IP x.x.x.x "potential port scanning" (heuristic)
"2015-12-17 19:09:42.843072" vps07 x.x.x.x 26071 94.23.218.25 25501 TCP IP x.x.x.x "potential port scanning" (heuristic)
My logs are full of false positive because the ip of the attacker comes from the machine hosting my second sensor.

**Comment by stamparm** [comment]
When you set up the remote sensor and server then the server's log files should be filled. I don't know in your case where did you find that `/var/log/maltrail/$(date +"%Y-%m-%d").log`. Also, the ping I've mentioned should produce the conficker warning at the server logs.

As of false positives, I am not sure that I understand what's going on in your case. From what I can see there are lots of connections on different ports going on in those logs

**Comment by unixfox** [comment]
Ok I found a strange bug, sensors are using UTC but python server is using default time zone (CEST) so when I visited the web interface returns it for me 2015-12-18 date.
Is it possible to whitelist an IP on the sensors ?

**Comment by stamparm** [comment]
whitelisting is possible. first please update to the latest revision.

there is a new option in `maltrail.conf` called `USER_WHITELIST`. just add the IPs there.

p.s. with the latest revision there should not be 404s any more for empty date event data

**Comment by stamparm** [comment]
@unixfox please update now (haven't pushed till this moment)

**Comment by unixfox** [comment]
@stamparm Okay I'll try new update !

**Comment by stamparm** [comment]
@unixfox ok now?

**Comment by unixfox** [comment]
@stamparm Everything is working good, thank you so much !
