### ISSUE TITLE
SyntaxError: expected expression on browsing via different UA

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#251]
Hello!

Have got an error message:

``` SyntaxError: expected expression, got '<' Script: http://127.0.0.1:8338/?papaworker Line: 1 ```

Steps-to-reproduce:

1) Firefox is installed.
2) User-Agent Switcher (https://mybrowseraddon.com/useragent-switcher.html) is installed via Firefox Add-ons installation mechanism.
3) In User-Agent Switcher switch to any UA instead of default.
4) Try to access MT webpage.

![maltrail_syntax_error](https://user-images.githubusercontent.com/7167300/44572469-901ed580-a78c-11e8-8cf9-ee471dc73005.png)

**Comment by MrHappy** [comment]
This is happening to me now too, after updating to most recent Firefox (v72.0).

**Comment by stamparm** [comment]
@MikhailKasimov @MrHappy it should be fixed now with the latest commit/revision

**Comment by MrHappy** [comment]
@stamparm tested and it works again! Thanks!
