### ISSUE TITLE
configurable search engine

### ISSUE THREAD

**Issue by jpgpi250** [stamparm/maltrail#2521]
feature request:

I noticed, when hovering over a domain name, in the trail column, per default, bing.com is used.
Would it be possible to make the search engine configurable in maltrail.conf, this to use for example duckduckgo, which respects privacy more than other popular search engines?

Thank you for your time and effort.

**Comment by stamparm** [comment]
Not gonna happen. Previously there was a possibility to choose between Google, DuckDuckGo and Bing, but Google and DuckDuckGo decided to shutdown the support for 3rd party iframe-ing of their results. Also, it is really hard to find search engines that still support iframe-ing
