### ISSUE TITLE
[benkow.cc] Panel and RAT trails on consideration to add

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#255]
Hello!

- Panel tracker: [0] http://benkow.cc/passwords.php
- Panel tracker trail: [1] http://benkow.cc/export.php (downloads ```urls.cvs```)

- RAT tracker: [2] http://benkow.cc/ratracker.php
- RAT tracker trail: [3] http://benkow.cc/export_rat.php (downloads ```urls.cvs```)

Whitelisting request for ```benkow.cc```: #254 

Benkow's twitter: [5] https://twitter.com/benkow_ (with ```_``` sign, yes).

**Comment by MikhailKasimov** [comment]
Some chances to be considered/added?

**Comment by MikhailKasimov** [comment]
Yes, this will be also useful for such cases: https://twitter.com/James_inthe_box/status/1031145087525244928

**Comment by MikhailKasimov** [comment]
OK, let's have a decision here.

**Comment by MikhailKasimov** [comment]
Yes/No , @stamparm ?

**Comment by stamparm** [comment]
benkow is already being covered with [blackbook](https://github.com/stamparm/blackbook) feed.

**Comment by stamparm** [comment]
p.s. lots of those benkow's feeds you've enlisted here are not updated for some time (e.g. benkow.cc/export_rat.php has been dead for half a year or so)
