### ISSUE TITLE
make trail storage customizeable via config

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#2569]
Hi,

while playing with OPNsense plugin and maltrail I realized this:

```
root@OPNsense:~ # python2.7 /usr/local/share/maltrail/sensor.py
Maltrail (sensor) #v0.13.1

[i] using configuration file '/usr/local/share/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[?] at least 384MB of free memory required
[i] using '/root/.maltrail/trails.csv' for trail storage
[i] updating trails (this might take a while)...
 [o] 'https://data.netlab.360.com/feeds/dga/chinad.txt'
[x] stopping (Ctrl-C pressed)
[i] finished
```

Trails go into .maltrail/trails.csv. 

But what happens when I start maltrail via an init script:
https://github.com/opnsense/plugins/blob/master/security/maltrail/src/etc/rc.d/opnsense-maltrailsensor

I'm quite sure this wont work and no trails are loaded. Perhaps there is a way to specifiy a path so I can set correct permissions to it.

**Comment by stamparm** [comment]
A) There shouldn't be any problems, even in your case. Although, update could be automatically run multiple times (if different user accounts are being used)
B) Nevertheless, with the latest commit I've put the `TRAILS_FILE` into configuration file. So, from now on you will be able to explicitly set trail file location by using that same option

**Comment by mimugmail** [comment]
Great addition, thank you!
