### ISSUE TITLE
DNS requested displayed

### ISSUE THREAD

**Issue by jpgpi250** [stamparm/maltrail#2577]
I have configured maltrail to look at port 53 only, DNS
I'm running unbound as a recursive DNS server, so every DNS request ends up contacting the specific DNS server, that holds the record requested.
Some of these DNS servers are reported by maltrail as a threath, which is the reason for using maltrail

Would it be possible to not only display the suspicious IP address (or name) of the DNS server contacted but also the DNS entry it was asked to resolve?

Example:
If 8.8.8.8 would be a suspicious DNS server (it isn't, but used as an example), I would like to see an entry in maltrail that says **8.8.8.8** AND record requested, such as **ssl.google-analytics.com**

Thank you for your time and effort

**Comment by stamparm** [comment]
Done. Please update and rerun everything. Now you'll see something like this:

![abc](https://user-images.githubusercontent.com/921555/60500166-24659d00-9cba-11e9-9499-1fc72bac112f.png)
