### ISSUE TITLE
your latest change (DNS info)

### ISSUE THREAD

**Issue by jpgpi250** [stamparm/maltrail#2579]
I'm NOT sure you understood my request correctly, don't know if it is at all possible?

I'm now seeing the DNS name of the resolver that is contacted, but a resolver probably is serving many DNS domains.

The resolver name is useful, but I believe this was already possible by hovering over the IP address.

What I want to see (please - no offence intended) is the domain name of the query made to that resolver, e.g. if server 208.78.70.136 is contacted to resolve something.example.com, I want to see the DNS record it was requesting, eg something.example.com.

That is NOT happening with the version I just installed (There is no version info on the maltrail screen, can't find one in the maltrail directory either)

This is how I install (after simply stopping maltrail and removing the folder)
# install sensor
git clone https://github.com/stamparm/maltrail.git
# install server
[[ -d maltrail ]] || git clone https://github.com/stamparm/maltrail.git

screenshot of what I'm seeing, after visiting https://github.com/stamparm/maltrail
![2019-07-02 11_48_05-Microsoft Edge](https://user-images.githubusercontent.com/24669386/60503308-b3c17f00-9cbf-11e9-99b6-16cb29b40ace.png)

**Comment by stamparm** [comment]
`I'm NOT sure you understood my request correctly, don't know if it is at all possible?` <- well, have you seen the https://user-images.githubusercontent.com/921555/60500166-24659d00-9cba-11e9-9499-1fc72bac112f.png. Does that look like something you've requested?

**Comment by stamparm** [comment]
Where did you get those `209.112.113.33`, `162.88.61.21`, etc?

**Comment by stamparm** [comment]
It goes like this. I believe that we've missed each other somewhere along the line of communication. There is something called "Rogue DNS" (trails file can be found [here](https://github.com/stamparm/maltrail/blob/master/trails/static/suspicious/rogue_dns.txt)). I thought that you are referring to those KNOWN malicious DNS servers and not to ALL IP trails.

To test the "real deal", please do something like the following (contacting the rogue DNS server):

`dig www.google.com @188.225.25.33`

**Comment by stamparm** [comment]
One more thing. I am not sure how you did the test that produced that results you've got. After I tried something like `dig www.google.com @209.112.113.33` I really got `...209.112.113.33 53 UDP IP "209.112.113.33 (www.google.com)" "known attacker" voipbl.org...` as an event.

Hence, those domain names that you've screenshot-ed are a result of a bad test. Those domain names were really sent (as I can see) to those IPs. Please use **appropriate testing** (e.g. `dig www.google.com @209.112.113.33`)

**Comment by jpgpi250** [comment]
I'm sorry for the confusion, I'll try to explain better.

I looked at your screenshot and was exited and confused, but tried the new release anyway.
In the trail field, I see `188.225.25.33` and the DNS name `www.google.com`. I assume `188.225.25.33` is a rogue DNS server, thus making it appear in the maltrail screen.

As explained before, I'm using unbound as a recursive DNS server witch means (not really using the correct terminology):
- client requests to resolve `www.google.com`
- unbounds sends a query to the root server, who has `google` in the `com` TLD
- rootserver replies: 8.8.8.8 servers the google domain
- unbound now sends a request to 8.8.8.8, IP address for `www`, if you please
- 8.8.8.8 replies `172.217.168.196` if `A`, `2a00:1450:400e:80d::2004` if `AAAA` was requested.
- unbound replies the result to the client.

This means unbound is talking to DNS servers all over the world, The servers that actually have the detailed information, NOT some ISP's DNS resolver, or a DNS provider such as OpenDNS.

Because of the way unbound operates, I get some (not a lot) maltrail alerts, as soon as unbound is trying to resolve a domain name, unbound contacts the servers holding the targeted zone.

The alerts in the screenshot I published, are simply the result of unbound doing it's work after opening a browser on my client and going to `https://github.com/stamparm/maltrail/issues/`

What I would expect of maltrail: when unbound finally contacts the server holding the actual DNS record AND it is a server that triggers mailtrail to make a log entry, is to see the address ( and possibly name of the DNS server) + the request that unbound made, e.g. if the DNS server (rogue example) is 145.145.145.145, that holds the zone for malware.com, maltrail would show 145.145.145.145 (dns1.malware.com) (request=www.maltrail.com)

P.S. if I execute `dig www.google.com @209.112.113.33`, I get (no IP address reported at all):

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> www.google.com @209.112.113.33
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 59989
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; Query time: 14 msec
;; SERVER: 209.112.113.33#53(209.112.113.33)
;; WHEN: Tue Jul 02 12:44:15 CEST 2019
;; MSG SIZE  rcvd: 43

If I use `dig www.google.com`, thus using default name resolution (unbound) I get (IP address resolved):

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64402
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         61      IN      A       172.217.168.196

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jul 02 12:45:33 CEST 2019
;; MSG SIZE  rcvd: 59

I hope I've addressed al your questions...

Thanks again, for your time and effort, and willingness to improve maltrail

**Comment by stamparm** [comment]
* Now I see what you want and it is generally something that is not inline with current Maltrail workflow.
* First of all, I believe that you've referred to "rogue" DNS (if I am not mistaken), while rogue DNS is a DNS server that is something completely different than you are asking for
* You are asking for the information on authoritative server for malware itself. That won't be implemented as that would introduce too much confusion. Majority of users don't have a slight idea what is an authoritative server. They would just be confused with an information that is being served where appears that Maltrail detects some IP contacting the client (or vice versa), while that same IP was contacted by the recursive server itself

**Comment by jpgpi250** [comment]
Somehow, with the latest version, it is displaying (not always) the information I want to see (screenshot)
![2019-07-02 14_00_10-Microsoft Edge](https://user-images.githubusercontent.com/24669386/60511353-060b9b80-9cd2-11e9-8da5-39aee0134e1d.png)

Thus maltrail is becoming more informative, but not always...

side notes
- version information in maltrail screen possible?
- on the GitHub page, I've enabled 'watch releases', but I'm not getting any notifications (on other GitHub pages, this works). Is this something you can (have to) fix?

**Comment by stamparm** [comment]
* `What is the best way to upgrade? ( I know stop both server and sensor, delete the maltrail folder, and reinstall)` - best way, used in own production environment, is to do an automatic once a day `git pull` and reset both server and sensor. You can find that info at https://github.com/stamparm/maltrail#best-practices
* `on the GitHub page, I've enabled 'watch releases', but I'm not getting any notifications (on other GitHub pages, this works). Is this something you can (have to) fix?` - with that setting, you should get info on new release, not each commit. Last official release was on Apr 30 2019.

**Comment by jpgpi250** [comment]
feature request: make sensor and server exit up op receiving SIGINT or other signal

**Comment by stamparm** [comment]
@jpgpi250 unreproducible:

![p1](https://user-images.githubusercontent.com/921555/60660133-5f510780-9e57-11e9-8cc1-a31ee6031b2f.png)
![p2](https://user-images.githubusercontent.com/921555/60660134-5f510780-9e57-11e9-9cd6-986f504e5208.png)
