### ISSUE TITLE
[lokibot] Idea for C2 heur detection

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#258]
Hello!

Lokibot C2 lists:

[0] https://pastebin.com/UGm39pdU
[1] https://pastebin.com/mgVvSRHi

and other findings show, that lokibot's C2s have constant properties: they end on ```/fre.php``` (the most often case) and ```PvqDq929BSx_A_D_M1n_a.php``` (sometimes). See #257 .

We can have MT's static trail ```lokibot.txt``` and some ```lokibot (heuristic)``` trail, based on detection of properties, mentioned above.

**Comment by stamparm** [comment]
I've already commented this at the pull-request for lokibot.txt update. Please don't do this kind of stuff as it could soon become a source of false-positives. Also, malware authors tend to change this between malware strains/versions. One more thing. Once the C2 is down, path itself is useless (there has to be a connection in the first place toward the C2)

**Comment by MikhailKasimov** [comment]
OK, will use path ```/fre.php``` manually.
