### ISSUE TITLE
Preventing IP blocked to be analyzed.

### ISSUE THREAD

**Issue by unixfox** [stamparm/maltrail#26]
When I want to block an attacker, I null route him with "route add" (http://www.cyberciti.biz/tips/how-do-i-drop-or-block-attackers-ip-with-null-routes.html) but even after he is still displayed on the web interface in the first position in the column "last seen".
Maybe you should add an option to hide automatically IP who has been blocked.

**Comment by stamparm** [comment]
@unixfox so, it is being logged on even after? I guess that I should ignore those "re-routes" to `127.0.0.1` (i.e. ignore all traffic to 127.0.0.1)

**Comment by unixfox** [comment]
Yes even after null route the attacker is still logged. I don't know why because I have already blocked him a few hours ago : 
>root@debian:/var/log# netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
103.19.88.162   127.0.0.1       255.255.255.255 UGH       0 0          0 lo

![](https://i.unixfox.eu/10-08-34.png)
(Time zone : CEST)

**Comment by stamparm** [comment]
I'll "patch" it later today. Logged on because capturing also for `127.0.0.1`

**Comment by stamparm** [comment]
@unixfox i hope that this will do. If not, I am not sure that I can do any more. My presumption is that in your case the `dst_ip` is being converted to `127.0.0.1`

**Comment by unixfox** [comment]
I hope too, I'll try when I've time.

**Comment by unixfox** [comment]
It works ! Thank you !
