### ISSUE TITLE
0.14 release tag for FreeBSD port

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#2676]
Hi,

as there were some changes lately maybe you want to tag a new release when you find the time, so I can update the FreeBSD port :)

In two weeks opnsense plugin will go to stable branch, hoping for plenty of community feedback.

Thanks,
Michael

**Comment by stamparm** [comment]
@mimugmail 

Tomorrow around this time. Just to test some changes inside the production environment.

**Comment by mimugmail** [comment]
No rush, thanks :)

**Comment by stamparm** [comment]
Done (https://github.com/stamparm/maltrail/releases)
