### ISSUE TITLE
False Positive?

### ISSUE THREAD

**Issue by adliwahid** [stamparm/maltrail#27]
Hi, 

I have the sensor and server on installed on the same box. 

It seems that a legitimate traffic to a feed server (vxvault) is flagged  as malicious (high).  

![fp](https://cloud.githubusercontent.com/assets/9648793/11897783/55c47eba-a5de-11e5-9dc9-f3f94f85d068.png)

Sorry if I am confused :-)

**Comment by darkwarriors** [comment]
it means that 213.186.33.5 has seen doing malicious traffic in the past, so that is a possible FP in your case due to old data in the trails (reference). What is the purpose of that OVH ip in your environment?

**Comment by stamparm** [comment]
2 events is of no great concern. That feed said that its connected to the malware. It could be triggered by some random ad(s) on some dummy web page. Maltrail is a tool which should be looked holistically,  like, you should immediately see if something is wrong or just a regular Internet noise. In your case it was only a slight noise

**Comment by adliwahid** [comment]
Thanks!

**Comment by darkwarriors** [comment]
i can confirm this is a FP due to trails download from vxvault my honeypot got hit by this outbound connection too.

**Comment by stamparm** [comment]
@darkwarriors you mean false positive or true positive?

**Comment by stamparm** [comment]
![111111111111111](https://cloud.githubusercontent.com/assets/921555/11973726/8f4b6e96-a95d-11e5-8c10-e7d87c9142b9.png)

**Comment by stamparm** [comment]
I'll just say for the record. One visit to the problematic IP is not a problem. Multiple and constant visits is a problem. Attaching an obvious malware victim traffic:

![rerererere](https://cloud.githubusercontent.com/assets/921555/11973761/f4702bc2-a95d-11e5-9098-f26548b670de.png)

**Comment by darkwarriors** [comment]
yep you are right just to inform that this IP is linked to a resource of vxvault where we download ip/domain reputation.
