### ISSUE TITLE
Enhancement: Windows Sensor

### ISSUE THREAD

**Issue by jdeplato** [stamparm/maltrail#29]
Hello!
Would be great if there was a Windows sensor for this. 
Use-Case: In most setups there is a mix of both Windows and Linux machines. I'd like to monitor both.

**Comment by 15w34r0n3D4y** [comment]
![maltrail_on_windows_7_64bit_errors](https://cloud.githubusercontent.com/assets/13278733/12013309/08862d78-ad14-11e5-9e51-4e2366665e55.png)

Server and sensor works but there is error... I have installed "pyopenssl" but error [see image RED] and with datacenters.csv [see image GREEN]

How fix it?

**Comment by stamparm** [comment]
@15w34r0n3D4y can you please make a single PCAP file (with e.g. some DNS traffic) on that problematic machine and send it to `miroslav@sqlmap.org`?

**Comment by 15w34r0n3D4y** [comment]
@stamparm ok I send file hope it's ok and thank you for helping and fast support.

**Comment by stamparm** [comment]
@15w34r0n3D4y everything looks fine, at least in the provided PCAP.

About those results you got. ICMP doesn't have ports. You are troubled about nothing.

**Comment by stamparm** [comment]
@15w34r0n3D4y p.s. to write in plainspeak, ICMP protocol doesn't use ports, hence there are no ports in attached screenshot
