### ISSUE TITLE
Magento trail for cosideration to add

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#290]
Hello!

[0] https://github.com/gwillem/magento-malware-scanner/blob/master/rules/burner-domains.txt

Here some domains are same to our static trail [1] https://github.com/stamparm/maltrail/pull/277 (e.g. ```magentocore.net```) , some are missing (e.g. [2] https://www.riskiq.com/blog/labs/magecart-keylogger-injection/), but many of them are unique.

[3] https://twitter.com/gwillem/status/1035791410014892034

So, I think [0] and [1] can be applicable in MT simultaneously.

**Comment by stamparm** [comment]
Done with latest commit
