### ISSUE TITLE
[content-security-policy] frame-src -> child-src error

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#2942]
Hello!

I have this error message on running MT on old Ubuntu 14.04 (yes!) + Firefox 57.0.1 (yes!).

![2019-07-21 14_12_24(1)](https://user-images.githubusercontent.com/7167300/61590480-c1816a80-abc2-11e9-8248-8aac06709018.png)

Some workaround?

**Comment by D9ping** [comment]
It's seems to be a problem with PapaParse.
Try changing:
default-src 'none'
to:
default-src 'self'
in the file: 
https://github.com/stamparm/maltrail/blob/376d114198f12617849d5a65e28f4f199f21d070/core/httpd.py#L160

**Comment by MikhailKasimov** [comment]
> 
> 
> It's seems to be a problem with PapaParse.
> Try changing:
> default-src 'none'
> to:
> default-src 'self'
> in the file:
> 
> https://github.com/stamparm/maltrail/blob/376d114198f12617849d5a65e28f4f199f21d070/core/httpd.py#L160

This works, thnak you! Can you, please, put PR for this as being founder of solution?

**Comment by MikhailKasimov** [comment]
![108638794-ab701600-7499-11eb-9e5e-7751c73e57eb](https://user-images.githubusercontent.com/7167300/170793103-c5ecd2d8-6b74-4a8b-9eec-0dc35801c60b.png)

**Comment by MikhailKasimov** [comment]
![108638794-ab701600-7499-11eb-9e5e-7751c73e57eb](https://user-images.githubusercontent.com/7167300/170795427-8989dafc-e2f6-4923-b81c-a2f1af19d0d5.png)
