### ISSUE TITLE
regexes failure

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#2943]
Hello!

Given:

MT: latest: 0.13.45
Trail: ```android_roamingmantis.txt```

1. Current regex: ```^security[a-z]{3}\-apple\.top$```
Domain to check: ```securityqwt-apple.top``` ( see https://twitter.com/ninoseki/status/1152885073357623298 )

I can change regex any way I wish:  ```security[a-z]{3}\-apple\.top$```, ```security[a-z]{3}\-apple\.top```, ```security[a-z]{3}-apple.top$``` and to open ```securityqwt-apple.top``` in browser -- result is the same in log (via ```cat /var/log/maltrail/2019-07-21.txt```):

```
"2019-07-21 15:06:56.202164" ubuntucomp 192.168.1.138 52429 192.168.1.1 53 UDP DNS (securityqwt-apple).top "domain (suspicious)" (static)
"2019-07-21 15:06:56.226686" ubuntucomp 192.168.1.138 38860 192.168.1.1 53 UDP DNS (securityqwt-apple).top "domain (suspicious)" (static)
"2019-07-21 15:12:07.119369" ubuntucomp 192.168.1.138 59337 192.168.1.1 53 UDP DNS (securityqwt-apple).top "domain (suspicious)" (static)
"2019-07-21 15:12:07.142218" ubuntucomp 192.168.1.138 32919 192.168.1.1 53 UDP DNS (securityqwt-apple).top "domain (suspicious)" (static)
```

2. Another case:  to open ```aa-bz.top``` in browser. Regex is ```^[a-z]{2}\-[a-z]{2}\.top$```.

Result:
```
"2019-07-21 15:49:07.960059" ubuntucomp 192.168.1.138 52481 192.168.1.1 53 UDP DNS (aa-bz).top "domain (suspicious)" (static)
"2019-07-21 15:49:08.007400" ubuntucomp 192.168.1.138 55604 192.168.1.1 53 UDP DNS (aa-bz).top "domain (suspicious)" (static)
"2019-07-21 15:49:08.011586" ubuntucomp 192.168.1.138 42040 192.168.1.1 53 UDP DNS (aa-bz).top "domain (suspicious)" (static)
"2019-07-21 15:49:08.036237" ubuntucomp 192.168.1.138 59674 192.168.1.1 53 UDP DNS (www.aa-bz).top "domain (suspicious)" (static)
```

So, even ```^``` sign doesn't work here.

I suspect, that regexes are also unworkable for other trails, that contain regexes-based detection records.

Please, try to reproduce it on your side. Thanks!

**Comment by MikhailKasimov** [comment]
@stamparm The same diagnose for 0.13.46 :(

**Comment by stamparm** [comment]
![2](https://user-images.githubusercontent.com/921555/61854924-6354d000-aebf-11e9-8e84-2593c15ae1ab.png)

![1](https://user-images.githubusercontent.com/921555/61854928-664fc080-aebf-11e9-988f-0b848a739aa5.png)

**Comment by stamparm** [comment]
Another example:

![4](https://user-images.githubusercontent.com/921555/61855328-2a692b00-aec0-11e9-88cc-0485d3f1b9cd.png)

![3](https://user-images.githubusercontent.com/921555/61855339-2ccb8500-aec0-11e9-8621-7405c159c29c.png)

**Comment by MikhailKasimov** [comment]
@stamparm 0.13.48 : https://youtu.be/ZonMHYJHjKA

**Comment by MikhailKasimov** [comment]
@stamparm A small reminder.
