### ISSUE TITLE
You can add these lists

### ISSUE THREAD

**Issue by pierrocknroll** [stamparm/maltrail#2980]
- https://www.projecthoneypot.org/list_of_ips.php?rss=1
- https://www.spamhaus.org/drop/drop.txt
- http://www.nothink.org/blacklist/blacklist_malware_http.txt
- http://www.nothink.org/blacklist/blacklist_ssh_all.txt
- http://antispam.imp.ch/spamlist
- https://dshield.org/ipsascii.html?limit=10000
- http://malc0de.com/bl/IP_Blacklist.txt
- https://www.binarydefense.com/banlist.txt
- http://www.talosintelligence.com/feeds/ip-filter.blf

Thanks

**Comment by stamparm** [comment]
Just to comment few of these:

* http://www.nothink.org/blacklist/blacklist_malware_http.txt - "Generated 2016-01-31 23:05:01 UTC"
* https://www.spamhaus.org/drop/drop.txt - huge network ranges
* http://antispam.imp.ch/spamlist - "Generated at Wed Feb  8 14:35:02 2017, timezone is CEST"
* http://malc0de.com/bl/IP_Blacklist.txt - "Last updated 2019-05-23"
...

Sorry, not huge fan of adding more IP blacklists
