### ISSUE TITLE
how to exclude low severity

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#3055]
Hi,

more and more OPNsense users are using maltrail and one of the guys was asking how to exclude attacks with severity `low` I know that you can search for `medium` of `high` but is there also a syntax like `!low`? Or maybe a config option so I can add it to the template?

Thanks! 
Michael

**Comment by stamparm** [comment]
https://github.com/stamparm/maltrail/issues/1772#issuecomment-489564706

**Comment by stamparm** [comment]
p.s. usage of `DISABLED_TRAILS_INFO_REGEX` will drastically reduce the total number of events. As said in referenced comment, I use it a (big) production environment to reduce all that noise coming from IP based trails

**Comment by mimugmail** [comment]
Thanks! I think I will implement a dropdown multiselect field to exclude feeds.
