### ISSUE TITLE
Whitelist doesn't appear to be working

### ISSUE THREAD

**Issue by DigiAngel** [stamparm/maltrail#31]
So here's what I got from my maltrail.conf:
~~~
USER_WHITELIST 127.0.0.1,localhost,71.21.81.200
~~~
But I continue to see this IP address in the list.  Sensor running in debug doesn't show anything.  I'm also specifically looking at the last seen time.  Thank you!

**Comment by stamparm** [comment]
Have you restarted sensor after changing configuration file? If yes, then it is a bug. Can you please send details of the problematic threat (e.g. screenshot of row with problematic threat/IP)

**Comment by DigiAngel** [comment]
Yes....restarted a few times...did a git pull this morning as well.  I do see whitelisting working in different environments (home), so I wonder if this might be the Cisco VLAN thing again.  In any case here's the screenshot...thank you!

![maltrail](https://cloud.githubusercontent.com/assets/947191/11936760/2b091bf4-a7cd-11e5-9fd7-4aeec5efbb12.jpg)

**Comment by stamparm** [comment]
Can't see from picture was the threat `heuristic` or something else?

**Comment by DigiAngel** [comment]
Threat type was IP...thank you :)

**Comment by stamparm** [comment]
@DigiAngel please update and retry

**Comment by DigiAngel** [comment]
Done :)  Will monitor...nice thicker sparklines and love the malicious ASN icon...nicely done.

**Comment by stamparm** [comment]
:)

**Comment by DigiAngel** [comment]
Hrmm...these appear to still be showing up:
~~~
"2015-12-21 23:16:44.100681" ids x.x.x.31 42904 72.21.81.200 443 TCP IP 72.21.81.200 "malware distribution (suspicious)" "malc0de.com (+binarydefense.com)"
"2015-12-21 23:16:44.100826" ids x.x.x.31 59385 72.21.81.200 443 TCP IP 72.21.81.200 "malware distribution (suspicious)" "malc0de.com (+binarydefense.com)"
"2015-12-21 23:16:51.278247" ids x.x.x.31 33248 72.21.81.200 443 TCP IP 72.21.81.200 "malware distribution (suspicious)" "malc0de.com (+binarydefense.com)"
~~~

Some session and tls info for the last hit (src port 33248):
~~~
2015-12-21T23:16:51+0000        CHqXOQ3U2J26Bj6Tr7      x.x.x.31  33248   72.21.81.200    443     tcp     ssl     82.728257       970     7997    SF      T       F       0       ShADadFf        11      1418    11      8445    (empty)

2015-12-21T23:16:51+0000        CHqXOQ3U2J26Bj6Tr7      x.x.x.31  33248   72.21.81.200    443     TLSv12  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256   secp256r1       iecvlist.microsoft.com  F       -       -       T       FzVFNs27QByTM9jJ94,F8HspA2KYNfDeuJDw1,FHAjW824xAVxerkd0b        (empty) CN=*.vo.msecnd.net      CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US -       -       16773   16789   17      T
~~~

Thank you.

**Comment by stamparm** [comment]
Strange, can't reproduce with the latest revision.

Can you please send me a PCAP (with related traffic) and corresponding `USER_WHITELIST`?

**Comment by DigiAngel** [comment]
Can do...capturing now.

**Comment by DigiAngel** [comment]
Ah dang....I had 71.21.81.200 in the whitelist, and the IP that's showing up is 72.21.81.200....my fault on this one...sorry...now correct in my whitelist...monitoring now...I'm an idiot 8-|

**Comment by DigiAngel** [comment]
Confirming this is working great now..thank you so much...sorry for the hassle.
