### ISSUE TITLE
Idea for 'long .php (suspicious)' heur trail

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#313]
Hello!

Looking on long random-sequenced name ```/tnmvqxxf9bmua2a6qbhpvc7k.php``` (see [0] https://twitter.com/PhishingAi/status/1037158782415994880) and ```//PvqDq929BSx_A_D_M1n_a.php``` (see ```lokibot.txt``` trail), I have an idea-question: can be this snippet of code from ```sensor.py``` for long domains heur detection also be applicable (after its modification, of course) to detect anomalies in php-endings like ```/something-long-and-random.php``` ?

```
if not result and config.USE_HEURISTICS:
            if len(parts[0]) > SUSPICIOUS_DOMAIN_LENGTH_THRESHOLD and '-' not in parts[0]:
                trail = None

                if len(parts) > 2:
                    trail = "(%s).%s" % ('.'.join(parts[:-2]), '.'.join(parts[-2:]))
                elif len(parts) == 2:
                    trail = "(%s).%s" % (parts[0], parts[1])
                else:
                    trail = query

                if trail and not any(_ in trail for _ in WHITELIST_LONG_DOMAIN_NAME_KEYWORDS):
                    result = True
log_event((sec, usec, src_ip, src_port, dst_ip, dst_port, proto, TRAIL.DNS, trail, "long domain (suspicious)",

```

**Comment by stamparm** [comment]
I have a feeling that this could cause lots of false-positives. I can check tomorrow at live environment

**Comment by MikhailKasimov** [comment]
OK, thanks!

**Comment by stamparm** [comment]
One day traffic (data for only unique PHP files - Note: including extension `.php`):

```
# NumSamples = 1904; Min = 5.00; Max = 61.00
# Mean = 13.554097; Variance = 38.075855; SD = 6.170564; Median 12.000000
# each ∎ represents a count of 11
    5.0000 -    10.6000 [   645]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
   10.6000 -    16.2000 [   831]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
   16.2000 -    21.8000 [   265]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
   21.8000 -    27.4000 [    80]: ∎∎∎∎∎∎∎
   27.4000 -    33.0000 [    51]: ∎∎∎∎
   33.0000 -    38.6000 [    21]: ∎
   38.6000 -    44.2000 [    10]: 
   44.2000 -    49.8000 [     0]: 
   49.8000 -    55.4000 [     0]: 
   55.4000 -    61.0000 [     1]: 
```

I manually checked those long names and they don't seem to be "malware" related (e.g. `obveznici-van-sustava-pdv-a-primanje-usluga-iz-inozemstva.php`, `ketogenic-diet-lemonade-without-sugar.php`, `include_compositeurs_similaires-index.php`, etc.)

Based on your samples and these results I can only conclude that this idea for "long php" heuristics would just produce either too many false-positives (e.g. check for length > 25) or too many false-negatives (e.g. check for length > 50)

**Comment by MikhailKasimov** [comment]
OK, got it. Thanks for testing!
