### ISSUE TITLE
[www.cruzit.com] feed is (possibly) dead

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#316]
Hello!

Please, re-check ```www.cruzit.com``` feed on your side. Seems, this feed is dead and is a candidate to be removed, meanwhile when MT sensor starts on my side, it returns ```something went wrong``` on retrieving this feed. And this is not for the first time.

Thanks!

**Comment by stamparm** [comment]
![screen](https://user-images.githubusercontent.com/921555/45153559-bacd4d00-b1d4-11e8-81c7-8eeff2c07b11.png)

**Comment by MikhailKasimov** [comment]
Hmm. you're lucky here. Thanks for re-check!
