### ISSUE TITLE
Limitations on pppoe interfaces? 

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#3785]
Hi,

are there any known limitations for pppoe devices? Maybe only FreeBSD affected, but I'm looking for any other confirmations. When I run maltrail on pyhiscal interfaces everything works fine, but when using pppoe there are no detections. I tried running sensor in foreground, no errors.
Currently I have no idea where to look further.

For reference:
https://github.com/opnsense/plugins/issues/1470

Thanks! 
Michael

**Comment by stamparm** [comment]
A) First impression is that the `UPDATE_PERIOD` contains some "fishy" value, as commented [here](https://github.com/opnsense/plugins/issues/1470#issuecomment-533457248). It should be evaluated to an integer, while it seems to contain something else than digits
B) It is quite possible that the `packet_handler` doesn't "handle" it well. You can see [here](https://github.com/stamparm/maltrail/blob/master/sensor.py#L949-L971) that the decapsulation in case of PPPOE is most probably being done in "heuristic" way. Maybe you could provide me with the wireshark/tcpdump of a sample traffic (couple of packets would be enough)
C) There is also a possibility for you to capture a content of one such `packet` inside the `packet_handler`, so I could have something to work on

**Comment by mimugmail** [comment]
https://github.com/stamparm/maltrail/commit/b06bd4ba69ad3bb58a668862e59c619dfaa66296

**Comment by mimugmail** [comment]
Thank you @stamparm really appreciated!

**Comment by stamparm** [comment]
No problem. Thank you for report it
