### ISSUE TITLE
Sensor and Server shutdown

### ISSUE THREAD

**Issue by stratonetworks** [stamparm/maltrail#38]
Hi, both of  services shutdown 2-3 hours since start up.
I launch it so:

python sensor.py &
python server.py &

What I doing bad ?

Regards!

**Comment by stamparm** [comment]
Can you please start them in screen or tmux instance and tell what's going on? Is there any error message?

**Comment by stratonetworks** [comment]
Sorry for the delay, Xmas ;-)
There is not error message, only the process           down (server and sensor). There is not difference starting server        or sensor firstly.
When I stand up servers, this is the capture:
![captura de pantalla de 2015-12-27 11 36 02](https://cloud.githubusercontent.com/assets/16427185/12009925/925f70e8-ac8f-11e5-8bdc-7358747afa97.png)
Thanks!

**Comment by stratonetworks** [comment]
Add at this issue, that i have another server only with sensor. It's debian Wheezy and the server (it's the above post) its Debian jessie. Both have same problem.

**Comment by stamparm** [comment]
Please update to the latest revision and rerun from the beginning.

When you see that one of them fails, please take a look into the `/var/log/maltrail/error.log` and write if you see anything there.

As a second "way", I would suggest you to put a hard value for the `CAPTURE_BUFFER` in `maltrail.conf` (e.g. `CAPTURE_BUFFER 100MB`) and rerun everything from start.

**Comment by stratonetworks** [comment]
Ok, I going to probe and  I will send feedback  on 24h.
Thank you!

**Comment by o-be-one** [comment]
Any news @stratonetworks ?

**Comment by stratonetworks** [comment]
Hi!

I Observed that this issue appear and disappears ramdonly. After update the version, the issue appears again twice, and on the server no more appears again, but on the client (only sensor) it repeat daily. On log I see this error:

![captura de pantalla de 2015-12-31 12 40 38](https://cloud.githubusercontent.com/assets/16427185/12064151/14f98064-afbc-11e5-9b05-b0720dc55f5c.png)

**Comment by kutus** [comment]
I see a similar error:
![error_maltrail](https://cloud.githubusercontent.com/assets/7306996/13314983/623c25da-dba8-11e5-99e6-30232f98bf49.png)

**Comment by stamparm** [comment]
@stratonetworks @kutus please read the http://stackoverflow.com/a/20997655

**Comment by stamparm** [comment]
As said, solution to this problem is described at http://stackoverflow.com/a/20997655

**Comment by stamparm** [comment]
p.s.:

```
sudo nohup ./sensor.py 2>&1 &
nohup ./server.py > /dev/null 2>&1 &
```
