### ISSUE TITLE
Sending logs to Logstash (ELK) and Local

### ISSUE THREAD

**Issue by ocuil** [stamparm/maltrail#40]
Hi there I think is good idea to let us setup in the config file config more than one "LOG_SERVER" or one LOG_SERVER and save that in local :-)

I use ELK solution and to let me use that with web server side I modify the "core/log.py" and in the section "def log_event(event_tuple)" in the first "if":

if config.LOG_SERVER:
                remote_host, remote_port = config.LOG_SERVER.split(':')
                s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                s.sendto("%s %s" % (sec, event), (remote_host, int(remote_port)))

I add:

                handle = get_event_log_handle(sec)
                os.write(handle, event)

Then now I can send and save the logs :-)

What do you think about that improvement ?

Thanks a happy holidays

**Comment by stamparm** [comment]
Now there is a new option `DISABLE_LOCAL_LOG_STORAGE` which is by default turned off. That means that now you can use `LOG_SERVER` and without turning on the option `DISABLE_LOCAL_LOG_STORAGE` you'll get logs stored both locally and remotely

**Comment by MikhailKasimov** [comment]
@ocuil Meet also ```LOGSTASH_SERVER=``` option in ```/maltrail.conf``` : https://twitter.com/maltrail/status/1341500268798742529
