### ISSUE TITLE
Problem with logging (i think)

### ISSUE THREAD

**Issue by o-be-one** [stamparm/maltrail#42]
Hello stamparm,

i'm glad to discover this tool, could be useful to use it. That's why i've started to try it and at this time i'm not able to do what is it supposed to do.

First of all, i've nothing on the webserver, saying there's no event. But the calendar show event and the number increase.
I've started in debug, it's an ubuntu 14.04.

To begin, in documentation, you don't use sudo to start the webserv daemon, and i got a perm error to read logs. It could be awesome to dos something who will work at the begin without needs of chown or chmod.

And the problem i have when starting the webserver as sudo/root : 
```
[i] starting HTTP server at 'http://0.0.0.0:8338/'
[o] running...
Traceback (most recent call last):
  File "/home/admin/maltrail/core/httpd.py", line 514, in _counts
    current = datetime.datetime.strptime(os.path.splitext(os.path.basename(filename))[0], DATE_FORMAT)
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'error' does not match format '%Y-%m-%d'
```

My sensor log file looks like this : 
```
"2015-12-29 03:57:27.818642" maltrail 149.202.238.199 41049 92.x.x.x 8888 TCP IP 149.202.238.199 "bad reputation (malicious)" alienvault.com
"2015-12-29 03:59:53.915040" maltrail 92.x.x.x - 136.161.101.53 - ICMP IP 136.161.101.53 "conficker (malware)" (static)
"2015-12-29 04:03:56.389039" maltrail 92.x.x.x - 136.161.101.53 - ICMP IP 136.161.101.53 "conficker (malware)" (static)
```

I'm trying too to put a sensor on an other server, but actually it's not able to send logs to webserver. I'll tell you more in other ticket if i don't find how to fix this.

Thanks again for this good job.

**Comment by stamparm** [comment]
1) That `ValueError` is patched now. I hasn't caused problems (shown only on `SHOW_DEBUG`)
2) `To begin, in documentation, you don't use sudo to start the webserv daemon, and i got a perm error to read logs. It could be awesome to dos something who will work at the begin without needs of chown or chmod.` - if you start sensor first (which requires sudo privileges) it should put all necessary permissions so the server could read logs without any problems. I have thought about this before and this should be implemented.

But.. If you say that you have `perm error to read logs` can you please give some more details. Has there been any error message?

**Comment by o-be-one** [comment]
It seems to appears only with the current day logs :
```
[i] using configuration file '/home/admin/maltrail/maltrail.conf'
[i] running UDP server at '0.0.0.0:8337'
[i] starting HTTP server at 'http://0.0.0.0:8338/'
[o] running...
Traceback (most recent call last):
  File "/home/admin/maltrail/core/log.py", line 97, in handle
    handle = get_event_log_handle(int(sec))
  File "/home/admin/maltrail/core/log.py", line 41, in get_event_log_handle
    _thread_data.event_log_handle = os.open(_thread_data.event_log_path, flags)
OSError: [Errno 13] Permission denied: '/var/log/maltrail/2015-12-30.log'
```

**Comment by stamparm** [comment]
@o-be-one you are right. There was a bug in case of non-sudo usage of `server.py` if `UDP_SERVER` is set up. Now you are being warned in such cases to run it in `sudo` environment

**Comment by o-be-one** [comment]
Thank you, good job, happy to see that you are active and listening users :).
