### ISSUE TITLE
Filtering requests

### ISSUE THREAD

**Issue by DigiAngel** [stamparm/maltrail#43]
Would love to be able to filter by a port number.  Would be nice also to have src/dst/port/protocol filtering like maybe something below:

USER_WHITELIST src_192.168.1.1_tcp_25
USER_WHITELIST src-192.168.1.1-udp-53

Thank you.

**Comment by arons** [comment]
have a look to: https://github.com/stamparm/maltrail/commit/bdfed1ae8622d3c6a5ffdcbac058956a103bb5d0

you can now ignore some events based on source/destination ip and port.
See https://github.com/stamparm/maltrail/blob/master/misc/ignore_events.txt for syntax and examples.

**Comment by MikhailKasimov** [comment]
Done via https://github.com/stamparm/maltrail/commit/bdfed1ae8622d3c6a5ffdcbac058956a103bb5d0
