### ISSUE TITLE
pua.txt blocking github.com

### ISSUE THREAD

**Issue by p1r473** [stamparm/maltrail#4373]
Hi,
Can you please comment out the following line in pua.txt as it is causing github.com to be blocked when using this list in Pihole ad blocker
It seems most reference lines you commented except this one

https://github.com/advanced-threat-research/IOCs/blob/master/2014/2014-12-16-installcube-how-russian-programmers-turn-adware-into-cash/installcube-how-russian-programmers-turn-adware-into-cash.csv

**Comment by MikhailKasimov** [comment]
Hello! Seems, my fault, sorry. Should be fixed in https://github.com/stamparm/maltrail/pull/4374/commits/8f4f8c73d4901ce3e711a9bfdd609a06ff7e0ee6
