### ISSUE TITLE
Add a link to go back to home on the top left logo

### ISSUE THREAD

**Issue by o-be-one** [stamparm/maltrail#45]
Hello,

could be useful to have a buton to click to go back to the main view, without the need to clear the filter.

Thank you !

**Comment by stamparm** [comment]
Just a question. By back home you mean reload everything with today's date data and reset all filters and graph views?

**Comment by o-be-one** [comment]
Yes, the root url, the first page you see when you connect to website.

**Comment by o-be-one** [comment]
Oh i've checked, please add the "altrail" after the logo to as link if possible.

**Comment by stamparm** [comment]
@o-be-one done ;)

**Comment by o-be-one** [comment]
Thank you :)
