### ISSUE TITLE
unpack requires a string argument of length 8

### ISSUE THREAD

**Issue by YSmetana** [stamparm/maltrail#47]
Hi! Thanks for you work.

Trying to run the system on FreeBSD 10.0-RELEASE (Python 2.7.6). Default configs. Got this traceback:

    root@iota:/tmp/3/maltrail-master # python2.7 sensor.py
    Maltrail (sensor) #v0.8.359

    [i] using configuration file '/tmp/3/maltrail-master/maltrail.conf'
    [i] using '/var/log/maltrail' for log storage
    [?] at least 512MB of free memory required
    [i] loading trails file...
    [i] 867,140 trails loaded
    [x] virtual interface 'any' missing. Replacing it with all interface names
    [i] opening interface 'em0'
    [i] opening interface 'taurus0'
    [i] opening interface 'libra0'
    [i] opening interface 'em0.5'
    [i] opening interface 'em0.100'
    [i] opening interface 'em0.101'
    [i] opening interface 'em0.102'
    [i] opening interface 'em0.103'
    ...
    [i] opening interface 'em0.600'
    [i] opening interface 'lo0'
    [i] setting filter 'ip and (not tcp or (tcp[13] == 2) or (tcp[13] & 8 != 0))'
    [i] creating 1 more processes (2 CPU cores detected)
    [?] please install 'schedtool' for better CPU scheduling
    [o] running...
    Process 0:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/tmp/3/maltrail-master/core/parallel.py", line 92, in worker
        sec, usec = struct.unpack("=II", content[:8])
    error: unpack requires a string argument of length 8
    [x] Ctrl-C pressed

The server starts fine:

    root@iota:/tmp/3/maltrail-master # python2.7 server.py
    Maltrail (server) #v0.8.359

    [i] using configuration file '/tmp/3/maltrail-master/maltrail.conf'
    [i] starting HTTP server at 'http://0.0.0.0:8338/'
    [o] running...

The web-interface is up and running. I can see some threats there. But data doesn't update. It seems it analyse the traffic once (when starting) and then stops.

Can this error *"error: unpack requires a string argument of length 8"* cause the problem? Tnx!

**Comment by YSmetana** [comment]
OK now. I have set the exact interface name, instead of "any". But I have a lot of interfaces...

**Comment by stamparm** [comment]
@YSmetana it seems that you have problems with multiprocessing. You could temporary disable it in maltrail.conf with `USE_MULTIPROCESSING false`

**Comment by stamparm** [comment]
@YSmetana you'll probably be fine with `any`. Otherwise, you can use comma separated value for `MONITOR_INTERFACE` (e.g. `MONITOR_INTERFACE eth0, eth1`)

**Comment by stamparm** [comment]
@YSmetana with latest commit(s) your issue should disappear
