### ISSUE TITLE
Cannot look at one day ago - No connection to the server

### ISSUE THREAD

**Issue by erikbotta** [stamparm/maltrail#48]
One day all was OK. Also I could look one day back. Now when I want to do it still got the same error as in Screenshot.
No exception in screen process with server none in error.log.
After reload all is OK, but I can see only today.
![maltrail_error](https://cloud.githubusercontent.com/assets/832402/12144941/53bd3c22-b48b-11e5-8ad3-03aace23d1a8.png)

**Comment by stamparm** [comment]
What do you get when you visit the `<server_ip:server_port>/ping` (e.g. http://localhost:8338/ping) from browser?

**Comment by stamparm** [comment]
Also, can you please tell me which browser do you use?

**Comment by erikbotta** [comment]
17pong

But I have to say that this problem is gone after some hours. Strange.

I use for it latest stable Chrome

**Comment by stamparm** [comment]
Well, not sure how to reproduce. I'll have this on my mind

**Comment by erikbotta** [comment]
OK me to. Maybe some data in some time . I will look at it. I am professional tester and your app is good for us so I will test it complete anyway. Thx
