### ISSUE TITLE
Maltrail sensor use a bunch of my ram after a long period of running.

### ISSUE THREAD

**Issue by unixfox** [stamparm/maltrail#49]
My sensor was running since 26 december and I saw that the process "sensor" was using 60% of my total ram (2GO).
I don't really know why it using so much ram because if I restart it, sensor now use only 13% of my ram.

>root@unixfox:~# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     16893  0.0 39.9 1080768 837880 ?      Ssl   2015  10:08 /usr/bin/python2 /root/maltrail/sensor.py
root     16896  0.9 21.9 994892 461316 ?       Sl    2015 146:11 /usr/bin/python2 /root/maltrail/sensor.py

**Comment by stamparm** [comment]
Two things are important here:

1) After last updates (1-2 days ago) sensor now uses less memory than before
2) If multiprocessing is used then the mechanism `mmap` is used (for capture buffering) which is not filled immediately (it is being filled with the traffic data). This `mmap` mechanism depends on `CAPTURE_BUFFER` setting

Now my question is what's your value of `CAPTURE_BUFFER` and how much total RAM do you have on that machine?

**Comment by unixfox** [comment]
I didn't tried the last updates, `CAPTURE_BUFFER` is set on 20%.

I'll close the issue and if I've again the same ram problem I'll reopen it.

**Comment by stamparm** [comment]
In some point of time I'll just decide to fill up the `mmap` buffer all at once to prevent this kind of "problems"

**Comment by stamparm** [comment]
@unixfox with the latest revision `mmap` buffer is filled all at once. This is safer to do at start to prevent unexpected problems later (memory exhaustion)
