### ISSUE TITLE
new features added in forked maltrail_dev

### ISSUE THREAD

**Issue by darkwarriors** [stamparm/maltrail#5]
these are only my 2cents, unfortunately i usually use bitbucket for my "projects", so i show you what i have added to your very good project for meet my needed inside my honeynet sensor:
- i have just added User-Agent Heuristic as an optional configuration that can or cant be activated
- it will check UA for various string for Malware, Scanner, Crawler, Attacker
- it will report it in log because i think that UA will be a good information during IR for every type of HTTP events, so IMHO it could be added to all other HTTP Heuristic events if you think that can be useful.
- next improvement i think that will be to switch from regex to a trail so we can treat UA like IP and Domain with some auto updating feeds.

https://bitbucket.org/n3ophyte/maltrail_dev/commits/branch/develop-ua

i can recreate it in github and then make a pull-request to a development branch of your repo if you think that this can also by useful for you, obv iam not a developer so if you think that there will be a better way to deal with this implementation no problems :) 

my next development will be to create a python instance and a caching mechanism for scanning all logfiles for create a single JSON  document that contains all historical matches for further search and a better overview of aggregate data that every sensor are collecting, something like:
```
[IP/Domain] { 
     [first_seen]
     [last_seen]
     [hits]
     [UA] { [1] => .. [2] => ... }
     [Reliability] = from 10 to 0
}
```
Reliability can be from 10 to 0, where 10 is added when we first add this information to the JSON document and then every day or two (or whatever we think that could be a good security timeframe) we decrease that number if we dont see that object anymore in the sensor...
this could be integrated in the portal so we have a single method for searching all the events over the time without scanning billions of lines of files that can contains many time the same ip/domain/url

**Comment by stamparm** [comment]
There are some great ideas here.

Will refactor the code and include it. Also, you gave me the idea to switch
from TRAIL.URL to TRAIL.HTTP as a type for all those HTTP related events
like your UA and URL from before.

Will keep you posted in next couple of days.

Hide thanks for your efforts.

Bye

**Comment by stamparm** [comment]
@darkwarriors you've incorporated `pcapy.DLT_PPP` as support datalink type, while without proper stripping of header inside the `_process_packet(packet, sec, usec)`. I really don't know how to strip it to get to the ETH/IP parts. Googling around I can't find good info on it

**Comment by darkwarriors** [comment]
hi @stamparm i have just added it because of some of my honey use 3G,4G connection with ppp0 ethernet interface, adding that datalink let me correctly parse IP traffic without any further addition, am i wrong ?

**Comment by stamparm** [comment]
problem is that the packet needs to be dissected manually to get to the ETH layer. For example, in the following couple of lines, in case of `pcapy.DLT_LINUX_SLL` first 2 bytes are discarded accordingly:

```
def _process_packet(packet, sec, usec):
    """
    Processes single (raw) packet
    """

    global _connect_sec

    try:
        if _datalink == pcapy.DLT_LINUX_SLL:
            packet = packet[2:]

        eth_header = struct.unpack("!HH8sH", packet[:ETH_LENGTH])
        eth_protocol = socket.ntohs(eth_header[3])
```

**Comment by stamparm** [comment]
@darkwarriors if you could send me such sample packet capture (PPP) to the `miroslav.stampar@gmail.com` it would be great. Only couple of packets would do

**Comment by darkwarriors** [comment]
yes sure but i need to do it while come back from my day work, i'll try to send you a short pcap asap.

**Comment by stamparm** [comment]
@darkwarriors np. no hurry.

**Comment by stamparm** [comment]
@darkwarriors majority of your ideas is implemented now. Can you please take a look and give your opinion?

I haven't included `SUSPICIOUS_UA_COMMAND_REQUEST_REGEX` as I am not sure about the usability. If you believe that this is something of importance, maybe some generic approach could be done (for all header values)

**Comment by stamparm** [comment]
@darkwarriors this issue is delicate. I've seen tons of false positives on a live 1Gbps :). Regular user requests like `Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)` are marked as suspicious (malware). Those regexes should be carefully scrutinized.

**Comment by stamparm** [comment]
@darkwarriors I've made two new options (which you'll possibly find useful for your use-case):

`USE_SHORT_OR_MISSING_USER_AGENT` <- event in case of short or missing user agent header
`USE_MISSING_HOST` <- event in case of missing host header

**Comment by darkwarriors** [comment]
ok i'am testing it on 5 honey sensor. i used for a while my dev branch into my honey servers and i didnt spot any false positive for that UA, but you should be right because with my honey i catch only attacks coming from the internet and i didnt inspect client traffic that could be generate a lot of FP for that UA that i saw long time ago used by ZeroAccess Botnet (i'am trying to find the pcaps that link to that UA's if you need that).

Thanks as usual for your very good work and for the code refactoring!

**Comment by darkwarriors** [comment]
shouldn't be better to have two separate REGEX patterns for the UA, one coming from the scanner/attackers/bot and one for suspicious activity from inside to outside the network like malware, spyware, toolbar etc? 
i think that it will be more manageable and more clear for future update to have that type of separation even we can decide to enable one of them or both with a specific configuration, what do you think about that? this is why i have chosen to separate the regex patterns in my first development branch: https://bitbucket.org/n3ophyte/maltrail_dev/src/8118d460dcf8bdff3a7c2a2019ed8e943bb9de1d/core/settings.py?at=develop-ua&fileviewer=file-view-default from line 56 to 58

**Comment by stamparm** [comment]
@darkwarriors it goes like this. Majority of "suspicious" user agents are coming from bots. Others, that are not "bots" are something in between. There are no clear "malware" user-agents IMO. I've tried to include non-bot user agents into a real traffic and there were tons of false-positives.

In short, it is really hard, and maybe impossible to make "malware" user agents

**Comment by stamparm** [comment]
@darkwarriors ping? Can you please pinpoint and/or research what would be the most interesting "malware" user-agents?

**Comment by darkwarriors** [comment]
sorry about the delay I'am on vacation period :) there are several sources from which we can take some information, like VRT labs snort rules (user-agents.rules) or EmergingThreat Ruleset (ET MALWARE , ET TROJANS, ET INFO) or as i did in my SIEM by taking info from this kind of web site/ traffic:

http://networkraptor.blogspot.it/2015/01/user-agent-strings.html
http://www.malware-traffic-analysis.net/2015/01/27/index.html
http://www.malware-traffic-analysis.net/2015/01/22/index.html

obv i understand your point, my idea was just to be more flexible if a malware detection through UA can be a good Heuristic approach with also some other header inspection because i'am using that by hunting log data from Bro, but as you wrote can be leverage to a lot of FP, that is why i thought  to leave it as an option to the end user to enable or disable this heuristic outbound functionality.

**Comment by stamparm** [comment]
I'll do my best here, but I am afraid of too many false positives.

Good place for this topic:

http://doc.emergingthreats.net/bin/view/Main/WebSearch?search=Suspicious+User-Agent&scope=all&web=Main

**Comment by stamparm** [comment]
Also,

http://doc.emergingthreats.net/bin/view/Main/WebSearch?search=ET+MALWARE+User+Agent&scope=all&web=Main

**Comment by stamparm** [comment]
Closing this down as lots of work has been "assimilated". Also, @darkwarriors is now contributing actively (by using Github account :)

**Comment by darkwarriors** [comment]
sorry about this, but i hate JS and i am not able to help you by fixing it by my self so sad about that!
there is ony a little fix due to a long UA displayed, i attach you the image if we can use the same mechanism that you do for multiple trail:

<img width="1247" alt="screen shot 2015-12-18 at 3 53 22 pm" src="https://cloud.githubusercontent.com/assets/1184000/11899493/9e88c87a-a59f-11e5-9417-85854a28e599.png">

**Comment by stamparm** [comment]
@darkwarriors no worry. can do that (also thought about it). only thing is that i am not sure what's the right way to do it. whether to just isolate the "problematic part" and hide the rest, or plain simply hide the rest of the overlong string

**Comment by darkwarriors** [comment]
for me the better solution will be a button that i can click to show all the UA like it already happen for the heuristic one when we have multiple match for the same IP. am i right?

**Comment by stamparm** [comment]
Ok. Will do

**Comment by stamparm** [comment]
@darkwarriors it should be better now
