### ISSUE TITLE
error.log flooded with Received unexpected datalink (186)

### ISSUE THREAD

**Issue by Northguy** [stamparm/maltrail#5183]
Hi,

my error.log is flooded with " Received unexpected datalink (186)". It logs 8 lines of  _2019-11-26 10:17:31 Received unexpected datalink (186)_ per second.

Cannot get a clue on root cause, but is causing excessive CPU load when enabling Maltrail on my APU Opnsense firewall. Any pointers as to how to debug or resolve?

**Comment by MikhailKasimov** [comment]
Hello! What is MT version you currently use? This seems to be related to https://github.com/stamparm/maltrail/issues/3570

**Comment by Northguy** [comment]
Hi,

I am using OPNsense 19.7.7-amd64
With Maltrail Plugin os-maltrail v1.2
which seems to use Maltrail package version 0.16

Might it be that the plugin is not using the latest released Maltrail version ?

**Comment by stamparm** [comment]
@Northguy there are two patches that have to be done here. First one as a "fast" patch to throttle this kind of "behavior", second one related to the root of cause (unexpected datalink)

**Comment by stamparm** [comment]
@Northguy when I look into #3570 (as @MikhailKasimov mentioned), I can see that there is no need for "second patch". Please update to the latest revision and rerun everything
