### ISSUE TITLE
Filter by Severity High

### ISSUE THREAD

**Issue by Dededus** [stamparm/maltrail#52]
When I filter with the word "high" or when i click "high" in the severity column not only filter "high" because in the info column we have "high consonant no such domain name".

**Comment by stamparm** [comment]
@Dededus you are right. Have to find proper substitution

**Comment by stamparm** [comment]
@Dededus p.s. also, I am now on vacation so I haven't had a chance to test it in production (so, unaware of potential problems with recent changes)

**Comment by Dededus** [comment]
Perfect!! Thanks stamparm!

**Comment by stamparm** [comment]
It should be ok now. Substituted "high consonant" with "consonant threshold" and "high entropy" with "entropy threshold". Though, your previous events/threats will stay as they were

**Comment by Dededus** [comment]
Works perfect!!! Thanks!!
