### ISSUE TITLE
False positive , tcpdump show nothing

### ISSUE THREAD

**Issue by erikbotta** [stamparm/maltrail#54]
Hello I see on some of our servers communicate at the same time for a week to the same IP (simda it says). When I run tcpdump filtered to that external IP : maltrail show that connection again but tcpdump shows nothing on external adapter.
![false-positive](https://cloud.githubusercontent.com/assets/832402/12321006/1e02d660-baac-11e5-8d46-53c64e1a4a69.png)

**Comment by stamparm** [comment]
So, you are running tcpdump on sensor, right? Do you use an internal proxy? If so, then maltrail extracts connection attempts from proxy requests (too)

**Comment by erikbotta** [comment]
It is little bit complicated. Sensor and tcpdump are running on host OS(linode virtual server) at screen procceses. But on the same host there're many docker containers with docker0 adapter. There's no internal proxy.

**Comment by stamparm** [comment]
Well, there are connection attempts for sure.

Now, it might me a false positive (in terms of a malware threat), it might be not. For example: http://www.bfk.de/bfk_dnslogger.html?query=213.186.33.5 and https://myip.ms/info/whois/213.186.33.5 say that there are lots of domains there. Also, https://www.virustotal.com/en/ip-address/213.186.33.5/information/ says that this really might be something malicious.

Most interesting thing is that you say that they communicate at the same time. Normally, I would say that this are MX traffic attempts, but port 80 is used.

Don't know how to help you here. Maybe I could help you somehow in maltrail for you to dump the problematic packages (from there)?

**Comment by erikbotta** [comment]
For me it could be great to know what process is opening that socket. And I am consterned that tcpdump is showing no communication to that address. For now I am working on better iptables to default deny outgoing traffic but now I must find that process if it is real.

**Comment by erikbotta** [comment]
![pstree](https://cloud.githubusercontent.com/assets/832402/12321510/abf3222a-baae-11e5-843f-5f98f2a89768.png)

This is how it is on the most easy server. One is sensor and one tcpdump.

**Comment by stamparm** [comment]
How do you run `tcpdump` (which options/switches) and what's your value for `MONITOR_INTERFACE` in maltrail.conf?

**Comment by erikbotta** [comment]
tcpdump host 213.186.33.5 -w /root/searching.txt

MONITOR_INTERFACE any

**Comment by stamparm** [comment]
Can you please retry with:

`tcpdump -i any -w /root/searching.txt host 213.186.33.5`

I'll just show you the difference:

A) without any:
![1](https://cloud.githubusercontent.com/assets/921555/12321711/ed7e7702-baaf-11e5-8609-9de52329bc84.png)

B) with any:
![2](https://cloud.githubusercontent.com/assets/921555/12321719/f7bebb14-baaf-11e5-9e42-7e0b23bae4b2.png)

Can you see it? Without any only the first interface (in this case `eth0`) is monitoried

**Comment by erikbotta** [comment]
Oh I'll try and wait to 17:20 :) Thx for help!

**Comment by erikbotta** [comment]
OK. 14.1. At the same time on 3 servers same thing. But tcpdump(with -i any) still empty. Is there a chance to debug this on sensor?

**Comment by stamparm** [comment]
With the latest commit I've added support for `plugins`. Please update and take a look into `plugins/peek.py`.

For your case I would suggest:

```
cat > /tmp/simda_peek.py << "EOF"
#!/usr/bin/env python

import re
import sys
import string
import time

TIME_FORMAT = "%Y-%m-%d %H:%M:%S"

def plugin(event_tuple, packet=None):
    sec, usec, src_ip, src_port, dst_ip, dst_port, proto, type, trail, info, reference = event_tuple
    if packet and "simda" in info:
        localtime = time.strftime(TIME_FORMAT, time.localtime(int(sec)))
        output = "\n%s %s:%s -> %s:%s:\n" % (localtime, src_ip, src_port, dst_ip, dst_port)
        output += "%s\n" % "".join(_ if _ in string.printable else '.' for _ in packet)
        sys.stderr.write(output)
        sys.stderr.flush()
EOF

sudo python sensor.py -p /tmp/simbda_peek.py
```

In my case, when I run it like that, I get for `curl 85.13.129.76` the following console output:

```
$ sudo python sensor.py -p /tmp/simda_peek.py
Maltrail (sensor) #v0.9.45

[i] using configuration file '/home/stamparm/Dropbox/Work/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[?] at least 384MB of free memory required
[i] loading trails file...
[i] 914,088 trails loaded
[?] in case of any problems with packet capture on virtual interface 'any', please put all monitoring interfaces to promiscuous mode manually (e.g. 'sudo ifconfig eth0 promisc')
[i] opening interface 'any'
[i] setting capture filter 'ip'
[i] creating 3 more processes (4 CPU cores detected)
[o] running...

2016-01-15 13:11:13 192.168.0.107:53470 -> 85.13.129.76:80:
.L...P...+Z..!....*m...........kU
.(n.18..

2016-01-15 13:11:13 85.13.129.76:80 -> 192.168.0.107:53470:
.L...k.P..Z.. ...+..8..).........
18...(n.....

2016-01-15 13:11:13 192.168.0.107:53470 -> 85.13.129.76:80:
.L...P...*......r.W............kU
.(n.........

2016-01-15 13:11:13 192.168.0.107:53470 -> 85.13.129.76:80:
.L...P...+Z..!.............h...kU
.(n.18..GET / HTTP/1.1
User-Agent: curl/7.35.0
Host: 85.13.129.76
Accept: */*



2016-01-15 13:11:13 192.168.0.107:53470 -> 85.13.129.76:80:
.L...P...wZ.......(d...........kU
.(n.18..

2016-01-15 13:11:13 85.13.129.76:80 -> 192.168.0.107:53470:
.L...k.P..Z..!...w...r*......
18...(n.

2016-01-15 13:11:13 85.13.129.76:80 -> 192.168.0.107:53470:
.L...k.P..Z......x...r(......
18...(n.

2016-01-15 13:11:13 85.13.129.76:80 -> 192.168.0.107:53470:
.L...k.P..Z......w...r(......
18...(n.

2016-01-15 13:11:13 85.13.129.76:80 -> 192.168.0.107:53470:
.L...k.P..Z..!...w...ra(.....
18...(n.HTTP/1.1 503 Service Unavailable
Date: Fri, 15 Jan 2016 12:11:13 GMT
Server: Apache
X-Powered-By: PHP/5.4.45-nmm1
Retry-After: 3600
Vary: Accept-Encoding
Content-Length: 184
Connection: close
Content-Type: text/html

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Temporarily Unavailable</title>
</head><body>
<h1>Service Temporarily Unavailable</h1>
</body></html>

2016-01-15 13:11:13 192.168.0.107:53470 -> 85.13.129.76:80:
.L...P...wZ.......(b...........kU
.(n.18..
```
