### ISSUE TITLE
pcap import

### ISSUE THREAD

**Issue by bergernetch** [stamparm/maltrail#55]
I wonder if it would be possible to create a "sensor" to import already existing pcap files? This would provide for an easy way to analyze already recorded traffic.
What would be the best way to implement this?

**Comment by stamparm** [comment]
I can do it, but in couple of days. Only problems are: A) multiple runs will generate duplicated events and B) events will be filled into the respective date (not today) - so user should expect this

**Comment by stamparm** [comment]
p.s. both A and B are something intuitive, I would just like users to deduce this (without raising new Issues) :)

**Comment by stamparm** [comment]
With latest commit:

```
$ python sensor.py -h
Maltrail (sensor) #v0.9.34

Usage: sensor.py [options]

Options:
  --version       show program's version number and exit
  -h, --help      show this help message and exit
  -c CONFIG_FILE  Configuration file (default: 'maltrail.conf')
  -p PCAP_FILE    Open pcap file for offline analysis
```

**Comment by stamparm** [comment]
```
$ python sensor.py -h
Maltrail (sensor) #v0.9.34

Usage: sensor.py [options]

Options:
  --version       show program's version number and exit
  -h, --help      show this help message and exit
  -c CONFIG_FILE  configuration file (default: 'maltrail.conf')
  -p PCAP_FILE    open pcap file for offline analysis
  --console       print events to console (too)
```

```
$ sudo python sensor.py --console -p /tmp/output.pcap
Maltrail (sensor) #v0.9.34

[i] using configuration file '/home/stamparm/Dropbox/Work/maltrail/maltrail.conf'
[i] using pcap file '/tmp/output.pcap'
[i] using '/var/log/maltrail' for log storage
[?] at least 384MB of free memory required
[i] loading trails file...
[i] 914,217 trails loaded
[i] setting capture filter 'ip'
[i] creating 3 more processes (4 CPU cores detected)
[o] running...
"2016-01-14 14:09:00.534953" Laptop 192.168.0.107 44823 8.8.4.4 53 UDP DNS jebena.ananikolic.su "palevo (malware)" (static)
"2016-01-14 14:09:01.106003" Laptop 192.168.0.107 37859 8.8.4.4 53 UDP DNS jebena.ananikolic.su "palevo (malware)" (static)
"2016-01-14 14:08:59.696892" Laptop 192.168.0.107 58631 8.8.4.4 53 UDP DNS jebena.ananikolic.su "palevo (malware)" (static)
```

**Comment by crazyintern** [comment]
Question here... I have tried following instructions _sudo python sensor.py --console -p /tmp/output.pcap but I was not able to get the same output. First, when I ran sudo ./sensor.py --console -p /home/KMG/Downloads/2013-10-28-Sibhost-EK-traffic.pcap

[*] starting @ 23:14:31 /2021-08-07/

[i] using configuration file '/home/KMG/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[i] using '/root/.maltrail/trails.csv' for trail storage (last modification: 'Sat, 07 Aug 2021 22:04:41 GMT')
[i] loading trails...
[i] 1,938,210 trails loaded
[!] empty file '__init__.py' required inside directory '/home/KMG/Downloads'

and next, when I included '__init__.py' file, and ran the same command, I have received the following.
#
Maltrail (sensor) #v0.36.3 {https://maltrail.github.io}

[*] starting @ 23:15:22 /2021-08-07/

[i] using configuration file '/home/KMG/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[i] using '/root/.maltrail/trails.csv' for trail storage (last modification: 'Sat, 07 Aug 2021 22:04:41 GMT')
[i] loading trails...
[i] 1,938,210 trails loaded
[!] plugin script '2013-10-28-Sibhost-EK-traffic.pcap' should have an extension '.py'

I am trying to thankfully use your tool to check against known malicious PCAPs and see what types of alerts occur.
