### ISSUE TITLE
IPv6 scan

### ISSUE THREAD

**Issue by jessie00** [stamparm/maltrail#57]
Could you say me if maltrail support ipv6. I don't see IPV6 scan. Perhaps it's a problem on my configuration.

**Comment by stamparm** [comment]
Can you please update to the latest revision and retry? I've just included (initial) support for IPv6

**Comment by stamparm** [comment]
Please wait a bit.... :)

**Comment by stamparm** [comment]
Now you can try

**Comment by stamparm** [comment]
![11](https://cloud.githubusercontent.com/assets/921555/12452196/7e80f98c-bf8d-11e5-8d2a-2494af1d5902.png)

**Comment by stamparm** [comment]
p.s. if you are using older version of `maltrail.conf` please remove the `CAPTURE_FILTER` as it was previously set to `ip` (also, please update to the latest revision)

**Comment by jessie00** [comment]
I just try. Its works perfect.

We are now ready for the future of the Internet :-)

If you want more test, don't hesitate to contact me.




2016-01-20 16:06 GMT+01:00 Miroslav Stampar <notifications@github.com>:
