### ISSUE TITLE
whoami not found

### ISSUE THREAD

**Issue by rauldobrota** [stamparm/maltrail#6]
After starting sensor and server, on web interface I get 'The requested url /maltrail/html/whoami not found'

**Comment by stamparm** [comment]
Web interface should be accessible on port 8338 (by default) when you start
the server.py instance. I hope that you haven't used e.g. Apache to copy
the maltrail's directory there. In such case error like this is possible.

Can you please send a screenshot of your error (and the way you access the
web interface).

p.s. You can find a test installation at maltrail.cu cc:8338

**Comment by stamparm** [comment]
That's it. You've copied the content of `html/` directory to (e.g.) apache instance, while Maltrail requires its own web server (accessible at port 8338 after running the `server.py`)

![hhhh](https://cloud.githubusercontent.com/assets/921555/11781222/928935da-a268-11e5-924f-2ab8df764ec0.png)

**Comment by stamparm** [comment]
p.s. just run the `python server.py` and access the Maltrail at `http://127.0.0.1:8338`

**Comment by rauldobrota** [comment]
Hi,
You are just right.
Excuse my reply delay.

2015-12-14 14:58 GMT+02:00 Miroslav Stampar <notifications@github.com>:

> p.s. just run the python server.py and access the Maltrail at
> http://127.0.0.1:8338
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamparm/maltrail/issues/6#issuecomment-164430169>.
>



-- 












*-----------------------------------------Laurenţiu Dobrotă+40 727 846 234
<40727846234>rauldobrota@gmail.com
<rauldobrota@gmail.com>skype:rauldobrotalinkedin:laurentiudobrota
<https://www.linkedin.com/in/laurentiudobrota>+laurentiudobrota
<https://plus.google.com/+laurentiudobrota>github:rauldobrota
<https://github.com/rauldobrota>slideshare:RaulDobrota
<http://www.slideshare.net/RaulDobrota>facebook:rauldobrota
<https://www.facebook.com/rauldobrota>twitter:rauldobrota
<https://twitter.com/rauldobrota>*
