### ISSUE TITLE
Memory usage is very high

### ISSUE THREAD

**Issue by theonlydoo** [stamparm/maltrail#60]
Hi,

Since I started to use maltrail in pre-production, peered on ossec hids, I saw this : 
![htop](https://cloud.githubusercontent.com/assets/1903124/12787899/9b7eb8b6-ca97-11e5-9338-614b02060209.png)

is there any way to help you debug this ?
n.b. the server's trafic is shaped like this : 
![graphs](https://cloud.githubusercontent.com/assets/1903124/12787891/941358c0-ca97-11e5-93d2-c127c557d9f9.png)

**Comment by stamparm** [comment]
Take a look into `CAPTURE_BUFFER` inside `maltrail.conf`

**Comment by theonlydoo** [comment]
Neat, it perfectly worked for memory consumption, but CPU usage stays a bit intense :
![cpu](https://cloud.githubusercontent.com/assets/1903124/12810089/2149c224-cb24-11e5-8b4e-c17aae5f8337.png)

Is there a possible tweak ?

**Comment by stamparm** [comment]
Well, it is a traffic analyzer. It is supposed to be intensive :)

You can try to use (in maltrail.conf):

`CAPTURE_FILTER ip and (not tcp or (tcp[13] == 2) or (tcp[13] & 8 != 0))`

This means that it will capture (most interesting) only SYN or PSH TCP packets and all other non-TCP IP packets

If you want to skip non-TCP (UDP,ICMP,etc.) traffic alltogether you can just put:

`CAPTURE_FILTER (tcp[13] == 2) or (tcp[13] & 8 != 0) or not tcp`

**Comment by stamparm** [comment]
If you don't care about heuristics (suspicious user agents, suspicious domains, suspicious...) you can turn off it in `maltrail.conf` like:

`USE_HEURISTICS false`

**Comment by theonlydoo** [comment]
even without the heuristics, the cpu usage stays around 25% .. So at scale, it's better to use maltrail on some random network points instead of running it infrastructure wide I guess. Otherwise it would be a huge waste of CPU time
