### ISSUE TITLE
HTTP_PORT is needed when running as sensor only

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#6020]
Hi,

one of the OPNsense users tries to use maltrail as sensor only with centralized logging, but it seems that sensor wont start when HTTP_PORT is unset.

Is this normal behavior? 

```
root@OPNsense:/usr/plugins/security/maltrail # python2.7 /usr/local/share/maltrail/sensor.py
Maltrail (sensor) #v0.15.56

[i] using configuration file '/usr/local/share/maltrail/maltrail.conf'
[!] invalid configuration value for 'HTTP_PORT' ('')

```

https://github.com/opnsense/plugins/pull/1650

**Comment by stamparm** [comment]
@mimugmail "fixed" with the latest revision

**Comment by mimugmail** [comment]
Thx :) Would you mind tagging a release when you find the time?

**Comment by MikhailKasimov** [comment]
> Thx :) Would you mind tagging a release when you find the time?

https://github.com/stamparm/maltrail/commit/999339c8b9b615332e8d3f3f53c3262408588a69
