### ISSUE TITLE
[Feature request] Output to text file

### ISSUE THREAD

**Issue by scriptzteam** [stamparm/maltrail#61]
Will be great if we can export the table of threats into text file

**Comment by scriptzteam** [comment]
Anything like this is possible?? Would be really cool to have it exported ;)

**Comment by scriptzteam** [comment]
Okay so still nothing? :D

**Comment by MikhailKasimov** [comment]
Hello!

Maltrail logs are in plain-text format. Perhaps, you can build something with your own critearias by using ```awk```, ```grep```, ```sort```, ```uniq``` commands?
