### ISSUE TITLE
Provide help generating sha256 hashed password

### ISSUE THREAD

**Issue by berturion** [stamparm/maltrail#62]
Just a little enhancement for newbis:

I had some trouble to generate a new password. And I found that the simplest way to do this on linux is this:

    echo -n 'changeme!' | sha256sum

I think that it would be useful to include a comment in maltrail.conf that would say:

    # for example, default password is optained with command:
    #    $ echo -n 'changeme!' | sha256sum

**Comment by stamparm** [comment]
done

**Comment by berturion** [comment]
Wow, that was quick :)
Thanks.
