### ISSUE TITLE
Auto-refreshing of MT-page

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#624]
Resounded from #168 .

We can have such functionality, inspired on e.g. apache2 ```mod_status``` module, which gives a hint for such variant -- to have something like ```example.com:8338/?refresh=N``` , where N -- page refreshing period (secs).

See [0] https://httpd.apache.org/docs/current/mod/mod_status.html ```Automatic Updates``` section:

```You can get the status page to update itself automatically if you have a browser that supports "refresh". Access the page http://your.server.name/server-status?refresh=N to refresh the page every N seconds.```

**Comment by stamparm** [comment]
e.g. `?refresh=60` will enforce refreshment of page in every 60 seconds
