### ISSUE TITLE
FeatReq: Selectable number of packet processing cores

### ISSUE THREAD

**Issue by petiepooo** [stamparm/maltrail#63]
I can see this running on a multi-use sensor with other NSM tools, such as netsniff-ng, snort, etc.  When USE_MULTIPROCESSING is set to true, defaulting the number of packet processing cores to cpu_count - 1 is unfriendly in this regard.

I'd love to see the ability to select the number of CPU processes created for processing packets.  Say a configuration option that's used instead of _multiprocessing.cpu_count() within the _init_multiprocessing() function.  If the config option is unspecified, it could default to cpu_count() - 1.

I'd recommend not setting affinity either if a process count is specified.

This would also lend itself to use on specific interfaces by running with different config files.

**Comment by stamparm** [comment]
Done for number of processes (`USE_MULTIPROCESSING` is now deprecated):

```
# [Sensor]

# Number of processes
PROCESS_COUNT $CPU_CORES
```

As of affinity, can you please be more elaborate why do you think that setting up the affinity is bad?

**Comment by petiepooo** [comment]
If I run two instances of this using two config files, each with a different eth interface, will they have affinity set to use the same CPUs?  

I typically run things like this on a 24 or 32-core server and let the scheduled do its thing shuffling the task between cores.

If affinity does come into play, I prefer setting it such that hyperthread cores are excluded and data from the sniffing process going to processing processes never have to leave the physical CPU's cache on a dual socket server. That level of config is very machine-dependent and is best done explicitly or manually.

**Comment by petiepooo** [comment]
BTW, thanks for the quick update! That was much faster than if I would have tried to whip up a pull request on my own.. 😀

**Comment by petiepooo** [comment]
Autocorrect got me. It should read "let the scheduler do its thing" in case that wasn't clear...

**Comment by stamparm** [comment]
Affinity setting logic can be found here: https://github.com/stamparm/maltrail/blob/master/sensor.py#L687-L703

I can introduce the configuration switch for user to disable it (if he wants to do it himself like in your case)

**Comment by petiepooo** [comment]
Yes please if it's not too much trouble. Thanks for your effort; this is a great tool.

**Comment by stamparm** [comment]
Added new switch `DISABLE_CPU_AFFINITY`
