### ISSUE TITLE
Work on FreeBSD port?

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#631]
Hi,

I'd love to build a plugin for OPNsense Firewall but would need a FreeBSD port for this.
Anyone around planning to bring it to BSD?

Thanks! 👍

**Comment by mimugmail** [comment]
@stamparm I'll create a FreeBSD port myself. Would you mind publishing a new release as building ports will download the latest release from github (which is 0.9).

**Comment by stamparm** [comment]
Done

**Comment by mimugmail** [comment]
Thx! I'll test it with my Makefile and send to the FreeBSD port list

**Comment by mimugmail** [comment]
@stamparm https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233074
