### ISSUE TITLE
server.py: open files limit exceeded

### ISSUE THREAD

**Issue by srondeauuwt** [stamparm/maltrail#64]
The server (v0.9.171) had been running for several days, I believe. I noticed today that the open files limit was exceeded. For root, that was 1024 files soft and 4096 hard. I changed them both to be 10240.

I am not sure if that means that over 1024 files or sockets are open, and if this is a bug or just too much data.

There is a sensor process running on the same host, and one that is remotely logging its data to the server host.

The remote sensor (v0.9.171) had at least 24,000 events in one day a couple of days ago.  I think server.py started failing due to too many open files yesterday, but I wasn't watching the host, so I can't be sure.

**Comment by stamparm** [comment]
This should be fixed with v0.9.185 (https://github.com/stamparm/maltrail/commit/e6972d2e83c46b7f825baa1600ea2b1bea20039d)

Please reopen if you have the same problem in future
