### ISSUE TITLE
Custom Files

### ISSUE THREAD

**Issue by jigsawsecurity** [stamparm/maltrail#66]
-rw-r--r-- 1 root root     118 Jan 22 09:51 dprk.txt
-rw-r--r-- 1 root root    1374 Jan 22 09:51 __init__.py
-rw-r--r-- 1 root root 3399828 Feb 13 00:09 Jigsaw-Malicious-Domain
-rw-r--r-- 1 root root 1383029 Feb 13 00:09 Jigsaw-Malicious-Hostname
-rw-r--r-- 1 root root  956307 Feb 13 00:09 Jigsaw-Malicious-IP-Dst
-rw-r--r-- 1 root root 1264316 Feb 13 00:09 Jigsaw-Malicious-IP-Src
-rw-r--r-- 1 root root 2329767 Feb 13 00:09 Jigsaw-Malicious-URL

I have these files in the custom trails directory. However none of them actually detect in maltrail. Below is a snippet from each of the files. 

Jigsaw-Malicious-Domain:
0-0-0-0-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0-0-0.info
0-0-0-0-0-0-0-0-0-0-0-0-0-16-0-0-0-0-0-0-0-0-0-0-0-0-0.info
0-0-0-0-0-0-0-0-0-0-0-0-0-19-0-0-0-0-0-0-0-0-0-0-0-0-0.info
0-0-0-0-0-0-0-0-0-0-0-0-0-19-0-0-0-0-0-0-0-0-0-0-0-0-0.info
0-0-0-0-0-0-0-0-0-0-0-0-0-22-0-0-0-0-0-0-0-0-0-0-0-0-0.info

Jigsaw-Malicious-Hostname:
0-.qpic.cn
0-.store.qq.com
0-0.am-0.ns-0.am
0-0.dw-0.pr-0.dw-0.ps-0.pt
0-0.fu-0.w0-0.fu-0.sr-1.ss.st.su

Jigsaw-Malicious-IP-Dst:
1.0.6.11
1.1.16.10
1.1.172.13
1.1.172.13
1.1.215.210
1.1.215.210
1.1.5.4
1.11.163.130

It won't detect ANY of the domains, IP's or anything from these list. Is there something wrong here with my format?

**Comment by stamparm** [comment]
Those should have an extension **.TXT**

Just please rename them to have the extension **.TXT**
