### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by Ponyboy47** [stamparm/maltrail#662]
I recently set up an Maltrail server and have attained Let's Encrypt certificates. I'm unsure which certificate is supposed to be used as the SSL_PEM cert (I think either the fullchain.pem or privkey.pem), but none of them work. Starting the server always results in the following error:
```
2018-10-12 10:01:29 

[!] unhandled exception occurred ('[('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'PEM lib')]')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "/opt/maltrail/server.py", line 108, in <module>
    main()
  File "/opt/maltrail/server.py", line 100, in main
    start_httpd(address=config.HTTP_ADDRESS, port=config.HTTP_PORT, pem=config.SSL_PEM if config.USE_SSL else None, join=True)
  File "/opt/maltrail/core/httpd.py", line 599, in start_httpd
    server = SSLThreadingServer((address or '', int(port) if str(port or "").isdigit() else 0), pem, SSLReqHandler)
  File "/opt/maltrail/core/httpd.py", line 93, in __init__
    ctx.use_certificate_file(pem)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 935, in use_certificate_file
    _raise_current_error()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'PEM lib')]
'
---
```

I saw the other issue here about the certificate having dos line endings and I've verified that is not the case with the Let's Encrypt certificates which I'm trying to use.

For now I'm proxying through https with Nginx using the certificates.

**Comment by stamparm** [comment]
1) Both certificate and private key (PEM format) should be inside provided file (merged)
2) Run `openssl req -new -x509 -keyout server.pem -out server.pem -days 1023 -nodes` to see the example of a valid file (accepted by Maltrail)

**Comment by Ponyboy47** [comment]
Thank you, I've managed to get Maltrail working with SSL now
