### ISSUE TITLE
[!] please install 'Pcapy' (e.g. 'sudo apt-get install python-pcapy')

### ISSUE THREAD

**Issue by wizhardhacker1** [stamparm/maltrail#6778]
python-pcapy is installed 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pcapy is already the newest version (0.11.4-1~kali2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

python version

Python 2.7.17

constant error now 

##@##:~/maltrail$ sudo python3 sensor.py
[!] please install 'Pcapy' (e.g. 'sudo apt-get install python-pcapy')

any help would be great

**Comment by awmawl** [comment]
Hello there. May I can help. Pcapy is a Python extension module that enables software written in Python to access the routines from the pcap packet capture library. For further information: https://pypi.org/project/pcapy/

So, You just insert this command to your server:

**sudo apt-get update
sudo apt-get upgrade
apt-get install python-pcapy**

If it still doesn't work, please update your Linux OS Repository with this command:
**sudo apt-add-repository 'deb http://ftp.us.debian.org/debian stretch main contrib non-free'**

I hope your Maltrail will work as well :)

**Comment by awmawl** [comment]
Hello there.. Pcapy is a Python extension module that enables software written in Python to access the routines from the pcap packet capture library. For further information: https://pypi.org/project/pcapy/

So, You just insert this command into your server:
**sudo apt-get update
sudo apt-get upgrade
apt-get install python-pcapy**

If it still doesn't work, please update your Linux OS Repository with this command:
**sudo apt-add-repository 'deb http://ftp.us.debian.org/debian stretch main contrib non-free'**

I hope your Maltrail will work as well :D

**Comment by wizhardhacker1** [comment]
Yea, that was done - if you look at the commands I pasted it is installed-

**Comment by awmawl** [comment]
Have you update your repository? Try to Add the repository with the command above and try again to install python-pcapy

**Comment by wizhardhacker1** [comment]
Yep , but I just figured it out something simple

I used Python3 command instead of just python

**Comment by awmawl** [comment]
Solved?

**Comment by awmawl** [comment]
Nah, solved?

**Comment by wizhardhacker1** [comment]
Yes

**Comment by wizhardhacker1** [comment]
sudo python sensor.py

**Comment by stamparm** [comment]
Sorry for late reply. It is little clumsy to describe to user how to install packages depending on Python version used. 

Thus, with the latest revision you'll be pointed to appropriate `pip` command (e.g. `sudo pip2 install pcapy` for Python2 and `sudo pip3 install pcapy` for Python3)
