### ISSUE TITLE
 in the sersor.py increase in the command line parameters --updatetimer, the implementation of the Update_timer function.

### ISSUE THREAD

**Issue by nmweizi** [stamparm/maltrail#68]
When using maltrail, there is no condition for connecting to the Internet.
So in the sersor.py increase in the command line parameters --updatetimer, the implementation of the Update_timer function.
At the same time in the Dockerfile to increase the **RUN python /root/maltrail/sensor.py --updatetime**

**Comment by stamparm** [comment]
Please take a look into the `UPDATE_PERIOD` inside the `maltrail.conf`

**Comment by nmweizi** [comment]
I'm not good at English. thx
The first start there is no Internet connection, so can not be downloaded trails.
Ready to build in the docker when it has been able to download trails.
Copy image to target machine，then run.

**Comment by stamparm** [comment]
Now, with the latest commit, Maltrail will wait in this kind of situations:

```
$ sudo ./sensor.py 
[sudo] password for stamparm: 
Maltrail (sensor) #v0.9.219

[i] using configuration file '/home/stamparm/Dropbox/Work/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[?] at least 384MB of free memory required
[!] can't update because of lack of network connection (waiting...
```

**Comment by nmweizi** [comment]
thx.
Downloaded tails does not exist, means that the analysis of the data is not complete.
Therefore would like to have the conditions on the machine download TRAILS (image docker), and then copy the image(docker) to the machine running on the no internet and No need to update.
