### ISSUE TITLE
PROCESS_COUNT -> USE_MULTIPROCESSING

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#6842]
Hello!

Discussion: 

https://twitter.com/julio_cbc/status/1229485355591663622 -> https://forum.opnsense.org/index.php?topic=14021.0 :

```
@mimugmail

Apparently changing from `PROCESS_COUNT` to `USE_MULTIPROCESSING` solved my problem with very high CPU usage.

Makes any sense to you?
```
ref.: https://github.com/cloudfence/plugins/commit/e878c035a465882d186e5c9181f827b5c21e177d

MT files with ```PROCESS_COUNT``` variable:

- log.py
- maltrail.conf
- settings.py
- sensor.py

@stamparm @mimugmail

**Comment by mimugmail** [comment]
I have an old VirtualBox VM which has a similar issue like in the thread, load of 1,7 with maltrail enabled and not traffic. I changed from PROCESS_COUNT to USE_MULTIPROCESSING without effect.

@stamparm is there a best practice to do?
Currently I'm hardcoding it into config:

https://github.com/opnsense/plugins/blob/master/security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf#L29-L30

**Comment by stamparm** [comment]
1) `What does your /var/log/maltrail/error.log show? Mine is flooded " with Received unexpected datalink (186)` <- this has been indeed causing trouble, before that same referenced commit
2) `USE_MULTIPROCESSING` shows a non-exiting deprecation warning (in console): `[x] configuration switch 'USE_MULTIPROCESSING' is deprecated. Please use 'PROCESS_COUNT' instead` <- thus, this doesn't do anything smart (maybe only reducing number of process count to 1)

**Comment by mimugmail** [comment]
My error.log is empty with the current code.
So this looks sane:

```
PROCESS_COUNT $CPU_CORES
DISABLE_CPU_AFFINITY false

```
?

**Comment by stamparm** [comment]
@mimugmail yup

**Comment by mimugmail** [comment]
Ok, then I'd say we don't change the defaults to USE_MULTIPROCESSING.
I'll reach out for the guy stating that it worked for him, may it had some other reason.
