### ISSUE TITLE
Environment ready to download TRAILS, for docker

### ISSUE THREAD

**Issue by nmweizi** [stamparm/maltrail#69]
thx.

- Downloaded tails does not exist, means that the analysis of the data is not complete,and sersor.py Can never run,Will be parked in the waitting state,Because there is no condition to connect the Internet.
- Therefore would like to have the conditions on the machine download TRAILS (image docker), and then copy the image(docker) to the machine running on the no internet and No need to update.

#68

**Comment by stamparm** [comment]
There is only one problem here. If there is no feed update (on daily basis) you'll be left with blacklists that will become junk after several weeks, especially those based on IPs

**Comment by stamparm** [comment]
With the latest revision (https://github.com/stamparm/maltrail/commit/672c9a9519f134364acdb0b9f1da6fe067531dfa) you'll be able to run the docker in that environment you want. Update will now be done immediately after the `git clone` and afterwards there will be a 100 seconds of connection retry attempts (continuing on after that)

**Comment by nmweizi** [comment]
This is the way. Thx
