### ISSUE TITLE
Autostart Problem/Question

### ISSUE THREAD

**Issue by bicodegas** [stamparm/maltrail#690]
Hi, 

I'm having some trouble autostarting sensor and server. I have git cloned maltrail to /home/[user]/.maltrail and both run fine via command line. I pointed "server.py", "sensor.py" and "maltrail.conf" to the /home/[user]/.maltrail/ path in both crontabs.

If I use the /usr/bin/pgrep parameter, server and sensor won't start at all. If I don't use it, the sensor process seems to start multiplying itself until it uses all the ram and my computer freezes.

Is this happening just because I'm starting maltrail from my home folder?
Just in case, I'm using Xubuntu 18.04

Thanks in advance
Cheers

p.s.- sorry for the 'repost', but some days ago I made this question on an old issue from 2017

**Comment by stamparm** [comment]
As commented at: https://github.com/stamparm/maltrail/issues/147#issuecomment-315875680. Are you able to do those same commands from `root` shell?

**Comment by bicodegas** [comment]
Hi, thanks for your help

Yes, I've tried both commands on a root shell:

`/usr/bin/pgrep -f server.py || /usr/bin/python /path/to/maltrail/server.py -c /path/to/maltrail.conf`
`/usr/bin/pgrep -f sensor.py || /usr/bin/python /path/to/maltrail/sensor.py -c /path/to/maltrail.conf`

and everything works fine. The server is running normally and sensor process was limited to two (2 cores)

**Comment by stamparm** [comment]
Then not sure what seems to be the problem with the `cron` in your case.

A) Double check that you run the cronjobs (with those commands) from root account
B) If that still fails try to put each of those lines into shell scripts (e.g. `/usr/local/bin/maltrail_sensor.py`) and just call them from cron jobs (e.g. `*/5 * * * * /usr/local/bin/maltrail_sensor.py`)

**Comment by bicodegas** [comment]
Hi @stamparm 

I tried your suggestions, both command on the root account didn't work, it wouldn't start. I had to create the two shell scripts and called them both from the root's cronjob, like this:
```
*/1 * * * * /home/USER/.maltrail/sensor_cron
*/5 * * * * /home/USER/.maltrail/server_cron
``` 
Server script wouldn't start from the normal user account. I don't know if there's a problem running the server from root's cronjob. On your comment #147 you said "preferably non-root's user cronjob". 

But for now everything seems to be running fine. 
Thanks for you help.

**Comment by stamparm** [comment]
Server requires `/var/log/maltrail` to be created (creation requires sudo privileges). So, if sensor has been run once with sudo/root account, it should be there.

Beside that requirement, it could be run from non-root account (I've just stated the least privilege that it requires - at it should be non-root account)

**Comment by stamparm** [comment]
Just created [Best practice(s)](https://github.com/stamparm/maltrail/#best-practices)
