### ISSUE TITLE
Feature Request:  Refresh

### ISSUE THREAD

**Issue by DigiAngel** [stamparm/maltrail#7]
First off THIS APP IS AWESOME.  Just started with it today and it rocks.  Second, any chance we can get an autorefresh workin on this?  Thanks so much!

**Comment by stamparm** [comment]
@DigiAngel just as a starter, in the last 12hours there were couple of big bugs. Please update to the latest revision.

As of autorefresh, I have it on my mind. Only thing is that I am not sure that this will be doable like "real-time" refresh. Processing of all data has to be done in one go (at least now), so incremental update is somehow unrealistic at the moment. If you would like dummy "autorefresh" every N minutes, this is doable. Just tell me how would you prefer it. I could make it as a configuration option (e.g. AUTO_REFRESH_PERIOD) or as a web page dropdown menu (e.g. autorefresh -> disabled, 5 mins, 10mins, ...)

**Comment by DigiAngel** [comment]
Thanks for the quick response!  Just dig a git pull a few seconds ago, so there's that :)  I think as a web page dropdown might give people quicker access if they don't need it to say...refresh over a weekend when away from work...something like that.  Thanks again.

**Comment by ryan7g49i27653** [comment]
Just a simple drop-down with a few selections that change the meta (or the like) to refresh the page every selected minutes (or whatever) would be killer :)  What would be even more killer is to be able to have it reload with the selected filter in place too (i.e. high).

**Comment by stamparm** [comment]
@ryan7g49i27653 with latest push, filter is now saved between refresh

**Comment by MikhailKasimov** [comment]
Seems, can be closed because of refresh implementation via https://github.com/stamparm/maltrail/issues/624
