### ISSUE TITLE
Dockerfile  increase  copy maltrail.conf

### ISSUE THREAD

**Issue by nmweizi** [stamparm/maltrail#70]
Dockerfile:
COPY maltrail.conf /root/maltrail/maltrail.conf
or
sudo docker run -d --net=host  ---cap-add=NET_ADMIN -v /var/log/maltrail/:/var/log/maltrail/ -v /home/maltrail/maltrail.conf:/root/maltrail/maltrail.conf:ro  maltrail

**Comment by stamparm** [comment]
`COPY` makes sense, but Docker is pretty st*pid regarding missing copy files. What if regular user doesn't want to make changes to the regular maltrail.conf (and hence misses putting its own maltrail.conf)? Docker will just break (`INFO[0000] maltrail.conf: no such file or directory`)

**Comment by nmweizi** [comment]
- Because I need to change the conf file and trails update file, so I started this.

ifconfig eth1 promisc
ifconfig eth2 promisc
docker  run -d --net=host  -v /var/log/maltrail/:/var/log/maltrail/ -v /root/.maltrail/:/root/.maltrail/ 

- Recommended to detect conf and trails file status, if there is an update on the restart service.

**Comment by stamparm** [comment]
Is it now better with latest https://github.com/stamparm/maltrail/blob/ce62ca7a2ed196991e367347b0f0ef652089ef24/docker/README.md ?

p.s. as of last point (update/restart) can you please be more elaborate?

**Comment by nmweizi** [comment]
- centos7 grep in the card name is eno????,May not be too common.
- last point (update/restart) can you please be more elaborate:
When sensor detects maltrail.conf changes, reboot auto itself.
Such as django:
mange.py runserver 
When the settting.py changes, restart web.
