### ISSUE TITLE
Graph.facebook.com

### ISSUE THREAD

**Issue by p1r473** [stamparm/maltrail#7286]
Blocking this  domain breaks Facebook Groups on mobile.

**Comment by MikhailKasimov** [comment]
Hello! ```graph.facebook.com``` lives in https://github.com/stamparm/maltrail/blob/master/misc/whitelist.txt (see string 459). 

So, need some details from you: what exactly blocks ```graph.facebook.com``` on your side? Does MT detect ```graph.facebook.com``` on your side? What version of MT do you use?

Thank you!

**Comment by p1r473** [comment]
Sorry, I think I have made a mistake

**Comment by MikhailKasimov** [comment]
@p1r473 How old is this information and where you get it from?

**Comment by p1r473** [comment]
It was a bug I think
