### ISSUE TITLE
CHECK_CONNECTION_URL change 

### ISSUE THREAD

**Issue by nmweizi** [stamparm/maltrail#73]
CHECK_CONNECTION_URL = "https://www.google.com"
to
CHECK_CONNECTION_URL = "https://www.github.com"
Because Ping google doesn't work.

**Comment by stamparm** [comment]
Ping is not used

**Comment by nmweizi** [comment]
I can't visit Google.Firewall block

**Comment by stamparm** [comment]
Changed
