### ISSUE TITLE
Sensor logging, logs not making it to server

### ISSUE THREAD

**Issue by pktmterenceg** [stamparm/maltrail#74]
Hallo! I'm loving maltrail (set up at home, but soon at work, too!) but I can't seem to get the logs from the sensor (Raspberry Pi, B+) over to the server (Mac OS X 10.10). There's nothing that should prevent the two systems from talking, and they appear to be otherwise able to ssh, etc. 

I'm more than willing to consider that the whole thing is a configuration issue (my fault, that is), but I can't figure out where. 

Help? Please?

Thanks!

Sensor's maltrail.conf:

    # [Sensor]

    # Number of processes
    PROCESS_COUNT $CPU_CORES

    # Disable setting of CPU affinity (with schedtool) on Linux machines (e.g. because of load issues with other processes)
    DISABLE_CPU_AFFINITY false

    # Use feeds (too) in trail updates
    USE_FEED_UPDATES true

    # Update trails after every given period (seconds)
    UPDATE_PERIOD 12000

    # Location of directory with custom trails (*.txt) files
    CUSTOM_TRAILS_DIR ./trails/custom

    # (Max.) size of multiprocessing network capture ring buffer (in bytes or percentage of total physical memory) used by sensor (e.g. 512MB)
    CAPTURE_BUFFER 10%

    # Interface used for monitoring (e.g. eth0, eth1)
    MONITOR_INTERFACE eth1

    # Network capture filter (e.g. ip)
    # Note(s): more info about filters can be found at: https://danielmiessler.com/study/tcpdump/
    #CAPTURE_FILTER ip

    # Sensor name to appear in produced logs
    SENSOR_NAME $HOSTNAME

    # Remote address to send log entries (local storage otherwise)
    LOG_SERVER 192.168.1.199:8337

    # Use only (!) in cases when LOG_SERVER should be used for log storage
    DISABLE_LOCAL_LOG_STORAGE false

    # Remote address for pulling (latest) trail definitions (e.g. http://192.168.2.107:8338/trails)
    #UPDATE_SERVER http://192.168.2.107:8338/trails

    # Use heuristic methods
    USE_HEURISTICS true

    # Use deep heuristic methods (not recommended)
    USE_DEEP_HEURISTICS false

    # Capture HTTP requests with missing Host header (introducing potential false positives)
    CHECK_MISSING_HOST false

    # Comma delimited (custom user) whitelist (i.e. IP addresses, domain names, etc.)
    USER_WHITELIST 127.0.0.1,127.0.0.2
    
Server's maltrail.conf:

    # [Server]

    # Listen address of (reporting) HTTP server
    HTTP_ADDRESS 0.0.0.0

    # Listen port of (reporting) HTTP server
    HTTP_PORT 8338

    # Use SSL/TLS
    USE_SSL false

    # SSL/TLS (private/cert) PEM file (e.g. openssl req -new -x509 -keyout server.pem -out server.pem -days 1023 -nodes)
    #SSL_PEM misc/server.pem

    # User entries (username:sha256(password):UID:filter_netmask(s))
    # Note(s): sha256(password) can be generated on Linux with: echo -n 'password' | sha256sum | cut -d " " -f 1
    #          UID >= 1000 have only rights to display results
    #          filter_netmask(s) is/are used to filter results
    USERS
    admin:9ab3cd9d67bf49d01f6a2e33d0bd9bc804ddbe6ce1ff5d219c42624851db5dbc:0:0.0.0.0/0                        # changeme!

    # Listen address of (log collecting) UDP server
    UDP_ADDRESS 0.0.0.0

    # Listen port of (log collecting) UDP server
    UDP_PORT 8337

    # Should server do the trail updates too (to support UPDATE_SERVER)
    USE_SERVER_UPDATE_TRAILS false

**Comment by stamparm** [comment]
A) when running server in this kind of situations it should be run with `sudo` privileges. Please make sure that you run it
B) can you please rerun everything from start together with `sudo tcpdump -X -n -i any port 8337` on server side? Afterwards run, on sensor side (or at point where traffic is being monitored by sensor): `ping -c 1 136.161.101.53`. Soon afterwards you should see an item in tcpdump. Please report back if you see it
C) after B), there should be a new event in sensor's `/var/log/maltrail/<today>.log` (and ideally in server logs too). Are you able to see it.

p.s. configuration looks fine

**Comment by stamparm** [comment]
No response. Closing down
