### ISSUE TITLE
Not send or capture traffic Server to remote

### ISSUE THREAD

**Issue by ecastillej0s** [stamparm/maltrail#76]
Dear team, good day @stamparm , download maltrail, but I have the following problem, could support me please, I do not register activity Server, This plugins set plans for fortigates, it would be something very good

run Server1 sensor.py, Server2 server.py with root privileges

Config maltrail.conf Vmware Server maltrail server.py
Config maltrail.conf Server sensor.py

///////////////////////////////////////////////////////////////////////////////
Vmware Maltrail.conf server.py Server2 IP 192.0.4.154> eno16777736 Bridge

  [Server]

  Listen address of (reporting) HTTP server
HTTP_ADDRESS 192.0.4.154

  Listen port of (reporting) HTTP server
HTTP_PORT 8338

  Use SSL/TLS
USE_SSL false

  SSL/TLS (private/cert) PEM file (e.g. openssl req -new -x509 -keyout server.pem -out server.pem -days 1023 -nodes)
 SSL_PEM misc/server.pem

  User entries (username:sha256(password):UID:filter_netmask(s))
  Note(s): sha256(password) can be generated on Linux with: echo -n 'password' | sha256sum | cut -d " " -f 1
           UID >= 1000 have only rights to display results
           filter_netmask(s) is/are used to filter results
USERS
    admin:9ab3cd9d67bf49d01f6a2e33d0bd9bc804ddbe6ce1ff5d219c42624851db5dbc:0:0.0.0.0/0                          changeme!

  Listen address of (log collecting) UDP server
UDP_ADDRESS 192.0.4.154

  Listen port of (log collecting) UDP server
UDP_PORT 8337

  Should server do the trail updates too (to support UPDATE_SERVER)
USE_SERVER_UPDATE_TRAILS true

  [Sensor]

  Number of processes
PROCESS_COUNT $CPU_CORES

  Disable setting of CPU affinity (with schedtool) on Linux machines (e.g. because of load issues with other processes)
DISABLE_CPU_AFFINITY false

  Use feeds (too) in trail updates
USE_FEED_UPDATES true

  Update trails after every given period (seconds)
UPDATE_PERIOD 86400

  Location of directory with custom trails (*.txt) files
CUSTOM_TRAILS_DIR ./trails/custom

  (Max.) size of multiprocessing network capture ring buffer (in bytes or percentage of total physical memory) used by sensor (e.g. 512MB)
CAPTURE_BUFFER 10%

  Interface used for monitoring (e.g. eth0, eth1)
MONITOR_INTERFACE any

  Network capture filter (e.g. ip)
  Note(s): more info about filters can be found at: https://danielmiessler.com/study/tcpdump/
 CAPTURE_FILTER ip

  Sensor name to appear in produced logs
SENSOR_NAME $HOSTNAME

  Remote address to send log entries (local storage otherwise)
 LOG_SERVER 192.168.2.107:8337

  Use only (!) in cases when LOG_SERVER should be used for log storage
DISABLE_LOCAL_LOG_STORAGE false

  Remote address for pulling (latest) trail definitions (e.g. http://192.168.2.107:8338/trails)
 UPDATE_SERVER http://192.168.2.107:8338/trails

  Use heuristic methods
USE_HEURISTICS true

  Use deep heuristic methods (not recommended)
USE_DEEP_HEURISTICS false

  Capture HTTP requests with missing Host header (introducing potential false positives)
CHECK_MISSING_HOST false

  Comma delimited (custom user) whitelist (i.e. IP addresses, domain names, etc.)
USER_WHITELIST 127.0.0.1,127.0.0.2
  [All]

  Show debug messages (in console output)
SHOW_DEBUG true

  Directory used for log storage
LOG_DIR $SYSTEM_LOG_DIR/maltrail

  HTTP(s) proxy address
 PROXY_ADDRESS http://192.168.5.101:8118

---

Maltrail.conf sensor.py Server1 IP 192.0.4.116> eth0 

  [Server]

  Listen address of (reporting) HTTP server
HTTP_ADDRESS 0.0.0.0

  Listen port of (reporting) HTTP server
HTTP_PORT 8338

  Use SSL/TLS
USE_SSL false

  SSL/TLS (private/cert) PEM file (e.g. openssl req -new -x509 -keyout server.pem -out server.pem -days 1023 -nodes)
 SSL_PEM misc/server.pem

  User entries (username:sha256(password):UID:filter_netmask(s))
  Note(s): sha256(password) can be generated on Linux with: echo -n 'password' | sha256sum | cut -d " " -f 1
           UID >= 1000 have only rights to display results
           filter_netmask(s) is/are used to filter results
USERS
    admin:9ab3cd9d67bf49d01f6a2e33d0bd9bc804ddbe6ce1ff5d219c42624851db5dbc:0:0.0.0.0/0                          changeme!

  Listen address of (log collecting) UDP server
 UDP_ADDRESS 0.0.0.0

  Listen port of (log collecting) UDP server
 UDP_PORT 8337

  Should server do the trail updates too (to support UPDATE_SERVER)
USE_SERVER_UPDATE_TRAILS false

  [Sensor]

  Number of processes
PROCESS_COUNT $CPU_CORES

  Disable setting of CPU affinity (with schedtool) on Linux machines (e.g. because of load issues with other processes)
DISABLE_CPU_AFFINITY false

  Use feeds (too) in trail updates
USE_FEED_UPDATES true

  Update trails after every given period (seconds)
UPDATE_PERIOD 1900

  Location of directory with custom trails (*.txt) files
CUSTOM_TRAILS_DIR ./trails/custom

  (Max.) size of multiprocessing network capture ring buffer (in bytes or percentage of total physical memory) used by sensor (e.g. 512MB)
CAPTURE_BUFFER 20%

  Interface used for monitoring (e.g. eth0, eth1)
MONITOR_INTERFACE eth0

  Network capture filter (e.g. ip)
  Note(s): more info about filters can be found at: https://danielmiessler.com/study/tcpdump/
CAPTURE_FILTER ip

  Sensor name to appear in produced logs
SENSOR_NAME $HOSTNAME

  Remote address to send log entries (local storage otherwise)
LOG_SERVER 192.0.4.154:8337

  Use only (!) in cases when LOG_SERVER should be used for log storage
DISABLE_LOCAL_LOG_STORAGE false

  Remote address for pulling (latest) trail definitions (e.g. http://192.168.2.107:8338/trails)
UPDATE_SERVER http://192.0.4.154:8338/trails

  Use heuristic methods
USE_HEURISTICS true

  Use deep heuristic methods (not recommended)
USE_DEEP_HEURISTICS false

  Capture HTTP requests with missing Host header (introducing potential false positives)
CHECK_MISSING_HOST true

  Comma delimited (custom user) whitelist (i.e. IP addresses, domain names, etc.)
USER_WHITELIST 127.0.0.1,127.0.0.2

  [All]

  Show debug messages (in console output)
SHOW_DEBUG true

  Directory used for log storage
LOG_DIR $SYSTEM_LOG_DIR/maltrail

  HTTP(s) proxy address
 PROXY_ADDRESS http://192.168.5.101:8118

---

Checking 30 min root@MaltrailSensor: ifconfig eth0 promisc
Checking 30 min root@MaltrailSensor: ifconfig eth0 promisc up

Maltrail sensor.py Server1 IP 192.0.4.116> eth0

root@MaltrailSensor:/opt/maltrail  ping 136.161.101.53
PING 136.161.101.53 (136.161.101.53) 56(84) bytes of data.
64 bytes from 136.161.101.53: icmp_seq=1 ttl=49 time=64.7 ms
64 bytes from 136.161.101.53: icmp_seq=2 ttl=49 time=64.9 ms
64 bytes from 136.161.101.53: icmp_seq=3 ttl=49 time=64.7 ms
64 bytes from 136.161.101.53: icmp_seq=4 ttl=49 time=64.9 ms
64 bytes from 136.161.101.53: icmp_seq=5 ttl=49 time=64.8 ms
64 bytes from 136.161.101.53: icmp_seq=6 ttl=49 time=64.7 ms
64 bytes from 136.161.101.53: icmp_seq=7 ttl=49 time=64.7 ms
64 bytes from 136.161.101.53: icmp_seq=8 ttl=49 time=64.7 ms
^C
--- 136.161.101.53 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7009ms
rtt min/avg/max/mdev = 64.713/64.788/64.945/0.236 ms

eth0      Link encap:Ethernet  HWaddr a4:5d:36:15:03:1a  
          inet addr:192.0.4.116  Bcast:192.0.4.255  Mask:255.255.255.0
          inet6 addr: fe80::a65d:36ff:fe15:31a/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:940493 errors:0 dropped:1 overruns:0 frame:0
          TX packets:484541 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1019559742 (972.3 MiB)  TX bytes:37573728 (35.8 MiB)

---

Vmware Maltrail server.py Server2 IP 192.0.4.154> eno16777736 Bridge

eno16777736 Link encap:Ethernet  HWaddr 00:0c:29:26:88:7d  
          inet addr:192.0.4.154  Bcast:192.0.4.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe26:887d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:232410 errors:0 dropped:2168 overruns:0 frame:0
          TX packets:404651 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:37988767 (37.9 MB)  TX bytes:959155117 (959.1 MB)

root@MaltrailServer:/opt/maltrail  python server.py 
Maltrail (server)  v0.10.16

[i] using configuration file '/opt/maltrail/maltrail.conf'
[i] running UDP server at '192.0.4.154:8337'
[i] starting HTTP server at 'http://192.0.4.154:8338/'
[o] running...
Traceback (most recent call last):
  File "/opt/maltrail/core/log.py", line 142, in handle
    handle = get_event_log_handle(int(sec))
  File "/opt/maltrail/core/log.py", line 40, in get_event_log_handle
    open(_, "w+").close()
IOError: [Errno 2] No such file or directory: '/var/log/maltrail/2016-03-02.log'
Traceback (most recent call last):
  File "/opt/maltrail/core/log.py", line 142, in handle
    handle = get_event_log_handle(int(sec))
  File "/opt/maltrail/core/log.py", line 40, in get_event_log_handle
    open(_, "w+").close()
IOError: [Errno 2] No such file or directory: '/var/log/maltrail/2016-03-02.log'
Traceback (most recent call last):
  File "/opt/maltrail/core/log.py", line 142, in handle
    handle = get_event_log_handle(int(sec))

---

Maltrail sensor.py Server1 IP 192.0.4.116> eth0

root@MaltrailServer:/opt/maltrail python sensor.py
python sensor.py 
Maltrail (sensor)  v0.10.16

[i] using configuration file '/opt/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[?] at least 384MB of free memory required
[i] retrieving trails from provided 'UPDATE_SERVER' server...
[i] loading trails...
[i] 1,012,706 trails loaded
[i] opening interface 'eth0'
[i] setting capture filter 'ip'
[i] preparing capture buffer...
[i] creating 3 more processes (out of total 4)
[o] running...
Traceback (most recent call last):
  File "sensor.py", line 544, in _process_packet
    answer = socket.inet_ntoa(dns_data[_ + 12:_ + 16])
error: packed IP wrong length for inet_ntoa
Traceback (most recent call last):
  File "sensor.py", line 544, in _process_packet
    answer = socket.inet_ntoa(dns_data[_ + 12:_ + 16])
error: packed IP wrong length for inet_ntoa

---

Server MaltrailServer  IP 192.0.4.154> 

root@MaltrailServer:/opt/maltrail  tcpdump -X -n -i any port 8337
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
09:28:45.207838 IP 192.0.4.116.51307 > 192.0.4.154.8337: UDP, length 141
    0x0000:  4500 00a9 32bb 4000 4011 7e7a c000 0474  E...2.@.@.~z...t
    0x0010:  c000 049a c86b 2091 0095 2530 3134 3536  .....k....%01456
    0x0020:  3933 3937 3039 2022 3230 3136 2d30 332d  939709."2016-03-
    0x0030:  3032 2031 313a 3238 3a32 392e 3730 3834  02.11:28:29.7084
    0x0040:  3636 2220 7061 7272 6f74 2031 3932 2e30  66".parrot.192.0
    0x0050:  2e34 2e31 3136 202d 2031 3336 2e31 3631  .4.116.-.136.161
    0x0060:  2e31 3031 2e35 3320 2d20 4943 4d50 2049  .101.53.-.ICMP.I
    0x0070:  5020 3133 362e 3136 312e 3130 312e 3533  P.136.161.101.53
    0x0080:  2022 7369 6e6b 686f 6c65 2063 6f6e 6669  ."sinkhole.confi
    0x0090:  636b 6572 2028 6d61 6c77 6172 6529 2220  cker.(malware)".
    0x00a0:  2873 7461 7469 6329 0a                   (static).
09:28:46.207858 IP 192.0.4.116.49320 > 192.0.4.154.8337: UDP, length 141
    0x0000:  4500 00a9 337c 4000 4011 7db9 c000 0474  E...3|@.@.}....t
    0x0010:  c000 049a c0a8 2091 0095 34fc 3134 3536  ..........4.1456
    0x0020:  3933 3937 3130 2022 3230 3136 2d30 332d  939710."2016-03-
    0x0030:  3032 2031 313a 3238 3a33 302e 3730 3939  02.11:28:30.7099
    0x0040:  3530 2220 7061 7272 6f74 2031 3932 2e30  50".parrot.192.0
    0x0050:  2e34 2e31 3136 202d 2031 3336 2e31 3631  .4.116.-.136.161
    0x0060:  2e31 3031 2e35 3320 2d20 4943 4d50 2049  .101.53.-.ICMP.I
    0x0070:  5020 3133 362e 3136 312e 3130 312e 3533  P.136.161.101.53
    0x0080:  2022 7369 6e6b 686f 6c65 2063 6f6e 6669  ."sinkhole.confi
    0x0090:  636b 6572 2028 6d61 6c77 6172 6529 2220  cker.(malware)".
    0x00a0:  2873 7461 7469 6329 0a                   (static).

Ping Server sensor.py

ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=46 time=43.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=46 time=43.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=46 time=43.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=46 time=43.3 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=46 time=43.3 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=46 time=43.2 ms
^C
--- 8.8.8.8 ping statistics ---
7 packets transmitted, 6 received, 14% packet loss, time 6003ms
rtt min/avg/max/mdev = 43.235/43.284/43.324/0.172 ms

TCPDUMP Server sensor.py

tcpdump host 8.8.8.8
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes

12:46:26.324737 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7892, seq 1, length 64
12:46:26.367953 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7892, seq 1, length 64
12:46:27.241104 IP 192.0.4.116.53722 > google-public-dns-a.google.com.domain: 9414+ PTR? 8.8.8.8.in-addr.arpa. (38)
12:46:27.294442 IP google-public-dns-a.google.com.domain > 192.0.4.116.53722: 9414 1/0/0 PTR google-public-dns-a.google.com. (82)
12:46:27.295415 IP 192.0.4.116.35819 > google-public-dns-a.google.com.domain: 8855+ PTR? 116.4.0.192.in-addr.arpa. (42)
12:46:27.324439 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7892, seq 2, length 64
12:46:27.348344 IP google-public-dns-a.google.com.domain > 192.0.4.116.35819: 8855 NXDomain 0/1/0 (96)
12:46:27.367673 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7892, seq 2, length 64
12:46:28.325787 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7892, seq 3, length 64
12:46:28.369085 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7892, seq 3, length 64
12:46:29.326514 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7892, seq 4, length 64
12:46:29.369780 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7892, seq 4, length 64
12:46:30.327115 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7892, seq 5, length 64
12:46:31.326520 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7892, seq 6, length 64
12:46:31.369796 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7892, seq 6, length 64
12:46:32.327914 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7892, seq 7, length 64
12:46:32.371175 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7892, seq 7, length 64
^C
17 packets captured
17 packets received by filter
0 packets dropped by kernel

Ping Server sensor.py

ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=46 time=43.5 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=46 time=43.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=46 time=43.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=46 time=43.1 ms
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 43.194/43.379/43.575/0.262 ms

TCPDUMP Server sensor.py:

tcpdump -i any host 8.8.8.8
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
12:47:16.232679 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7896, seq 2, length 64
12:47:16.276137 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7896, seq 2, length 64
12:47:17.194410 IP 192.0.4.116.40108 > google-public-dns-a.google.com.domain: 15133+ PTR? 8.8.8.8.in-addr.arpa. (38)
12:47:17.232463 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7896, seq 3, length 64
12:47:17.247976 IP google-public-dns-a.google.com.domain > 192.0.4.116.40108: 15133 1/0/0 PTR google-public-dns-a.google.com. (82)
12:47:17.248889 IP 192.0.4.116.38875 > google-public-dns-a.google.com.domain: 38416+ PTR? 116.4.0.192.in-addr.arpa. (42)
12:47:17.275702 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7896, seq 3, length 64
12:47:17.300715 IP google-public-dns-a.google.com.domain > 192.0.4.116.38875: 38416 NXDomain 0/1/0 (96)
12:47:18.233821 IP 192.0.4.116 > google-public-dns-a.google.com: ICMP echo request, id 7896, seq 4, length 64
12:47:18.276978 IP google-public-dns-a.google.com > 192.0.4.116: ICMP echo reply, id 7896, seq 4, length 64
12:48:38.181339 IP 192.0.4.116.38499 > google-public-dns-a.google.com.domain: 16569+ A? www.github.com. (32)
12:48:38.181345 IP 192.0.4.116.38499 > google-public-dns-a.google.com.domain: 50792+ AAAA? www.github.com. (32)
12:48:38.224897 IP google-public-dns-a.google.com.domain > 192.0.4.116.38499: 16569 2/0/0 CNAME github.com., A 192.30.252.131 (62)
12:48:38.225264 IP google-public-dns-a.google.com.domain > 192.0.4.116.38499: 50792 1/1/0 CNAME github.com. (111)
12:48:38.520922 IP 192.0.4.116.37586 > google-public-dns-a.google.com.domain: 26127+ A? github.com. (28)
12:48:38.520930 IP 192.0.4.116.37586 > google-public-dns-a.google.com.domain: 4305+ AAAA? github.com. (28)
12:48:38.565093 IP google-public-dns-a.google.com.domain > 192.0.4.116.37586: 4305 0/1/0 (93)
12:48:38.565807 IP google-public-dns-a.google.com.domain > 192.0.4.116.37586: 26127 1/0/0 A 192.30.252.130 (44)
![cat log server sensorpy](https://cloud.githubusercontent.com/assets/17597618/13471520/84d0d99c-e076-11e5-82da-1ab94f46f5cb.png)
![tcpdum -i eth0 sample](https://cloud.githubusercontent.com/assets/17597618/13471519/84cebaf4-e076-11e5-929f-caa2e1fc1c6a.png)
![tcpdum server maltrail](https://cloud.githubusercontent.com/assets/17597618/13471518/84cd6410-e076-11e5-9ab4-b91855be820c.png)
![error server sensorpy](https://cloud.githubusercontent.com/assets/17597618/13471521/84d2a218-e076-11e5-97a8-f6bd04593080.png)
![error log server mailtrail serverpy](https://cloud.githubusercontent.com/assets/17597618/13471522/84d373d2-e076-11e5-902c-261106511d3b.png)
![ping 136 161 101 53 server on sensorpy](https://cloud.githubusercontent.com/assets/17597618/13471517/84cd3e04-e076-11e5-9f8d-a9bfcbe177a4.png)
![panel server maltrail](https://cloud.githubusercontent.com/assets/17597618/13471523/84dc8ad0-e076-11e5-8f65-9ddbbc62c4af.png)

**Comment by ffaggiani** [comment]
HI,

I'm having exactly same issue.

Remote server is receiving correctly UDP log but it is having problems to save in /var/log/maltrail.

Seems that when you run server.py separately from sensor, the server cannot create the log files.
You can see that running server.py with strace and system calls open/write.
```
$ sudo strace -e open,write python server.py 

....
....
(ping from remote sensor to 136.161.101.53, and server receives UDP log)

 File "/home/*******/maltrail/core/log.py", line 40, in get_event_log_handle
    open(_, "w+").close()
IOError: [Errno 2] No such file or directory: '/var/log/maltrail/2016-03-03.log'
```

**Comment by ecastillej0s** [comment]
My Friend @ffaggiani thanks, fixed

mkdir maltrail
touch 2016-03-03.log

![fixed maltrail server](https://cloud.githubusercontent.com/assets/17597618/13497722/716a49b4-e11c-11e5-94af-39c781186998.png)


as recommend using tcpdump ? sample: tcpdump -i eth0

**Comment by ffaggiani** [comment]
Hi again,

Nice, i think that we have to create this files for the next days until the issue gets fixed.

Regarding tcpdump, 

- IF you are talking about "CAPTURE_FILTER" at sensor im using this: 

`CAPTURE_FILTER not arp and not stp and not port 22`
(Because i dont want to monitor ssh, arp and stp protocols)

-IF you are talking about how to debug at server side if UDP logs are arriving:

`$tcpdump -i eth0 -X port 8337 and host "sensor ip`

Cheers,
Fab

**Comment by ecastillej0s** [comment]
Hi friend, as you run tcpdump to monitor the entire network ? in server Sensor.py

**Comment by ffaggiani** [comment]
Hi!

You have to use "CAPTURE_FILTER" parameter in maltrail.conf to specify how tcpdump will run.
You have to use "MONITOR_INTERFACE" to specify the interface where tcpdump will sniff.

Said that, 

IF you want to monitor your entire network, you need an span port or network tap in your router/network to configure "MONITOR_INTERFACE" in that interface, because you want to sniff more than one device traffic.

I recommend to use Network Tap, you can build one or buy one.

**Comment by stamparm** [comment]
@ffaggiani my bad. Last commit should fix your issue (you've correctly debugged it :)

**Comment by HFsi** [comment]
Hi!
I've created the log file manually, but still can't get any data in it.
Any further help?
Thanks!

**Comment by stamparm** [comment]
Which options have you set for that purpose?

**Comment by HFsi** [comment]
I´m not sure which options do you mean.
In the log`s path for maltrail (/var/log/maltrail) I´ve created the file 2017-04-23.log with touch, like ecastillej0s said on 3 Mar 2016.
I´ve tried in Ubuntu Server 17.04 i386, which OS version do you use?

**Comment by HFsi** [comment]
Same result with Ubuntu Server 16.10 amd64

**Comment by stamparm** [comment]
@HFsi Original Issue has been fixed in a way that there is no more need to "touch"/"create" that file. Problem is that I am not sure what seems to be the problem in your case. Are you trying to send something from sensor to remove server or you are just trying to run sensor to get any events into it?

**Comment by HFsi** [comment]
The issue was fixed by especifying tha actual interface where the sensor listens, instead of ANY
