### ISSUE TITLE
Permanent Ban From RIPE Due to Query Rate

### ISSUE THREAD

**Issue by Synthetase** [stamparm/maltrail#77]
Hello,

It would appear that perhaps some sort of rate limiting of whois lookups via RIPE, or a local cache is in order. While using Maltrail over two weeks on a fresh VPS, and parsing various sizes of collected data, I have found that I am now permanently banned from doing whois lookups via RIPE. The ban is persistent a few months later, and will display even when doing a simple whois from the CLI for the first time in two months.

If a server is an active target, it would seem this may be an inevitable outcome after a period of time when looking over historical data. Please find the evidence below:

> % This is the RIPE Database query service.
> % The objects are in RPSL format.
> %
> % The RIPE Database is subject to Terms and Conditions.
> % See http://www.ripe.net/db/support/db-terms-conditions.pdf
> 
> %ERROR:201: access denied for <removed IPv6 IP of server>
> %
> % Sorry, access from your host has been permanently
> % denied because of a repeated excessive querying.
> % For more information, see
> % http://www.ripe.net/data-tools/db/faq/faq-db/why-did-you-receive-the-error-201-access-denied
> 
> % This query was served by the RIPE Database Query Service version 1.85.1 (DB-3)

**Comment by stamparm** [comment]
But Maltrail doesn't do WHOIS lookups on its own. Only time RIPE is called is when you look for events in browser. But I hardly doubt that this causes bans. Are you sure that this is Maltrail caused?

**Comment by Synthetase** [comment]
The browser is exactly where the data was often explored en mass. The only other thing making WHOIS look-ups on this particular utility server were singular queries from myself once every few days, via the CLI. That rate of lookup would never trigger a block. 

After using the Maltrail server element, the rate of queries was deemed so excessive as to trigger a permanent ban, not even a temporary one. The IPv6 address for the server has always belonged to me and this specific server.

**Comment by stamparm** [comment]
Is browser being used through SOCKS proxy of the server itself? I really don't see how this could all happen than if browser is making connections through SOCKS proxy (where proxy is server).

I'm using maltrail for more than a year on a huge network and haven't had such issues
