### ISSUE TITLE
[C2Panels] Feeds to add

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#771]
Hello!

On having static ```maltrail/trails/static/suspicious/malicious_с2panel.txt```, it would be perfect also to have specialized feeds for that with ```(suspicious)``` marker:

[0] https://zeustracker.abuse.ch/monitor.php?browse=dropzones
[1] https://cybercrime-tracker.net/ccpmgate.php

**Comment by MikhailKasimov** [comment]
Yes/No , @stamparm ?

**Comment by MikhailKasimov** [comment]
+1: http://tracker.viriback.com/

**Comment by stamparm** [comment]
https://cybercrime-tracker.net/ and http://tracker.viriback.com/ already covered with https://github.com/stamparm/blackbook/. ZeusTracker is discontinued
