### ISSUE TITLE
Fail2Ban blocking mechanism

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#7716]
Hello!

Inspired by https://twitter.com/awmawl/status/1241029586428690433) to describe two-three practical examples in documentation: e.g. to block ```suspicious``` addresses for 30 min and ```malicious``` for 60 min. 

This will give a ready-to-use mechanism for https://github.com/stamparm/maltrail/issues/30 and https://github.com/stamparm/maltrail/issues/44 and will make it possible for MT to be not only as IDS, but IPS too.

**Comment by MikhailKasimov** [comment]
https://github.com/stamparm/maltrail/commit/6f9279abe7eddee953ba9898bca41ca3a4be8b6c

**Comment by MikhailKasimov** [comment]
Can be closed due to https://github.com/stamparm/maltrail/commit/6f9279abe7eddee953ba9898bca41ca3a4be8b6c + https://github.com/stamparm/maltrail/commit/795c31881e784479ff78d9ff7f861fab59359761

**Comment by MikhailKasimov** [comment]
@mimugmail FYI : Hello! Possibly, you will need to update something for FreeBSD MT port and OPNSense GW. In particular, in GUI of settings section. Thank you!

**Comment by mimugmail** [comment]
OPNsense doesn't use fail2ban. A pkg is available but would be unconfigured. Maybe I find the time some day to add fail2ban as a plugin, after this we could add the field for maltrail. 

In general a nice feature :)

**Comment by MikhailKasimov** [comment]
@mimugmail And doesn't use ipset+iptables, as far as I remember. That's why I ping your attention here: to adopt some things, if needed. Thanks!

**Comment by awmawl** [comment]
Hi @MikhailKasimov ! Thanks for appreciation! I'm Awmawl, from the Twitter account above. I had connect Maltrail and Fail2Ban because of you and @stamparm. On July 7th, i'll face the last essay exam presentation, last but not least, thank you and wish me luck!
