### ISSUE TITLE
function update_trails optimization?

### ISSUE THREAD

**Issue by nmweizi** [stamparm/maltrail#80]
function update_trails  in update.py
line 78

if config.CUSTOM_TRAILS_DIR:

modify ->

if config.CUSTOM_TRAILS_DIR and not os.path.abspath(os.path.join(ROOT_DIR, "trails")) in os.path.abspath(os.path.join(ROOT_DIR, os.path.expanduser(config.CUSTOM_TRAILS_DIR))):

**Comment by stamparm** [comment]
This is just for checking whether the files in `config.CUSTOM_TRAILS_DIR` are of newer date than the current collected trails. What you tried to check/optimize here?

**Comment by nmweizi** [comment]
“for dirpath, dirnames, filenames in os.walk(os.path.abspath(os.path.join(ROOT_DIR, "trails"))) ” and “for dirpath, dirnames, filenames in os.walk(os.path.abspath(os.path.join(ROOT_DIR, os.path.expanduser(config.CUSTOM_TRAILS_DIR)))) ”  **repeat**

**Comment by stamparm** [comment]
With https://github.com/stamparm/maltrail/commit/ca4e5e94bc4c0a2a13b8adad760450f081afe348 there should be no repeat (using `set` instead of `list`)
