### ISSUE TITLE
Whitelist CIDR support

### ISSUE THREAD

**Issue by smtszk** [stamparm/maltrail#81]
Hi,
I wonder Maltrail will take any update for CIDR support? I want to add  all google IPs to my whitelist but you know, there are many IPs taken by google.
Any solution for this?

Best regards.

**Comment by nmweizi** [comment]
may be CAPTURE_FILTER in maltrail.conf

**Comment by PhunkFX** [comment]
I second this.  If I could add 10.10.10.0/24 in the whitelist, that would be awesome.  But so far so good with the new maltrail/misc/whitelist.txt file.

**Comment by stamparm** [comment]
Done :)

You can now put into your whitelist entries CIDR ranges too

**Comment by smtszk** [comment]
I tested but not working.

**Comment by stamparm** [comment]
@smtszk can you please describe how you've tried?

p.s. `USER_WHITELIST` is now pointing to the file location containing whitelisted entries

**Comment by smtszk** [comment]
@stamparm 

Okey. I added to 172.16.17.55 > /trails/custom/dprk.txt

Then;  editted /misc/whitelist.txt and added 

> 172.16.17.0/24

and pinged 

> 172.16.17.55;

  

`"2016-05-20 09:36:29.508004" ss-ThinkPad 192.168.1.41 - 172.16.17.15 - ICMP IP 172.16.17.15 dprk (custom)`

**Comment by stamparm** [comment]
@smtszk my bad :(

fixed

**Comment by smtszk** [comment]
@stamparm thanks. it works great.
