### ISSUE TITLE
[Feature] Blocking detected IPs

### ISSUE THREAD

**Issue by M4RC0Sx** [stamparm/maltrail#8187]
Could you add feature to block the malicious IPs detected? Or is there a good way to do it?

**Comment by MikhailKasimov** [comment]
#30 , #44 , #7716

**Comment by MikhailKasimov** [comment]
@M4RC0Sx Please, take a look on 6f9279a + 795c318

**Comment by stamparm** [comment]
Look for `FAIL2BAN_REGEX` at [README.md](https://github.com/stamparm/maltrail/blob/master/README.md#server)
