### ISSUE TITLE
[Feature Request] -- Whitelist File Reference

### ISSUE THREAD

**Issue by PhunkFX** [stamparm/maltrail#83]
Would you be able to reference file for whitelisting sources?  I feel that would be much more organized as well as transferable, rather than keeping all whitelisted sources in the maltrail.conf file itself.

Or even a whiltelist option on the source itself within the GUI.  

Throughts?

RH

**Comment by stamparm** [comment]
Done :)

`USER_WHITELIST` now takes a filepath (instead of comma separated values)

**Comment by PhunkFX** [comment]
Thanks Miro!
