### ISSUE TITLE
sensor finished

### ISSUE THREAD

**Issue by diegoarranz** [stamparm/maltrail#84]
Hi,

 I´ll try to use sensor in CentOS 6, the install is correct, but when i try to start it with python sensor.py(debug option active):

Maltrail (sensor) #v0.10.112

[i] using configuration file '/opt/maltrail/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[?] at least 384MB of free memory required
[i] loading trails...
[i] 979411 trails loaded
[i] opening interface 'eth0'
[i] setting capture filter 'ip or icmp or udp'
[i] preparing capture buffer...
[i] creating 3 more processes (out of total 4)
[o] running...
[i] finished
[i] please wait...
[i] finished

the sensor start but finished inmediatly. I put the eth0 in promisc mode

eth0      Link encap:Ethernet  HWaddr 08:00:27:91:C3:31
          inet addr:10.0.1.XXX  Bcast:10.0.1.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe91:c331/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:7208 errors:0 dropped:0 overruns:0 frame:0
          TX packets:515 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:595439 (581.4 KiB)  TX bytes:50430 (49.2 KiB)

but the result is the same.

The server.py is ok.

Teh server have 2 Gb. free whe i try to run the sensor

can somebody give me any idea about this?.

Thanks in advance.

**Comment by stamparm** [comment]
Do you get anything with:

`cat /var/log/maltrail/error.log`

**Comment by diegoarranz** [comment]
nothing... the log is empty now

2016-04-20 13:17 GMT+02:00 Miroslav Stampar <notifications@github.com>:

> Do you get anything with:
>
> cat /var/log/maltrail/error.log
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stamparm/maltrail/issues/84#issuecomment-212384873>
>



-- 
Diego Arranz Prada

**Comment by stamparm** [comment]
How do you run it? Do you do the disconnect from the remote console and afterwards a connect (e.g. SSH)? In those kind of cases you should run it inside terminal multiplexer like screen or tmux.

**Comment by smtszk** [comment]
It's not about maltrail, it's only about gcc and glibc version in Centos6. I remember that centos6 uses glibc 2.12, I updated to 2.16 and the problem was solved. I suggest you to install centos7, just give a try.

**Comment by stamparm** [comment]
But there are no compiled binaries inside the Maltrail. Maybe you had some problems with python libraries (e.g. `pcapy` uses some precompiled libraries)

**Comment by diegoarranz** [comment]
I install pcapy from sources with python setup.py install (v0.10.10). I´m really very bad with python and their libraries....

I can try install from a fresh installation and test again it.

**Comment by smtszk** [comment]
Yes, Stamparm, pcapy runs on libpcap and libpcap have some problems with version 2.12 of glibc. I had some troubles and it's about some parameters of building glibc and gcc. It crashes maltrail sometimes.

**Comment by stamparm** [comment]
Closing this down. Other users will be able to find this and potentially solve in their environment. I am afraid that I can't do much from Maltrail side
