### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by birka1** [stamparm/maltrail#86]
hi
just install maltrial , looking good :+1: 

is there a way to exclude threat or ip's    ? 
i seen some false positve and i want to avoide them

**Comment by stamparm** [comment]
Look into the maltrail.conf:

```
# Location of file with whitelisted entries (i.e. IP addresses, domain names, etc.) (note: take a look into 'misc/whitelist.txt')
#USER_WHITELIST
```

You can set the option `USER_WHITELIST` to a filepath of line-by-line whitelisted entries (e.g. IP addresses or IP ranges)
