### ISSUE TITLE
Multiple Sensors are not working for one centralized server.

### ISSUE THREAD

**Issue by goyalvartul** [stamparm/maltrail#8749]
I have made entries in HTTP_Address of B server and LOG_Address for B server and restarted for sensor machines A, C and D. Restarted also server.py in B server but no traffic is getting captured, any reason?

**Comment by MikhailKasimov** [comment]
Hello! 

Please, check ```# Listen port of (log collecting) UDP server
#UDP_PORT 8337``` directive status in ```Server``` section of ```maltrail.conf``` file. Should be enabled -- ```UDP_PORT 8337``` (without ```#``` sign) to make MT server to get messages from remote sensors. 

On sensor's side directive ```#LOG_SERVER <maltrail server address>:8337``` should be enabled (without ```#``` sign).

**Comment by goyalvartul** [comment]
Thanks for the update. I will do configuration.

**Comment by MikhailKasimov** [comment]
Also you can configure MT for server gets updates and sensors take them from MT local server instead of direct downloding updates by each sensor.

Make ```USE_SERVER_UPDATE_TRAILS false``` -> ```USE_SERVER_UPDATE_TRAILS true``` in ```[Server]``` section of ```maltrail.conf``` and ```#UPDATE_SERVER http://<maltrail server address>:8338/trails``` and ```USE_SERVER_UPDATE_TRAILS false``` --> ```USE_SERVER_UPDATE_TRAILS true``` directives should be activated in ```[Sensor]``` section.

**Comment by goyalvartul** [comment]
There are two servers:

Sensor Server: 138.68.241.164
Server - Where logging is happening: 167.172.197.105


In sensor server, I have configured mailtrail.conf as per your suggestions:

UDP_PORT 8337
LOG_SERVER 167.172.197.105:8338
LOG_SERVER 167.172.197.105:8337


In server, I have nothing configured only listening for traffic of sensors
but not getting still traffic.

I am attaching two files for your references, Please have a reference.

**Comment by goyalvartul** [comment]
Second thing, all things which you have mentioned as:


*"Please, check # Listen port of (log collecting) UDP server #UDP_PORT
8337 directive status in Server section of maltrail.conf file. Should be
enabled -- UDP_PORT 8337 (without # sign) to make MT server to get messages
from remote sensors.*

*On sensor's side directive #LOG_SERVER <maltrail server
address>:8337 should be enabled (without # sign)."*


 Where do I need to configure as it is on sensor side or server side?


BR//

Vartul

**Comment by MikhailKasimov** [comment]
Hello!

Currently I can see ```>telnet 167.172.197.105 8337
Connecting To 167.172.197.105...Could not open connection to the host, on port 8337: Connect failed```

On Server - Where logging is happening ```167.172.197.105```: ```UDP_PORT 8337```
On sensor side ```138.68.241.164``` : ```LOG_SERVER 167.172.197.105:8337```

```LOG_SERVER 167.172.197.105:8338``` <-- delete this.

**Comment by goyalvartul** [comment]
Thanks, it is working now, Thanks a lot. Please close the ticket and it is
very impressive for immediate response.

**Comment by MikhailKasimov** [comment]
Illustration
![Screenshot_624](https://user-images.githubusercontent.com/7167300/108638794-ab701600-7499-11eb-9e5e-7751c73e57eb.png)
