### ISSUE TITLE
"excessive no such domain (suspicious)" (heuristic)

### ISSUE THREAD

**Issue by smtszk** [stamparm/maltrail#88]
What does this log mean? Can someone explain with an example?

`"excessive no such domain (suspicious)" (heuristic)`

**Comment by stamparm** [comment]
Malware likes to generate too much NXDOMAIN (`no such domain`) traffic. Hence, that heuristics captures such events

**Comment by jjjan** [comment]
what is "bad reputation" mean?

**Comment by stamparm** [comment]
It means that somebody did some bad things before from that same IP/DNS at
some other detection system
