### ISSUE TITLE
Tag new release for FreeBSD port

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#884]
Hi,

I'm nearly finished with a OPNsense plugin, but I checked the commits the current release tag is behind and there is quite some code missing. Do you mind tagging a new release so I can update the FreeBSD port? 

Also, when I run the server with the current 0.11 tag I get in UI: Powered by Maltrail (v0.10.342)
Any ideas?

Thanks
Michael

**Comment by stamparm** [comment]
`Also, when I run the server with the current 0.11 tag I get in UI: Powered by Maltrail (v0.10.342)
Any ideas?` <- have you rerun the `server.py` ?

**Comment by stamparm** [comment]
Tag `0.12` is [done](https://github.com/stamparm/maltrail/releases)

**Comment by mimugmail** [comment]
Thanks! 

Yes, everytime I start the server I also get this message via CLI:

```
root@OPNsense:~ # /usr/local/bin/python2.7 /usr/local/maltrail/server.py
Maltrail (server) #v0.10.342

[i] using configuration file '/usr/local/maltrail/maltrail.conf'
[i] starting HTTP server at 'http://0.0.0.0:8338/'
[o] running...
```

BTW .. I wrote init scripts for server and sensor since OPNsense requires them:
https://github.com/mimugmail/plugins/blob/mt/security/maltrail/src/etc/rc.d/opnsense-maltrailsensor
https://github.com/mimugmail/plugins/blob/mt/security/maltrail/src/etc/rc.d/opnsense-maltrailserver

**Comment by stamparm** [comment]
I suspect that you are somehow running old revision.

What do you get for:

`cat /usr/local/maltrail/core/settings.py | grep "VERSION ="`

?
