### ISSUE TITLE
Possibility to add Snort rules manually?

### ISSUE THREAD

**Issue by Dededus** [stamparm/maltrail#91]
Hi, stamparm,

There is any way to add Snort rules manually to maltrail?

For example, we would like to add this rule:

_alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"SAT TorrentLocker Campaign"; flow:established,to_server; content:".php?id="; http_uri; fast_pattern:only; pcre:"/^\/[A-Z0-9]+\/[A-Z0-9]+\.php\?id=[A-Z0-9._%+-]+@(?:[A-Z0-9-]+\.)+[A-Z]{2,}/iU"; classtype:trojan-activity; sid:2018951; rev:1;)_ 

This ransomware create thousands of domains on the fly, so we can't add those domains to our blacklist because seconds later the ransomware will create thousands different domains.

It would be amazing.

Thanks a lot. Keep it up.

**Comment by stamparm** [comment]
Maltrail was meant to be a "complementary" to some Snort-like system, never a Snort replacement. Also, Snort has a whole parsing/optimization part just for running those rules in a fastest manner possible. Maltrail doesn't, nor it will. Sorry

**Comment by Dededus** [comment]
I understand :) Thanks anyway!
