### ISSUE TITLE
[Log] Severity 

### ISSUE THREAD

**Issue by nurhambali** [stamparm/maltrail#9132]
hi,

how to add maltrail severity to the log because in the maltrail record don't see the severity
![logs](https://camo.githubusercontent.com/92973003dc5fca1523aa538851595eb4e65040e5/68747470733a2f2f692e696d6775722e636f6d2f527963675672752e706e67)

**Comment by stamparm** [comment]
Hi.

This is entirely being done inside the web client. It is up to you to decide the severity in case of raw log data. In web client's case, (e.g.) malware related events have the highest priority, suspicious domain lookups and web attacks have the medium priority, while bad reputation IP connection attempts have the lowest priority.

Bye
