### ISSUE TITLE
IPv6 support (server instance)

### ISSUE THREAD

**Issue by mimugmail** [stamparm/maltrail#926]
Hi,

while my PR for OPNsense plugin is under review there was a question regarding IPv6 support of the server. It seems currently only listening on v4 addresses is supported. 

Correct? 
Any plans for adding this?

P.S. I added the new 0.12 tag to FreeBSD ports now https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236531

**Comment by stamparm** [comment]
`HTTP_ADDRESS` now support IPv6 addresses too (e.g. https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L6)

**Comment by mimugmail** [comment]
Wow, that was fast 👍 
Does this also works for users:
admin:9ab3cd9d67bf49d01f6a2e33d0bd9bc804ddbe6ce1ff5d219c42624851db5dbc:0:0.0.0.0/0

I'd only manage this via Firewall rules but one of the reviewers asked for it.

This is the PR if you're interested:
https://github.com/opnsense/plugins/pull/1257

**Comment by stamparm** [comment]
1) Now, we have to come to the common ground here. `filter_netmask(s)` is used ONLY to filter results presented to the end user (e.g. one user has access only to results for his own domain range). This is shortly mentioned in configuration file at [this place](https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L17-L20)
2) Now, I was under impression that this Issue is about making IPv6 listening server instance. Am I missing something?

**Comment by mimugmail** [comment]
1. Oh, I wasn't aware of this, then this is ok.
2. No, the question was only related to the server UI. As I only use v4 I never think of this but there are many users out there using v6 (most of them unaware for sure)

**Comment by mimugmail** [comment]
@stamparm I'd need a new release when you find time, otherwise I cannot update the FreeBSD port with the new v6 feature. It doesn't hurry as the plugin will stay in devel branch for some releases.

Really love the pace you and @MikhailKasimov are keeping 👍

**Comment by stamparm** [comment]
@mimugmail can you please ping back when you think that it should be the best time to do it? Currently, there is no timed schedule to do it, though, it passed only 8 days since the last one. Best time could be in couple of weeks (if that's ok with you)

**Comment by mimugmail** [comment]
Sure, there's no rush at all :)
