### ISSUE TITLE
Solution for/with Fail2ban on the same host

### ISSUE THREAD

**Issue by tomlp** [stamparm/maltrail#9313]
Dar all,
i played around with Maltrail and find it a very² nice tool - good Job !!!
Regarding the possibility of blocking, i propose the following solution : 
I assume fail2ban is running on the same host as the sensor does!
in maltrail.conf add in [Sensor]
`USE_FAIL2BAN true`
in core/log.py add on line 202 (after the other IF´s )
```
      if config.USE_FAIL2BAN:
             cmd = "fail2ban-client set maltrail-iptables banip %s > /etc/fail2ban/maltrail.log" % (src_ip)
             os.system(cmd)
```

in /etc/fail2ban/jail.local add
```
[maltrail-iptables]
enabled = true
filter = maltrail
bantime = 31536000
banaction = iptables-allports
action = iptables[name=MALTRAIL,port="0:65535",protocol=tcp]
logpath=/etc/fail2ban/maltrail.log
maxretry = 1
findtime = 1d
```
Note: The "protocol=tcp" should be fine tuned - with protocol=all it gives me an error i have to investigate later :)
After this adding you should start both services (sensor & fail2ban) and you should see in the fail2ban.log
```
2020-06-11 23:40:07,384 fail2ban.actions        [23020]: NOTICE  [maltrail-iptables] Ban 196.52.43.59
```

HTH & best wishes Tom

**Comment by tomlp** [comment]
one addition:
after i replayed my own config, i see that the filter for fail2ban is importand :)
in to file /etc/fail2ban/filter.d/maltrail.conf                                                                                                                            
```
[Definition]
failregex =
ignoreregex =
```
is enough :)
kr Tom

**Comment by tomlp** [comment]
an the next enhancmend:
add in maltrail.conf
```
OWN_NETWORK = xx.xx.xx.xx/27
```
and change in core/log.py from
```
 if config.USE_FAIL2BAN:
             cmd = "fail2ban-client set maltrail-iptables banip %s > /etc/fail2ban/maltrail.log" % (src_ip)
             os.system(cmd)
```
to 
```
    if config.USE_FAIL2BAN:
         if not ipaddress.ip_address(unicode(src_ip)) in ipaddress.ip_network(unicode(config.OWN_NETWORK)):
               cmd = "fail2ban-client set maltrail-iptables banip %s > /etc/fail2ban/maltrail.log" % (src_ip)
               os.system(cmd)
```
to get it work we must import the ipaddress at the beginning
```
import datetime
import os
import re
import signal
import socket           
import sys
import threading
import time
import traceback
import ipaddress ; <= add this
```
The reason for this changes : if some servers from inside make suspicious domain lookups, the complete server will be banned from fail2ban.
To avoid self-banning, i try it with "withlist", but this will be used for src_ip & dst_ip. And this will be knocked out all tests (the dst_ip is allways from your servers :) )
So i worked around this to declare the own network and check the src_ip for the own network...
May be not perfect, but it works for now and i search for further improvements :)

**Comment by tomlp** [comment]
next learning - on python3 the src_ip is allready in unicode...
to get it work on python3 you should remove the call for "unicode( ... )" in the check of the ip_address...
kr Tom

**Comment by stamparm** [comment]
With the latest revision, you have a new option `FAIL2BAN_REGEX` (look [here](https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L48)). It gives you the possibility to use the regular expression against the today's maltrail log to extract the fail2ban-able source IPs - reachable via web service call to `/fail2ban`.

Example (Note: Maltrail HTTP server is running at `http://172.16.155.1:8338`):

```
$ curl http://172.16.155.1:8338/fail2ban
119.62.209.130
94.191.31.86
195.223.171.66
191.5.45.237
157.245.119.191
182.52.138.246
187.63.220.254
129.226.127.212
45.233.10.183
5.89.118.25
39.148.37.80
202.29.22.195
177.67.74.47
80.15.21.65
52.204.47.231
191.36.185.119
191.6.81.181
1.2.172.96
188.149.210.145
122.51.189.39
103.214.140.139
119.62.209.216
132.148.204.202
146.247.255.4
170.82.75.58
120.236.251.175
45.175.159.161
119.62.209.163
119.247.36.120
49.235.81.41
112.123.69.159
```

With this same list you can do whatever the `fail2ban`/`ipset` scheme you want (e.g. via cronjob's)

**Comment by MikhailKasimov** [comment]
https://github.com/stamparm/maltrail/commit/6f9279abe7eddee953ba9898bca41ca3a4be8b6c

**Comment by tomlp** [comment]
perfekt....
