### ISSUE TITLE
[Problem] whitelist doesn't work 

### ISSUE THREAD

**Issue by BungeeHost** [stamparm/maltrail#9632]
My whitelist settings in the config:

# Location of file with whitelisted entries (i.e. IP addresses, domain names, etc.) (note: take a look into 'misc/whitelist.txt')
USER_WHITELIST misc/whitelist.txt

My whitelist.txt:

127.0.0.1
217.106.107.105
217.106.107.35
81.176.77.99

But... It doesn't work.

![image](https://user-images.githubusercontent.com/67600352/86035721-7532e180-ba45-11ea-94b6-79213155f1a8.png)

**Comment by stamparm** [comment]
`USER_WHITELIST` is used for whitelisting of problematic "trails" (e.g. if appearing at the 3rd party blacklist OR if you want to ignore static entries for some of domains), not the source of the events

**Comment by BungeeHost** [comment]
this is awkward.

Some malicious site tried to do something with our site, and scr_ip had the IP address of our DNS. And it was blocked. Is there any way to make a whitelist using scr_ip?

**Comment by BungeeHost** [comment]
this is awkward.

Some malicious site tried to do something with our site, and scr_ip had the IP address of our DNS. And it was blocked. Is there any way to make a whitelist using scr_ip?

**Comment by BungeeHost** [comment]
Я попросил моего друга провести ddos атаку. Оказалось, что вредоносным айпи читается НАШ DNS, а все айпи адреса, с которых идёт атака - записываются в строку trails и не идут в fail2ban. Нелогично получается. Вайтлист для trails, блокировка происходит по src_ip. Нет, это не нормально.

![image](https://user-images.githubusercontent.com/67600352/86067043-82b78e00-ba7c-11ea-802b-ce0084e720c7.png)

**Comment by stamparm** [comment]
1) `attack is coming from are written to the trails string and do not go to fail2ban` <- these kind of "suspicious" trails are not going to `fail2ban` list because it could case FPs
2) your DNS server is replying with those responses which Maltrail see as "suspicious" behavior. That whole line should be treated as "suspicious" and treated accordingly, while `src_ip` DOES NOT represent the attacker in similar cases
