### ISSUE TITLE
[Feature Request, sensor.py] Add --verbose key

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#97]
Hello!

Please, add --verbose key (python sensor.py --verbose) to have possibility to track the reason, why sensor.py gets status 'finished' on running.
```
k_mikhail@linux-mk500:~> sudo python ~/maltrail-master/sensor.py 
Maltrail (sensor) #v0.10.119

[i] using configuration file '/home/k_mikhail/maltrail-master/maltrail.conf'
[i] using '/var/log/maltrail' for log storage
[?] at least 384MB of free memory required
[i] loading trails...
[i] 1,121,459 trails loaded
[?] in case of any problems with packet capture on virtual interface 'any', please put all monitoring interfaces to promiscuous mode manually (e.g. 'sudo ifconfig eth0 promisc')
[i] opening interface 'any'
[i] setting capture filter 'udp or icmp or (tcp and (tcp[tcpflags] == tcp-syn or port 80 or port 1080 or port 3128 or port 8000 or port 8080 or port 8118))'
[i] preparing capture buffer...
[i] creating 1 more processes (out of total 2)
[o] running...
[i] finished
[i] please wait...
[i] finished
```

**Comment by stamparm** [comment]
Take a look into the `/var/log/maltrail/error.log`

**Comment by MikhailKasimov** [comment]
```
k_mikhail@linux-mk500:~> tail /var/log/maltrail/error.log 
2016-07-04 18:06:58 SIGTERM
2016-07-04 18:06:58 SIGTERM
2016-07-04 18:06:58 SIGTERM
2016-07-04 18:06:58 SIGTERM
2016-07-04 18:06:58 

[!] session abruptly terminated
[?] (hint: "https://stackoverflow.com/a/20997655")
2016-07-04 18:07:06 SIGTERM
```

That's all here. And
```
[o] running...
[i] finished
[i] please wait...
[i] finished
```
is on 2016-07-17. So, no way to track the reason here.

**Comment by stamparm** [comment]
And how do you run it? Do you start a terminal and it immediately does the `finished` inside that same terminal? Or do you connect to the remote SSH, then close the SSH session and start it from start?

**Comment by MikhailKasimov** [comment]
Started a terminal and it immediately does the finished inside that same terminal. Seems, it began after I tried to install pcapy manually (/pcapy/setup.py install) from https://github.com/CoreSecurity/pcapy (0.10.10)... Can you check that on your side?

**Comment by stamparm** [comment]
I haven't seen this kind of behaviour, but I believe that somebody did mention that he had the same problem with `pcapy`. I am really not able to reproduce it on both Debian and Ubuntu

**Comment by MikhailKasimov** [comment]
What version of pcapy is installed on Ubuntu and Debian? I'm using openSUSE Leap 42.1 and sensor.py worked fine until tonight. So, I really try to investigate the reason of sensor stopping. Possibly it tries to check something and check is getting failed. So, --verbose will be really appreciated. I also asked pcapy developer about 0.10.10, now I'm waiting for his reply -- possibly /pcapy/setup.py install works incorrectly a little bit...

**Comment by stamparm** [comment]
Maltrail is pretty verbose. I am not sure what should it do more verbose. I would say that it gets `SIGTERM` and it terminates. There is nothing to be verbose there.

As of pcapy version, I have a standard `apt-get` one: `Installed: 0.10.8-1build1`

**Comment by stamparm** [comment]
p.s. in case of any benign problem, there would be a console warning. In case of major problem, there would be a `/var/log/maltrail/error.log` entry. As said, I believe that it gets a signal to interrupt from the outside for some reason

**Comment by MikhailKasimov** [comment]
ok, thank you!

**Comment by MikhailKasimov** [comment]
Seems to be resolved. sensor.py starts normally after deleting redundant .egg-info file from my experiments with installing version 0.10.10 (/pcapy/setup.py install):
```
k_mikhail@linux-mk500:~> ls /usr/lib64/python2.7/site-packages/ | grep pcapy
pcapy-0.10.5-py2.7.egg-info
pcapy-0.10.10-py2.7.egg-info <---- to delete
pcapy.so <---- installed 0.10.5 from packages
```
But here is the question -- can we log such cases as pcapy version conflicts?

**Comment by stamparm** [comment]
I would need to be able to reproduce. Which OS and how did you installed
pcapy in the first place?

**Comment by MikhailKasimov** [comment]
openSUSE Leap 42.1 (on XFCE).

Steps-to-reproduce:
1. pcapy (0.10.5) was installed from https://software.opensuse.org/package/python-pcapy?search_term=pcapy
2. Download pcapy 0.10.10 from https://github.com/CoreSecurity/pcapy
3. Install gcc-c++: ```zypper in gcc-c++```
4. Unpack 0.10.10 and run ```setup.py install```. This will generate ```0.10.10.egg-info``` file in ```/usr/lib64/python2.7/site-packages/```
5. Run Maltrail sensor ```python sensor.py```

**Comment by stamparm** [comment]
Will try to do it later today. Thanks

**Comment by stamparm** [comment]
Just tried to run OpenSUSE inside the VMWare and go the kernel panic at the boot time. Same thing with `failsafe` settings.

Nevertheless, if you still have the "testing" environment where this happens, I wonder do you see anything unusual near the point of failure when running the sensor like:

1) `python -v sensor.py`
2) `strace ./sensor.py`

**Comment by MikhailKasimov** [comment]
> Just tried to run OpenSUSE inside the VMWare and go the kernel panic at the boot time. Same thing with failsafe settings.

Any tracelogs?

> Nevertheless, if you still have the "testing" environment where this happens

ok, will try to. Thank you again for assistance! Report can be closed.

**Comment by stamparm** [comment]
![1234](https://cloud.githubusercontent.com/assets/921555/16933179/c5301290-4d4b-11e6-83cd-59f6e7acc54c.png)

**Comment by MikhailKasimov** [comment]
Hmmm... ``` k_mikhail@linux-mk500:~> uname -r
4.1.27-24-default```, but, anyway, will send it to opesuse's bugzilla. Thanks for info!

**Comment by MikhailKasimov** [comment]
Try to reproduce this algo -- pcapy is installed on clean system from ```pip install pcapy``` And then to run sensor.py. Seems to be the same problem:
```
[o] running...
[i] finished
[i] please wait...
[i] finished
```
