### ISSUE TITLE
Is possible to add severity to syslog?

### ISSUE THREAD

**Issue by EternalAdvance** [stamparm/maltrail#9738]
CEF:0|  
I know 0 is the severity column.  but I could not find configure in maltrail.conf 
Does anybody knows how to put severity in syslog format? Is it possible?

**Comment by stamparm** [comment]
1) CEF_FORMAT is described with https://github.com/stamparm/maltrail/blob/master/core/settings.py#L43
2) `CEF:0` is actually the constant prefix used by Maltrail
3) Calculation of severity is actually left to you (and your e.g. SIEM). Maltrail calculates it inside the web client (web page server by the `server.py`) and it treats everything malware related with the highest severity, while the rest is either medium or low. Severity is calculated based on the `info` column content.

**Comment by EternalAdvance** [comment]
Thank you for your comment.
I added the code which calculates event severity at log.py. and it works fine.

**Comment by EternalAdvance** [comment]
Here is the code that I added

**INFO_SEVERITY = {"malware":3,"adversary":3,"ransomware":3,"reputation":1,"attacker":1,"spammer":1,"compromised":1,"crawler":1,"scanning":1,"phishing":2}**

                if config.SYSLOG_SERVER:
                    extension = "src=%s spt=%s dst=%s dpt=%s trail=%s ref=%s" % (src_ip, src_port, dst_ip, dst_port, trail, reference)
                    **event_severity = 0**
                    **if "(custom)" in reference:
                        event_severity = 3
                    elif "(remote custom)" in reference:
                        event_severity = 3
                    elif ("potential malware site") in info:
                        event_severity = 2
                    elif ("malwaredomainlist") in reference:
                        event_severity = 3
                    elif ("malware distribution") in info:
                        event_severity = 2
                    elif ("mass scanner") in info:
                        event_severity = 1
                    elif ("(suspicious)") in info:
                        event_severity = 2
                    else:
                        for keyword in INFO_SEVERITY.keys():
                            if keyword in info:
                                event_severity = INFO_SEVERITY[keyword]
                                break**

                    _ = CEF_FORMAT.format(syslog_time=time.strftime("%b %d %H:%M:%S", time.localtime(int(sec))), host=HOSTNAME, device_vendor=NAME, device_product="sensor", device_version=VERSION, signature_id=time.strftime("%Y-%m-%d", time.localtime(os.path.getctime(config.TRAILS_FILE))), name=info, severity=**event_severity**, extension=extension)
