### ISSUE TITLE
sensor.py doesn't start with pcapy 0.10.10 version

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/maltrail#98]
Hello!

Have tried to install pcapy on clean machine with ``` pip install pcapy```command. After pcapy was installed successfully, I tried to run ```python sensor.py```. And again, as it was described in #97 

``` 
[o] running...
[i] finished
[i] please wait...
[i] finished
```

And now, there are no other pcapy versions from ```apt-get``` and|or ```zypper``` installations. Please, check this out. For example -- do first ```apt-get remove python-pcapy``` and then do ``` pip install pcapy```. To check the version of installed pcapy, do ```pip show pcapy```. I suppose, the problem reproducing will be successful here.

**Comment by stamparm** [comment]
Thank you very much. I am able to reproduce. Will patch it ASAP

**Comment by MikhailKasimov** [comment]
version128: Works correctly for now. Thank you for fixing!

**Comment by stamparm** [comment]
Thank you for finding the bug
